export const battles = [
  {
    id: "panipat-1",
    name: "First Battle of Panipat",
    year: 1526,
    state: "Haryana",
    x: 35, // Approximate percentage coordinates on the SVG map
    y: 25,
    image: "assets/panipat.jpg",
    opponents: "Babur vs Ibrahim Lodi",
    outcome: "Mughal victory.",
    significance: "Marked the beginning of the Mughal Empire in India.",
    background: "Babur, the ruler of Kabul, invaded India at the invitation of Daulat Khan Lodi.",
    commanders: "Babur, Ibrahim Lodi",
    strategy: "Babur used the Tulughma and Araba tactics, and firearms effectively.",
    politicalImpact: "End of the Delhi Sultanate and establishment of Mughal rule.",
    longTerm: "Mughals ruled India for centuries.",
    relatedEvents: "Battle of Khanwa"
  },
  {
    id: "panipat-2",
    name: "Second Battle of Panipat",
    year: 1556,
    state: "Haryana",
    x: 36,
    y: 26,
    image: "assets/panipat.jpg",
    opponents: "Akbar vs Hemu",
    outcome: "Mughal victory.",
    significance: "Consolidated Akbar's rule in North India.",
    background: "Hemu had captured Delhi and Agra, and Akbar's forces marched to reclaim them.",
    commanders: "Bairam Khan, Hemu",
    strategy: "A stray arrow struck Hemu in the eye, turning the tide of the battle.",
    politicalImpact: "Restored Mughal control over northern India.",
    longTerm: "Set the stage for the expansion of the Mughal Empire under Akbar.",
    relatedEvents: "Third Battle of Panipat"
  },
  {
    id: "talikota",
    name: "Battle of Talikota",
    year: 1565,
    state: "Karnataka",
    x: 40,
    y: 65,
    image: "assets/talikota.jpg",
    opponents: "Deccan Sultanates vs Vijayanagara Empire",
    outcome: "Deccan Sultanates victory.",
    significance: "Led to the decline of the Vijayanagara Empire.",
    background: "An alliance of the Deccan Sultanates formed against the powerful Vijayanagara Empire.",
    commanders: "Ali Adil Shah I, Rama Raya",
    strategy: "The Sultanates used superior artillery and cavalry.",
    politicalImpact: "Destruction of the city of Vijayanagara (Hampi).",
    longTerm: "Shifted the balance of power in South India.",
    relatedEvents: "Deccan Wars"
  },
  {
    id: "haldighati",
    name: "Battle of Haldighati",
    year: 1576,
    state: "Rajasthan",
    x: 25,
    y: 40,
    image: "assets/haldighati.jpg",
    opponents: "Mughal Empire vs Mewar",
    outcome: "Mughal victory (tactical), Mewar resistance continued.",
    significance: "A legendary battle of Rajput resistance against Mughal expansion.",
    background: "Maharana Pratap refused to submit to Akbar's suzerainty.",
    commanders: "Man Singh I, Maharana Pratap",
    strategy: "Fought in a narrow mountain pass using traditional Rajput tactics.",
    politicalImpact: "Mughals gained control of the plains, but Pratap continued guerrilla warfare.",
    longTerm: "Symbol of Rajput valor and resistance.",
    relatedEvents: "Siege of Chittorgarh"
  },
  {
    id: "plassey",
    name: "Battle of Plassey",
    year: 1757,
    state: "West Bengal",
    x: 75,
    y: 45,
    image: "assets/plassey.jpg",
    opponents: "British East India Company vs Nawab of Bengal",
    outcome: "British victory.",
    significance: "Marked the beginning of major British political control in India.",
    background: "Tensions over trade privileges and the Black Hole of Calcutta incident.",
    commanders: "Robert Clive, Siraj-ud-Daulah",
    strategy: "Clive conspired with Mir Jafar, the Nawab's commander, who defected during the battle.",
    politicalImpact: "The British gained vast wealth and control over Bengal's revenues.",
    longTerm: "The foundation of the British Raj in India.",
    relatedEvents: "Battle of Buxar"
  },
  {
    id: "buxar",
    name: "Battle of Buxar",
    year: 1764,
    state: "Bihar",
    x: 65,
    y: 40,
    image: "assets/buxar.jpg",
    opponents: "British East India Company vs Combined Indian Forces",
    outcome: "British victory.",
    significance: "Solidified British authority over Bengal, Bihar, and Odisha.",
    background: "Mir Qasim, the Nawab of Bengal, allied with the Nawab of Awadh and the Mughal Emperor to oust the British.",
    commanders: "Hector Munro, Mir Qasim, Shuja-ud-Daula, Shah Alam II",
    strategy: "Superior British discipline and artillery prevailed against a larger but uncoordinated force.",
    politicalImpact: "Treaty of Allahabad granted the EIC the Diwani rights (right to collect taxes).",
    longTerm: "Transformed the EIC from a trading company to a sovereign power.",
    relatedEvents: "Anglo-Mysore Wars"
  }
];
