/* ==========================================================================
   TIGER RESERVES OF INDIA — DATASET
   Areas and tiger numbers are approximate. Reserve boundaries change with
   fresh notifications, and population figures come from the four-yearly
   All India Tiger Estimation, which reports ranges rather than exact counts.
   Treat every number on this page as indicative and dated.
   ========================================================================== */

const TR_LANDSCAPES = [
  { key: 'shivalik', name: 'Shivalik Hills & Gangetic Plain', icon: '🌾', blurb: 'Terai grassland and sal forest along the Himalayan foothills.' },
  { key: 'central', name: 'Central India & Eastern Ghats', icon: '🌳', blurb: 'The largest landscape by tiger numbers — teak and sal on the Deccan.' },
  { key: 'ghats', name: 'Western Ghats', icon: '⛰️', blurb: 'The most continuous tiger habitat left in the country.' },
  { key: 'northeast', name: 'North-East Hills & Brahmaputra', icon: '🍃', blurb: 'Floodplain grassland and wet evergreen hill forest.' },
  { key: 'sundarbans', name: 'Sundarbans', icon: '🌊', blurb: 'The only mangrove tiger population in the world.' },
];

/* `category` describes a reserve's population story only. Founding status is
   deliberately not one of these values: the two facts are independent — Corbett
   is both a founding reserve and a high-density source site — and collapsing
   them into a single field made the founding filter under-report. Founding
   status is derived from `notified` instead, using TR_FOUNDING_YEAR below. */
const TR_CATEGORIES = [
  { key: 'recovery', name: 'Recovery Story', icon: '📈' },
  { key: 'source', name: 'High-Density Source Site', icon: '🔥' },
  { key: 'lowdensity', name: 'Low Density / Rebuilding', icon: '🌱' },
];

/* Project Tiger launched on 1 April 1973 with nine reserves. A reserve is a
   founding reserve if and only if it was notified that year, so the filter is
   derived rather than hand-maintained and cannot drift out of sync. */
const TR_FOUNDING_YEAR = 1973;
const TR_FOUNDING_CHIP = { key: 'founding', name: 'Founding Nine (1973)', icon: '🏛️' };

/* --------------------------------------------------------------------------
   The reserves. `tigers` is a mid-range estimate from the most recent
   published cycle; `tigerNote` carries the caveat where one is needed.
   -------------------------------------------------------------------------- */
const TIGER_RESERVES = [
  {
    name: 'Jim Corbett Tiger Reserve',
    icon: '🐅',
    state: 'Uttarakhand',
    landscape: 'shivalik',
    category: 'source',
    notified: 1973,
    coreKm2: 821,
    bufferKm2: 466,
    tigers: 260,
    tigerNote: 'Among the highest tiger densities recorded anywhere in the world.',
    rivers: ['Ramganga', 'Kosi', 'Sonanadi'],
    tagline: 'The reserve Project Tiger was launched from',
    desc: 'India\'s oldest national park, notified as Hailey National Park in 1936 and renamed for Jim Corbett in 1957. Project Tiger was formally launched here on 1 April 1973. The Patli Dun valley, the Ramganga reservoir and the tall Dhikala grasslands together support a prey base dense enough to sustain tiger densities that most reserves cannot approach.',
    species: ['Tiger', 'Asian elephant', 'Leopard', 'Hog deer', 'Gharial', 'Mahseer'],
    feature: 'The Dhikala chaur — a grassland floodplain that concentrates chital and hog deer, and therefore tigers.',
  },
  {
    name: 'Bandipur Tiger Reserve',
    icon: '🌿',
    state: 'Karnataka',
    landscape: 'ghats',
    category: 'source',
    notified: 1973,
    coreKm2: 872,
    bufferKm2: 584,
    tigers: 150,
    tigerNote: 'Counted as part of the wider Nilgiri Biosphere population, which moves across state lines.',
    rivers: ['Kabini', 'Moyar', 'Nugu'],
    tagline: 'One corner of the largest tiger population on earth',
    desc: 'Bandipur sits at the junction of the Western and Eastern Ghats, contiguous with Nagarhole to the north-west, Mudumalai to the south and Wayanad to the west. Treating any of these four as a separate population is a mistake — together they form the Nilgiri Biosphere Reserve complex, which holds more tigers than any other single landscape in the world.',
    species: ['Tiger', 'Asian elephant', 'Gaur', 'Dhole', 'Sloth bear', 'Four-horned antelope'],
    feature: 'A night traffic ban on the highways crossing the reserve, upheld through repeated legal challenge.',
  },
  {
    name: 'Kanha Tiger Reserve',
    icon: '🦌',
    state: 'Madhya Pradesh',
    landscape: 'central',
    category: 'source',
    notified: 1973,
    coreKm2: 917,
    bufferKm2: 1134,
    tigers: 105,
    tigerNote: '',
    rivers: ['Banjar', 'Halon'],
    tagline: 'The reserve that saved the barasingha',
    desc: 'Kanha\'s sal forests and open maidans are the setting Kipling drew on, but its more concrete achievement is the hard-ground barasingha. The subspecies was down to around 66 animals in the 1960s and survived only here. Fenced enclosures, predator exclusion and grassland management brought it back into the high hundreds, and animals have since been translocated to Satpura.',
    species: ['Tiger', 'Hard-ground barasingha', 'Gaur', 'Dhole', 'Indian wolf', 'Blackbuck'],
    feature: 'India\'s first reserve to adopt an official mascot — Bhoorsingh the barasingha.',
  },
  {
    name: 'Ranthambore Tiger Reserve',
    icon: '🏰',
    state: 'Rajasthan',
    landscape: 'central',
    category: 'source',
    notified: 1973,
    coreKm2: 1113,
    bufferKm2: 297,
    tigers: 57,
    tigerNote: 'Approaching the ceiling of what the reserve can hold; dispersal out of it is now a management problem.',
    rivers: ['Chambal', 'Banas'],
    tagline: 'Tigers among the ruins of a tenth-century fort',
    desc: 'Dry deciduous forest wrapped around the Ranthambore Fort, in the last hills of the Aravallis before the Vindhyas. The habitat is thin and the reserve is small, which makes its tigers unusually visible and unusually well documented — Machhli, tracked across nearly twenty years, was probably the most photographed wild tiger that has ever lived.',
    species: ['Tiger', 'Leopard', 'Sloth bear', 'Marsh crocodile', 'Sambar', 'Indian gazelle'],
    feature: 'Surplus tigers from Ranthambore have been used to repopulate Sariska and Mukundra.',
  },
  {
    name: 'Sundarbans Tiger Reserve',
    icon: '🌊',
    state: 'West Bengal',
    landscape: 'sundarbans',
    category: 'source',
    notified: 1973,
    coreKm2: 1700,
    bufferKm2: 885,
    tigers: 100,
    tigerNote: 'Estimation here relies on camera traps placed on the few dry patches; the figure carries a wide band.',
    rivers: ['Matla', 'Bidya', 'Raimangal'],
    tagline: 'The only mangrove tiger population in the world',
    desc: 'A tidal delta of mangrove islands where the tigers swim between land masses, drink brackish water, and hunt in an environment no other tiger population occupies. Human–tiger conflict here is unlike anywhere else in India, because the forest is entered daily by people collecting honey, crab and fish.',
    species: ['Tiger', 'Estuarine crocodile', 'Fishing cat', 'Water monitor', 'Irrawaddy dolphin', 'Horseshoe crab'],
    feature: 'Part of a transboundary population continuous with the Bangladesh Sundarbans.',
  },
  {
    name: 'Manas Tiger Reserve',
    icon: '🦏',
    state: 'Assam',
    landscape: 'northeast',
    category: 'recovery',
    notified: 1973,
    coreKm2: 840,
    bufferKm2: 2310,
    tigers: 58,
    tigerNote: '',
    rivers: ['Manas', 'Beki', 'Hakua'],
    tagline: 'Lost to conflict, then rebuilt',
    desc: 'Manas is a World Heritage Site that was placed on the danger list in 1992 after years of civil unrest destroyed its infrastructure and emptied much of its wildlife. It was removed from that list in 2011. Rhinos were reintroduced, swamp deer returned, and the tiger population recovered — one of the clearest demonstrations that a reserve can come back if the habitat survives.',
    species: ['Tiger', 'Greater one-horned rhinoceros', 'Pygmy hog', 'Golden langur', 'Hispid hare', 'Bengal florican'],
    feature: 'Contiguous with Royal Manas National Park in Bhutan, forming a transboundary conservation area.',
  },
  {
    name: 'Melghat Tiger Reserve',
    icon: '🌲',
    state: 'Maharashtra',
    landscape: 'central',
    category: 'lowdensity',
    notified: 1973,
    coreKm2: 1500,
    bufferKm2: 1268,
    tigers: 55,
    tigerNote: '',
    rivers: ['Tapti', 'Sipna', 'Khandu'],
    tagline: 'The Satpura catchment that feeds the Tapti',
    desc: 'Melghat means "meeting of the ghats", and the reserve is a rugged block of the southern Satpura range in Amravati district. It is a founding reserve and one of the most important catchments in central India — the streams rising here feed the Tapti and the Purna. Its terrain is steep enough that much of the core sees very little human traffic.',
    species: ['Tiger', 'Indian giant squirrel', 'Sloth bear', 'Gaur', 'Forest owlet', 'Wild dog'],
    feature: 'One of the few reserves where the critically endangered forest owlet is regularly recorded.',
  },
  {
    name: 'Palamau Tiger Reserve',
    icon: '🍂',
    state: 'Jharkhand',
    landscape: 'central',
    category: 'lowdensity',
    notified: 1973,
    coreKm2: 414,
    bufferKm2: 715,
    tigers: 5,
    tigerNote: 'Numbers have been very low for two decades; the reserve is in a rebuilding phase.',
    rivers: ['North Koel', 'Auranga', 'Burha'],
    tagline: 'Where the first tiger census in the world was attempted',
    desc: 'Palamau has an unusual place in conservation history: the first attempt anywhere to count tigers by pug marks was made in these forests in 1932. It is a founding Project Tiger reserve, but decades of disturbance left its tiger numbers among the lowest of any reserve. Prey base recovery and habitat consolidation are the current focus.',
    species: ['Tiger', 'Elephant', 'Indian wolf', 'Gaur', 'Four-horned antelope', 'Sloth bear'],
    feature: 'The Betla sal forests and the ruins of two seventeenth-century Chero forts sit inside the reserve.',
  },
  {
    name: 'Simlipal Tiger Reserve',
    icon: '💧',
    state: 'Odisha',
    landscape: 'central',
    category: 'lowdensity',
    notified: 1973,
    coreKm2: 1195,
    bufferKm2: 1555,
    tigers: 20,
    tigerNote: 'Includes India\'s only known population of pseudo-melanistic tigers.',
    rivers: ['Budhabalanga', 'Khairi', 'Salandi'],
    tagline: 'Home of the black tiger',
    desc: 'Simlipal is a sal-dominated plateau in the Eastern Ghats, and the only place in the world where pseudo-melanistic tigers — animals whose stripes have broadened and merged into near-black patches — occur as a breeding population. The trait is genetic and its concentration here is a signature of a small, isolated population with limited gene flow.',
    species: ['Pseudo-melanistic tiger', 'Elephant', 'Gaur', 'Chausingha', 'Mugger crocodile', 'Giant squirrel'],
    feature: 'Isolation has produced a distinctive coat morph — and, less happily, a genetic bottleneck.',
  },
  {
    name: 'Bandhavgarh Tiger Reserve',
    icon: '🏛️',
    state: 'Madhya Pradesh',
    landscape: 'central',
    category: 'source',
    notified: 1993,
    coreKm2: 716,
    bufferKm2: 820,
    tigers: 165,
    tigerNote: 'Density in the Tala zone is among the highest in India.',
    rivers: ['Son', 'Johila', 'Charanganga'],
    tagline: 'A fort on a cliff, and tigers below it',
    desc: 'Bandhavgarh wraps around a 2,000-year-old fort on a sandstone plateau, with a valley system below that holds an exceptional density of tigers. The reserve is a net exporter of animals into the wider central Indian landscape, which makes its corridors to Sanjay-Dubri and Panna more important than the reserve boundary itself.',
    species: ['Tiger', 'Leopard', 'Sloth bear', 'Chital', 'Indian bison', 'Vultures'],
    feature: 'A reclining Vishnu statue carved in the tenth century sits at a spring inside the core zone.',
  },
  {
    name: 'Pench Tiger Reserve',
    icon: '📖',
    state: 'Madhya Pradesh & Maharashtra',
    landscape: 'central',
    category: 'source',
    notified: 1992,
    coreKm2: 411,
    bufferKm2: 768,
    tigers: 75,
    tigerNote: 'Managed as two administrative units across the state boundary but one biological population.',
    rivers: ['Pench', 'Kulbhera'],
    tagline: 'Split by a state line, joined by a river',
    desc: 'The Pench river runs through the middle of the reserve and the Madhya Pradesh–Maharashtra border runs alongside it. The teak forest here is the country Kipling described in the Jungle Book, and the reserve is a demonstration that tigers do not read administrative boundaries — the two halves are managed separately but function as one population.',
    species: ['Tiger', 'Indian gaur', 'Wild dog', 'Nilgai', 'Barking deer', 'Malabar pied hornbill'],
    feature: 'The reserve\'s corridor to Kanha carries regular tiger movement and is a national test case for corridor protection.',
  },
  {
    name: 'Tadoba-Andhari Tiger Reserve',
    icon: '🎋',
    state: 'Maharashtra',
    landscape: 'central',
    category: 'source',
    notified: 1995,
    coreKm2: 626,
    bufferKm2: 1102,
    tigers: 97,
    tigerNote: 'One of the fastest-growing tiger populations in India over the past decade.',
    rivers: ['Andhari', 'Erai'],
    tagline: 'Maharashtra\'s oldest and largest reserve',
    desc: 'Tadoba\'s tiger population has grown quickly enough that the buffer zone now holds breeding tigers as well as the core, which is unusual and has changed how the reserve is managed. It also means the reserve sits at the sharp end of India\'s human–tiger conflict problem — Chandrapur district records some of the country\'s highest conflict figures.',
    species: ['Tiger', 'Leopard', 'Sloth bear', 'Indian bison', 'Marsh crocodile', 'Honey badger'],
    feature: 'Buffer-zone tourism has been developed deliberately, to spread pressure away from the core.',
  },
  {
    name: 'Nagarhole Tiger Reserve',
    icon: '🐘',
    state: 'Karnataka',
    landscape: 'ghats',
    category: 'source',
    notified: 1999,
    coreKm2: 643,
    bufferKm2: 205,
    tigers: 140,
    tigerNote: 'Part of the Nilgiri complex; individuals move freely into Bandipur and Wayanad.',
    rivers: ['Kabini', 'Lakshmanatirtha', 'Nagarhole'],
    tagline: 'The reserve where camera-trap science was worked out',
    desc: 'Nagarhole, also called Rajiv Gandhi National Park, is where much of the statistical method now used to estimate tiger numbers across India was developed and validated. The Kabini backwaters draw one of the largest dry-season gatherings of Asian elephants anywhere, and the prey density is exceptional.',
    species: ['Tiger', 'Asian elephant', 'Leopard', 'Dhole', 'Gaur', 'Malabar giant squirrel'],
    feature: 'Long-term individual-identification datasets here run to more than three decades.',
  },
  {
    name: 'Periyar Tiger Reserve',
    icon: '🛶',
    state: 'Kerala',
    landscape: 'ghats',
    category: 'recovery',
    notified: 1978,
    coreKm2: 881,
    bufferKm2: 44,
    tigers: 35,
    tigerNote: '',
    rivers: ['Periyar', 'Pamba'],
    tagline: 'Poachers turned into guides',
    desc: 'Periyar is built around an artificial lake created by the Mullaperiyar dam in 1895, whose drowned tree stumps are the reserve\'s most recognisable feature. Its lasting contribution to Indian conservation is the India Eco-Development Project, which brought former sandalwood smugglers and poachers into the reserve as guides and patrol staff — a model since copied widely.',
    species: ['Tiger', 'Asian elephant', 'Nilgiri tahr', 'Lion-tailed macaque', 'Great hornbill', 'Nilgiri marten'],
    feature: 'Community-run tourism programmes staffed by former forest offenders.',
  },
  {
    name: 'Kaziranga Tiger Reserve',
    icon: '🦏',
    state: 'Assam',
    landscape: 'northeast',
    category: 'source',
    notified: 2006,
    coreKm2: 626,
    bufferKm2: 548,
    tigers: 104,
    tigerNote: 'The highest tiger density of any reserve in India, driven by extraordinary prey biomass.',
    rivers: ['Brahmaputra', 'Diphlu', 'Mora Diphlu'],
    tagline: 'Best known for rhinos, but the densest tiger habitat in India',
    desc: 'Kaziranga is famous for holding roughly two-thirds of the world\'s greater one-horned rhinos, and the tigers are frequently overlooked. They should not be: the alluvial grasslands of the Brahmaputra floodplain support such a high biomass of hog deer, swamp deer and wild buffalo that tiger density here exceeds every other Indian reserve.',
    species: ['Tiger', 'Greater one-horned rhinoceros', 'Wild water buffalo', 'Eastern swamp deer', 'Hog deer', 'Gangetic dolphin'],
    feature: 'Annual monsoon flooding is not a disaster here but the process that maintains the grassland.',
  },
  {
    name: 'Sariska Tiger Reserve',
    icon: '🔄',
    state: 'Rajasthan',
    landscape: 'central',
    category: 'recovery',
    notified: 1978,
    coreKm2: 881,
    bufferKm2: 332,
    tigers: 30,
    tigerNote: 'Every tiger in Sariska today descends from animals moved in after 2008.',
    rivers: ['Ruparel', 'Sariska nallahs'],
    tagline: 'India\'s most important conservation failure — and its repair',
    desc: 'In 2004–05 Sariska was found to have lost every one of its tigers to poaching. The shock triggered the Tiger Task Force, the 2006 amendment to the Wild Life (Protection) Act and the creation of the NTCA. In 2008 tigers were airlifted in from Ranthambore in the first such reintroduction attempted in India, and the population has bred since.',
    species: ['Tiger', 'Leopard', 'Striped hyena', 'Nilgai', 'Sambar', 'Indian peafowl'],
    feature: 'The tenth-century Neelkanth temples and the Kankwari fort stand inside the reserve.',
  },
  {
    name: 'Panna Tiger Reserve',
    icon: '💎',
    state: 'Madhya Pradesh',
    landscape: 'central',
    category: 'recovery',
    notified: 1994,
    coreKm2: 576,
    bufferKm2: 1002,
    tigers: 65,
    tigerNote: 'From zero in 2009 to a self-sustaining population — the most successful reintroduction in India.',
    rivers: ['Ken'],
    tagline: 'Zero tigers in 2009, a breeding population today',
    desc: 'Panna lost its entire tiger population by 2009, four years after Sariska. What followed was better handled: two tigresses and a male were translocated in, the reintroduced animals bred, and the reserve now holds a self-sustaining population. It was declared a UNESCO Biosphere Reserve in 2020. The proposed Ken-Betwa river link, which would submerge a substantial part of the core, is the open question hanging over it.',
    species: ['Tiger', 'Leopard', 'Sloth bear', 'Indian vulture', 'Chinkara', 'Gharial'],
    feature: 'The Ken river gorge and its waterfalls run through the middle of the reserve.',
  },
  {
    name: 'Satpura Tiger Reserve',
    icon: '🥾',
    state: 'Madhya Pradesh',
    landscape: 'central',
    category: 'lowdensity',
    notified: 2000,
    coreKm2: 1339,
    bufferKm2: 794,
    tigers: 50,
    tigerNote: '',
    rivers: ['Denwa', 'Sonbhadra', 'Tawa'],
    tagline: 'The reserve you walk into',
    desc: 'Satpura is the largest contiguous block of the Satpura-Maikal landscape and one of very few Indian reserves that permits walking safaris, canoeing and night drives in designated buffer areas. Its terrain — deep ravines, sandstone cliffs and rock-shelter art — is closer to the Deccan trap country than to the flat sal forests further east.',
    species: ['Tiger', 'Indian giant squirrel', 'Sloth bear', 'Barasingha (reintroduced)', 'Leopard', 'Indian skimmer'],
    feature: 'Prehistoric rock paintings in shelters inside the reserve, some thought to be several thousand years old.',
  },
  {
    name: 'Nagarjunsagar-Srisailam Tiger Reserve',
    icon: '🗺️',
    state: 'Andhra Pradesh & Telangana',
    landscape: 'central',
    category: 'lowdensity',
    notified: 1983,
    coreKm2: 2596,
    bufferKm2: 1150,
    tigers: 70,
    tigerNote: 'Spread thinly across the largest reserve area in the country.',
    rivers: ['Krishna'],
    tagline: 'India\'s largest tiger reserve by area',
    desc: 'At close to 3,700 km² across two states, Nagarjunsagar-Srisailam is the largest tiger reserve in India. The Krishna river cuts a gorge through the Nallamala hills at its centre. Density is low — this is dry deciduous and scrub country with a modest prey base — but the sheer size makes it strategically important for the Eastern Ghats population.',
    species: ['Tiger', 'Leopard', 'Indian pangolin', 'Mugger crocodile', 'Chowsingha', 'Blackbuck'],
    feature: 'Home to the Chenchu, a Particularly Vulnerable Tribal Group who live within the reserve.',
  },
  {
    name: 'Valmiki Tiger Reserve',
    icon: '🌾',
    state: 'Bihar',
    landscape: 'shivalik',
    category: 'recovery',
    notified: 1990,
    coreKm2: 899,
    bufferKm2: 361,
    tigers: 54,
    tigerNote: 'Numbers have roughly quadrupled since 2010.',
    rivers: ['Gandak', 'Masan', 'Bhapsa'],
    tagline: 'Bihar\'s only tiger reserve, and a genuine turnaround',
    desc: 'Valmiki lies on the Indo-Nepal border in West Champaran, contiguous with Nepal\'s Chitwan National Park. For years it was written off. Sustained anti-poaching work, grassland restoration and cross-border coordination with Nepal have made it one of the clearest recovery curves in India — from single figures to over fifty tigers.',
    species: ['Tiger', 'Indian rhinoceros (occasional)', 'Sloth bear', 'Gaur', 'Hog deer', 'Gharial'],
    feature: 'Forms a single transboundary tiger conservation unit with Chitwan across the Gandak.',
  },
  {
    name: 'Dudhwa Tiger Reserve',
    icon: '🦌',
    state: 'Uttar Pradesh',
    landscape: 'shivalik',
    category: 'source',
    notified: 1987,
    coreKm2: 1093,
    bufferKm2: 1108,
    tigers: 135,
    tigerNote: 'Counted with Katarniaghat and Kishanpur, which are part of the same reserve.',
    rivers: ['Sharda', 'Suheli', 'Mohana'],
    tagline: 'The last of the Terai grasslands',
    desc: 'Dudhwa protects the largest surviving block of Terai grassland and swamp forest in India, an ecosystem that has otherwise been almost entirely converted to sugarcane and paddy. It holds swamp deer in numbers found nowhere else, and rhinos reintroduced from Assam in 1984 have established a small breeding population.',
    species: ['Tiger', 'Swamp deer', 'Greater one-horned rhinoceros', 'Hispid hare', 'Bengal florican', 'Gangetic dolphin'],
    feature: 'The Katarniaghat unit protects one of India\'s few remaining breeding gharial stretches.',
  },
  {
    name: 'Anamalai Tiger Reserve',
    icon: '🐘',
    state: 'Tamil Nadu',
    landscape: 'ghats',
    category: 'lowdensity',
    notified: 2007,
    coreKm2: 958,
    bufferKm2: 521,
    tigers: 25,
    tigerNote: '',
    rivers: ['Aliyar', 'Amaravathi', 'Parambikulam'],
    tagline: 'Elephant hills on the Kerala border',
    desc: 'Anamalai — the elephant hills — spans altitudes from around 300 m to over 2,400 m, which gives it an unusually wide range of forest types in a small area: thorn forest, deciduous forest, wet evergreen shola and montane grassland. It adjoins Parambikulam in Kerala, and the two are managed as a single landscape.',
    species: ['Tiger', 'Asian elephant', 'Nilgiri tahr', 'Lion-tailed macaque', 'Grizzled giant squirrel', 'Great hornbill'],
    feature: 'Six indigenous communities live within the reserve, including the Kadar and the Muduvar.',
  },
  {
    name: 'Parambikulam Tiger Reserve',
    icon: '🌳',
    state: 'Kerala',
    landscape: 'ghats',
    category: 'lowdensity',
    notified: 2009,
    coreKm2: 391,
    bufferKm2: 252,
    tigers: 20,
    tigerNote: '',
    rivers: ['Parambikulam', 'Thunacadavu', 'Peruvaripallam'],
    tagline: 'Where the largest teak tree in the world stands',
    desc: 'A compact reserve wedged between the Anamalai and Nelliyampathy hills, Parambikulam is unusual for how thoroughly its tribal communities have been brought into management — colony residents run the eco-tourism operation. Kannimara, a teak thought to be several hundred years old, stands within the reserve.',
    species: ['Tiger', 'Elephant', 'Gaur', 'Lion-tailed macaque', 'Cochin forest cane turtle', 'Nilgiri langur'],
    feature: 'Four tribal communities hold formal roles in reserve management and tourism.',
  },
  {
    name: 'Bhadra Tiger Reserve',
    icon: '🏞️',
    state: 'Karnataka',
    landscape: 'ghats',
    category: 'recovery',
    notified: 1998,
    coreKm2: 492,
    bufferKm2: 572,
    tigers: 35,
    tigerNote: '',
    rivers: ['Bhadra', 'Somavahini', 'Thadabehalla'],
    tagline: 'India\'s model for voluntary village relocation',
    desc: 'Bhadra is cited internationally as the case where relocation was done properly. Between 2002 and 2006, sixteen villages moved out of the reserve voluntarily, with land-for-land compensation and infrastructure provided in advance at the resettlement site. Prey numbers and tiger numbers both rose afterwards, and — unusually — the relocated families reported improved livelihoods.',
    species: ['Tiger', 'Elephant', 'Gaur', 'Sloth bear', 'Malabar pied hornbill', 'King cobra'],
    feature: 'The relocation is studied as a template for consent-based resettlement.',
  },
  {
    name: 'Kali Tiger Reserve',
    icon: '🌧️',
    state: 'Karnataka',
    landscape: 'ghats',
    category: 'lowdensity',
    notified: 2007,
    coreKm2: 815,
    bufferKm2: 340,
    tigers: 15,
    tigerNote: 'Low density, but the habitat quality is high and connectivity is good.',
    rivers: ['Kali', 'Kaneri'],
    tagline: 'Evergreen forest in the northern Ghats',
    desc: 'Formerly Dandeli-Anshi, Kali is one of the wettest tiger reserves in the country and holds some of the best remaining evergreen and semi-evergreen forest in the northern Western Ghats. Its hornbill populations are exceptional, and the Kali river gorge cuts through the middle of it.',
    species: ['Tiger', 'Black panther', 'Great hornbill', 'Malabar pied hornbill', 'King cobra', 'Indian giant squirrel'],
    feature: 'Melanistic leopards are recorded here more often than almost anywhere else in India.',
  },
  {
    name: 'Sathyamangalam Tiger Reserve',
    icon: '🌄',
    state: 'Tamil Nadu',
    landscape: 'ghats',
    category: 'recovery',
    notified: 2013,
    coreKm2: 794,
    bufferKm2: 620,
    tigers: 85,
    tigerNote: 'One of the sharpest population increases recorded in India since notification.',
    rivers: ['Moyar', 'Bhavani'],
    tagline: 'Veerappan\'s forest, now a recovery story',
    desc: 'These forests were effectively outside state control for two decades while the sandalwood and ivory poacher Veerappan operated in them. Notified as a tiger reserve in 2013, Sathyamangalam has since recorded one of the steepest tiger increases in the country, and it forms the critical corridor linking the Western and Eastern Ghats populations.',
    species: ['Tiger', 'Elephant', 'Leopard', 'Indian gaur', 'Grizzled giant squirrel', 'Four-horned antelope'],
    feature: 'The Moyar gorge corridor is the main connection between the Nilgiri and Eastern Ghats tiger populations.',
  },
  {
    name: 'Mudumalai Tiger Reserve',
    icon: '🌿',
    state: 'Tamil Nadu',
    landscape: 'ghats',
    category: 'source',
    notified: 2007,
    coreKm2: 321,
    bufferKm2: 367,
    tigers: 110,
    tigerNote: 'Shared with Bandipur, Nagarhole and Wayanad — the same animals cross all four.',
    rivers: ['Moyar', 'Sigur'],
    tagline: 'The junction of three states',
    desc: 'Mudumalai meets Bandipur to the north, Wayanad to the west and the Sigur plateau to the east. It is small, but its position makes it one of the most important pieces of connectivity in the Nilgiri complex, and it carries a very high density of both tigers and elephants for its size.',
    species: ['Tiger', 'Elephant', 'Dhole', 'Gaur', 'Sloth bear', 'Indian rock python'],
    feature: 'The Sigur plateau corridor to the east is under sustained pressure from resorts and roads.',
  },
  {
    name: 'Buxa Tiger Reserve',
    icon: '🎍',
    state: 'West Bengal',
    landscape: 'northeast',
    category: 'lowdensity',
    notified: 1983,
    coreKm2: 391,
    bufferKm2: 367,
    tigers: 3,
    tigerNote: 'Photographic evidence of a tiger returned in 2021 after a long gap.',
    rivers: ['Raidak', 'Jayanti', 'Torsa'],
    tagline: 'A single camera-trap photograph in 2021',
    desc: 'Buxa sits in the Dooars against the Bhutan border and was for years the reserve most often described as tiger-free. A camera trap recorded a tiger in December 2021, the first confirmed image in over two decades. The reserve\'s value now lies mostly in connectivity — it links the Assam populations westward toward Nepal.',
    species: ['Tiger', 'Elephant', 'Clouded leopard', 'Gaur', 'Chinese pangolin', 'Regal python'],
    feature: 'The eighteenth-century Buxa Fort, later a detention camp for Indian independence activists, stands inside the reserve.',
  },
  {
    name: 'Namdapha Tiger Reserve',
    icon: '🐆',
    state: 'Arunachal Pradesh',
    landscape: 'northeast',
    category: 'lowdensity',
    notified: 1983,
    coreKm2: 1808,
    bufferKm2: 245,
    tigers: 11,
    tigerNote: 'Extremely difficult terrain makes estimation here unusually uncertain.',
    rivers: ['Noa-Dihing', 'Namdapha'],
    tagline: 'The only place with four big cat species',
    desc: 'Namdapha spans an altitudinal range from roughly 200 m to over 4,500 m, and is the only protected area in the world recorded to hold tiger, leopard, snow leopard and clouded leopard. Access is difficult, survey effort is limited, and much of what is known about the reserve comes from a small number of expeditions.',
    species: ['Tiger', 'Snow leopard', 'Clouded leopard', 'Hoolock gibbon', 'Red panda', 'Namdapha flying squirrel'],
    feature: 'The Namdapha flying squirrel is known from a single specimen collected in 1981 and has never been reliably seen since.',
  },
  {
    name: 'Nameri Tiger Reserve',
    icon: '🦆',
    state: 'Assam',
    landscape: 'northeast',
    category: 'lowdensity',
    notified: 2000,
    coreKm2: 200,
    bufferKm2: 144,
    tigers: 4,
    tigerNote: '',
    rivers: ['Jia Bhoroli', 'Bor Dikorai'],
    tagline: 'White-winged wood duck country',
    desc: 'A small reserve on the Assam–Arunachal border, contiguous with Pakke across the river. Nameri is best known for the white-winged wood duck, one of the rarest waterfowl in the world, and for being one of the few Indian reserves where walking with an armed guard is the normal way to see it.',
    species: ['Tiger', 'White-winged wood duck', 'Elephant', 'Capped langur', 'Black stork', 'Golden mahseer'],
    feature: 'Managed jointly with Pakke Tiger Reserve across the Jia Bhoroli.',
  },
  {
    name: 'Pakke Tiger Reserve',
    icon: '🦜',
    state: 'Arunachal Pradesh',
    landscape: 'northeast',
    category: 'lowdensity',
    notified: 2002,
    coreKm2: 683,
    bufferKm2: 515,
    tigers: 7,
    tigerNote: '',
    rivers: ['Pakke', 'Kameng'],
    tagline: 'Hornbill nests guarded by former hunters',
    desc: 'Pakke runs the Hornbill Nest Adoption Programme, in which Nyishi men who once hunted hornbills for their casques are paid to protect and monitor nest trees. Four hornbill species breed here. The reserve won the India Biodiversity Award in 2016, and the approach has been copied elsewhere in the North-East.',
    species: ['Tiger', 'Great hornbill', 'Wreathed hornbill', 'Clouded leopard', 'Asian elephant', 'Marbled cat'],
    feature: 'Community nest protection has measurably increased hornbill fledging success.',
  },
  {
    name: 'Achanakmar Tiger Reserve',
    icon: '🌲',
    state: 'Chhattisgarh',
    landscape: 'central',
    category: 'lowdensity',
    notified: 2009,
    coreKm2: 626,
    bufferKm2: 288,
    tigers: 12,
    tigerNote: '',
    rivers: ['Maniyari', 'Kharang'],
    tagline: 'The Maikal hills catchment',
    desc: 'Achanakmar sits in the Maikal range and is part of the Achanakmar-Amarkantak Biosphere Reserve. It is a key link in the corridor connecting Kanha to the Chhattisgarh reserves further east, and its sal forests form the catchment for several rivers feeding the Mahanadi system.',
    species: ['Tiger', 'Leopard', 'Indian bison', 'Wild dog', 'Sloth bear', 'Flying squirrel'],
    feature: 'The Baiga, a Particularly Vulnerable Tribal Group, live in and around the reserve.',
  },
  {
    name: 'Indravati Tiger Reserve',
    icon: '🐃',
    state: 'Chhattisgarh',
    landscape: 'central',
    category: 'lowdensity',
    notified: 1983,
    coreKm2: 1258,
    bufferKm2: 1541,
    tigers: 5,
    tigerNote: 'Access constraints have limited survey coverage for many years.',
    rivers: ['Indravati', 'Kotri'],
    tagline: 'The last home of the wild buffalo in central India',
    desc: 'Indravati in Bastar holds the last wild population of the Central Indian wild buffalo, down to a handful of animals. Long-running security constraints in the region have made systematic monitoring difficult, and much of the reserve has not been camera-trapped in the way reserves elsewhere routinely are.',
    species: ['Tiger', 'Wild buffalo', 'Barasingha', 'Gaur', 'Nilgai', 'Chital'],
    feature: 'Named for the Indravati river, which forms the reserve\'s northern boundary with Maharashtra.',
  },
  {
    name: 'Ranipur Tiger Reserve',
    icon: '🌱',
    state: 'Uttar Pradesh',
    landscape: 'central',
    category: 'lowdensity',
    notified: 2022,
    coreKm2: 230,
    bufferKm2: 300,
    tigers: 2,
    tigerNote: 'Newly notified; the reserve is being built up rather than counted.',
    rivers: ['Ohan', 'Bariyari'],
    tagline: 'Uttar Pradesh\'s fourth reserve, in Bundelkhand',
    desc: 'Notified in 2022 in Chitrakoot district, Ranipur is a dry deciduous Bundelkhand forest with a small resident tiger presence and connectivity toward Panna in Madhya Pradesh. The immediate management task is prey base recovery rather than tiger management.',
    species: ['Tiger', 'Leopard', 'Sloth bear', 'Chinkara', 'Sambar', 'Indian wolf'],
    feature: 'Represents the extension of tiger conservation into the Bundelkhand plateau.',
  },
  {
    name: 'Veerangana Durgavati Tiger Reserve',
    icon: '🆕',
    state: 'Madhya Pradesh',
    landscape: 'central',
    category: 'lowdensity',
    notified: 2023,
    coreKm2: 1414,
    bufferKm2: 924,
    tigers: 6,
    tigerNote: 'Established partly to take dispersing tigers from Panna.',
    rivers: ['Ken', 'Bearma'],
    tagline: 'Madhya Pradesh\'s seventh reserve',
    desc: 'Notified in 2023 across Damoh, Sagar and Narsinghpur districts, this reserve was created in part to receive tigers dispersing out of a now-crowded Panna, and to secure a corridor between the Panna and Nauradehi landscapes ahead of the Ken-Betwa link project.',
    species: ['Tiger', 'Leopard', 'Indian wolf', 'Chinkara', 'Sloth bear', 'Nilgai'],
    feature: 'Named for Rani Durgavati, the sixteenth-century Gondwana ruler.',
  },
  {
    name: 'Dholpur-Karauli Tiger Reserve',
    icon: '🏜️',
    state: 'Rajasthan',
    landscape: 'central',
    category: 'lowdensity',
    notified: 2023,
    coreKm2: 368,
    bufferKm2: 231,
    tigers: 3,
    tigerNote: 'A new reserve carved out of Chambal ravine country.',
    rivers: ['Chambal', 'Parvati'],
    tagline: 'Rajasthan\'s fifth reserve, in the Chambal ravines',
    desc: 'Notified in 2023, Dholpur-Karauli covers dry deciduous forest and the deeply dissected ravine country along the Chambal. It is intended to serve as a stepping stone between Ranthambore and the Kuno landscape, giving dispersing Ranthambore tigers somewhere to go.',
    species: ['Tiger', 'Leopard', 'Striped hyena', 'Indian wolf', 'Chinkara', 'Gharial'],
    feature: 'Adjoins the National Chambal Gharial Sanctuary along the river.',
  },
  {
    name: 'Guru Ghasidas-Tamor Pingla Tiger Reserve',
    icon: '🧭',
    state: 'Chhattisgarh',
    landscape: 'central',
    category: 'lowdensity',
    notified: 2024,
    coreKm2: 2049,
    bufferKm2: 1780,
    tigers: 4,
    tigerNote: 'Very early in its establishment; figures will change substantially.',
    rivers: ['Gopad', 'Banas'],
    tagline: 'One of the largest reserves by total area',
    desc: 'Notified in 2024 across the Sarguja region, this reserve joins Guru Ghasidas National Park with the Tamor Pingla sanctuary. Its significance is largely about connectivity: it links the Bandhavgarh and Palamau landscapes and is intended to allow tigers to re-establish across a belt where they had largely disappeared.',
    species: ['Tiger', 'Leopard', 'Indian wolf', 'Gaur', 'Sloth bear', 'Chousingha'],
    feature: 'Restores a link between the Madhya Pradesh and Jharkhand tiger landscapes.',
  },
];

/* ---------------------------------------------------- reserve vs park table */
const TR_COMPARISON = [
  {
    aspect: 'Legal basis',
    reserve: 'Notified under Section 38V of the Wild Life (Protection) Act, on NTCA recommendation',
    park: 'Notified under Section 35 of the same Act by the State Government',
    sanctuary: 'Notified under Section 26A / 18 by the State Government',
  },
  {
    aspect: 'Zoning',
    reserve: 'Mandatory two-zone structure: inviolate core and multiple-use buffer',
    park: 'Single zone; no statutory buffer requirement',
    sanctuary: 'Single zone; some regulated rights may continue',
  },
  {
    aspect: 'Governing plan',
    reserve: 'Tiger Conservation Plan, approved by the NTCA',
    park: 'Management plan approved by the Chief Wildlife Warden',
    sanctuary: 'Management plan approved by the Chief Wildlife Warden',
  },
  {
    aspect: 'Human presence',
    reserve: 'Core kept inviolate; relocation only with informed consent and a settled package',
    park: 'Rights settled at notification; grazing and collection generally barred',
    sanctuary: 'Certain rights may be allowed to continue if compatible',
  },
  {
    aspect: 'Central funding',
    reserve: 'Dedicated central assistance through Project Tiger',
    park: 'General central and state schemes only',
    sanctuary: 'General central and state schemes only',
  },
  {
    aspect: 'Can it contain the others?',
    reserve: 'Yes — a reserve usually contains one or more parks and sanctuaries',
    park: 'No',
    sanctuary: 'No',
  },
];

/* ------------------------------------------------------------------ timeline */
const TR_TIMELINE = [
  { year: '1972', title: 'Wild Life (Protection) Act', desc: 'The Act that made tiger hunting an offence and created the legal category of protected areas is passed by Parliament.' },
  { year: '1973', title: 'Project Tiger launched', desc: 'Nine reserves covering roughly 18,278 km² are notified, starting at Corbett on 1 April.' },
  { year: '1984', title: 'Reserves cross twenty', desc: 'Expansion into the Western Ghats and the North-East roughly doubles the network in a decade.' },
  { year: '1993', title: 'Global Tiger Forum', desc: 'India hosts the founding of the only intergovernmental body dedicated to tiger conservation.' },
  { year: '2005', title: 'Sariska loses every tiger', desc: 'Poaching wipes out the entire Sariska population. The Tiger Task Force is constituted in response.' },
  { year: '2006', title: 'NTCA created', desc: 'The WLPA is amended to create the National Tiger Conservation Authority and the Wildlife Crime Control Bureau, and to require core–buffer zoning.' },
  { year: '2006', title: 'First scientific estimation', desc: 'The pug-mark census is abandoned. The new double-sampling method puts the national figure at about 1,411 — far below earlier claims.' },
  { year: '2008', title: 'Sariska reintroduction', desc: 'Tigers are airlifted from Ranthambore to Sariska, the first tiger reintroduction attempted in India.' },
  { year: '2009', title: 'Panna reaches zero', desc: 'Panna is confirmed to have lost all its tigers. Reintroduction begins the following year.' },
  { year: '2010', title: 'TX2 goal set', desc: 'At the St Petersburg summit, thirteen range countries commit to doubling wild tiger numbers by 2022.' },
  { year: '2014', title: 'Estimate reaches 2,226', desc: 'The third cycle shows a clear national increase, though gains are concentrated in a minority of reserves.' },
  { year: '2018', title: 'Estimate reaches 2,967', desc: 'India meets the TX2 doubling target four years early. The survey enters the Guinness records as the largest camera-trap wildlife survey.' },
  { year: '2022', title: 'Network passes fifty reserves', desc: 'The programme approaches its half-century with more than fifty notified reserves.' },
  { year: '2023', title: 'Fifty years, and an estimate past 3,600', desc: 'Project Tiger completes fifty years on 1 April. The fifth estimation cycle reports a minimum of about 3,167 individually photographed tigers and an upper estimate above 3,900.' },
  { year: '2024', title: 'Network keeps growing', desc: 'Guru Ghasidas-Tamor Pingla is notified, taking the network past fifty-five reserves and 82,000 km².' },
];

/* -------------------------------------------------------- estimation method */
const TR_METHOD = [
  { step: '1', icon: '🥾', title: 'Ground survey', desc: 'Forest staff walk fixed transects across every beat, recording tiger signs, prey encounters and habitat condition. This covers the entire forested landscape, not just the reserves.' },
  { step: '2', icon: '📷', title: 'Camera trapping', desc: 'Paired cameras are placed in blocks so that both flanks of any animal passing between them are photographed. Every tiger carries a unique stripe pattern, so individuals can be told apart.' },
  { step: '3', icon: '🧮', title: 'Pattern matching', desc: 'Software compares stripe patterns across tens of thousands of images to build a catalogue of identified individuals. This gives the minimum number known to be alive.' },
  { step: '4', icon: '📐', title: 'Spatial capture-recapture', desc: 'Because not every tiger walks past a camera, the identified animals are used to model detection probability and estimate how many were missed. This is where the upper bound comes from.' },
  { step: '5', icon: '🌍', title: 'Extrapolation', desc: 'Densities from camera-trapped blocks are extrapolated to comparable habitat that was surveyed on foot but not photographed, using the relationship between sign encounter rate and density.' },
  { step: '6', icon: '📊', title: 'Reporting a range', desc: 'The published figure is a range with confidence limits, not a single number. Quoting only the midpoint — as most reporting does — throws away the uncertainty that the method was designed to express.' },
];

/* ------------------------------------------------------------------ threats */
const TR_THREATS = [
  { icon: '🎯', title: 'Poaching for trade', desc: 'Demand for skins and bones drives organised poaching networks that operate across state and national borders. A single well-organised gang emptied Sariska in under two years.', severity: 'Critical' },
  { icon: '🛣️', title: 'Linear infrastructure', desc: 'Highways, railway lines, canals and transmission corridors cut through habitat, killing animals directly and — more damagingly — severing the corridors that connect populations.', severity: 'Critical' },
  { icon: '🧩', title: 'Habitat fragmentation', desc: 'Most Indian tiger populations now sit in islands of habitat surrounded by farmland. Small isolated populations lose genetic diversity and are vulnerable to single events.', severity: 'Critical' },
  { icon: '🦌', title: 'Prey depletion', desc: 'Snaring and subsistence hunting of chital, sambar and wild pig removes the prey base. A forest can look intact on satellite imagery and still be empty of the animals a tiger needs.', severity: 'High' },
  { icon: '⚡', title: 'Human–tiger conflict', desc: 'Livestock depredation and, less often, attacks on people generate retaliatory killing — frequently by electrocution from illegally tapped power lines. Chandrapur and the Sundarbans carry the heaviest burden.', severity: 'High' },
  { icon: '🌿', title: 'Invasive species', desc: 'Lantana camara, Parthenium and Mikania smother the understorey and suppress the grasses that grazing prey depend on. Lantana now covers a substantial fraction of India\'s tiger habitat.', severity: 'High' },
  { icon: '⛏️', title: 'Mining and quarrying', desc: 'Coal, iron ore and limestone deposits lie under several central Indian tiger landscapes, and proposals to work them recur regardless of protected-area status.', severity: 'High' },
  { icon: '🐕', title: 'Disease from domestic animals', desc: 'Canine distemper and rabies spread from village dogs into wild carnivores. Distemper has already caused documented deaths in Indian tiger habitat.', severity: 'Moderate' },
  { icon: '🌡️', title: 'Climate and sea level', desc: 'The Sundarbans population is directly exposed to sea level rise and increasing cyclone intensity, with no higher ground to retreat to.', severity: 'Moderate' },
  { icon: '🏨', title: 'Tourism pressure', desc: 'Concentrated vehicle traffic in a handful of popular zones disturbs breeding females and alters movement patterns, even where overall visitor numbers are capped.', severity: 'Moderate' },
];

/* ------------------------------------------------------------------- wins */
const TR_WINS = [
  { icon: '🚁', title: 'Sariska reintroduction', org: '2008 onward', desc: 'Tigers were moved from Ranthambore into a reserve that had lost all of them. Early breeding failures were worked through, and the population is now self-sustaining.' },
  { icon: '💎', title: 'Panna recovery', org: '2009 onward', desc: 'From zero to a breeding population in little over a decade, and the clearest evidence available that a lost population can be rebuilt if the habitat is still there.' },
  { icon: '🏘️', title: 'Bhadra relocation', org: '2002–2006', desc: 'Sixteen villages moved out voluntarily with land-for-land compensation provided in advance. Both wildlife numbers and household incomes improved afterwards.' },
  { icon: '🤝', title: 'Periyar eco-development', org: '1996 onward', desc: 'Former poachers and smugglers were employed as guides and patrol staff, converting the people who knew the forest best from a threat into the protection system.' },
  { icon: '🛤️', title: 'Corridor notification', org: 'Ongoing', desc: 'Underpasses on NH-44 through Pench and Kanha, and mitigation structures elsewhere, have demonstrably restored animal movement across highways.' },
  { icon: '📱', title: 'M-STrIPES patrolling', org: '2010 onward', desc: 'GPS-logged patrol routes and sign records replaced paper registers, making patrol effort measurable and detecting gaps in coverage that were previously invisible.' },
  { icon: '🌏', title: 'Transboundary cooperation', org: 'Ongoing', desc: 'Coordination with Nepal at Valmiki–Chitwan and with Bhutan at Manas manages populations that have never respected the border.' },
  { icon: '🐅', title: 'TX2 met early', org: '2018', desc: 'India reached the international doubling target four years ahead of the 2022 deadline, and holds around seventy per cent of the world\'s wild tigers.' },
];

/* ------------------------------------------------------------------ gallery */
const TR_GALLERY = [
  { icon: '🐅', title: 'The Stripe Signature', caption: 'No two tigers share a stripe pattern — the basis of every modern population estimate.' },
  { icon: '📷', title: 'Camera Trap Grid', caption: 'Paired cameras photograph both flanks, so an animal can be identified from either side.' },
  { icon: '🌾', title: 'Terai Grassland', caption: 'Dudhwa and Corbett hold the tall grassland that most Terai wildlife depends on.' },
  { icon: '🌊', title: 'Mangrove Tigers', caption: 'In the Sundarbans, tigers swim between islands and drink brackish water.' },
  { icon: '🦌', title: 'Prey Base', caption: 'Chital, sambar and wild pig — the density of these decides the density of tigers.' },
  { icon: '🛤️', title: 'Corridor Underpass', caption: 'Mitigation structures on NH-44 let animals cross beneath the highway.' },
  { icon: '🏘️', title: 'Voluntary Relocation', caption: 'Bhadra\'s villages moved out with land-for-land compensation settled in advance.' },
  { icon: '🖤', title: 'Simlipal Melanism', caption: 'Pseudo-melanistic tigers occur as a breeding population only in Simlipal.' },
  { icon: '🚁', title: 'Translocation', caption: 'Tigers have been airlifted between reserves to rebuild lost populations.' },
  { icon: '🌲', title: 'Buffer Zone', caption: 'Multiple-use land around the core, where people and tigers share the same ground.' },
];

/* -------------------------------------------------------------------- facts */
const TR_FACTS = [
  'Project Tiger began on 1 April 1973 with nine reserves covering about 18,278 km². The network now exceeds fifty-five reserves and 82,000 km² — roughly 2.5% of India\'s land area.',
  'India holds around seventy per cent of the world\'s wild tigers, in a country with about eighteen per cent of the world\'s people.',
  'Every tiger\'s stripe pattern is unique, and the pattern on the left flank differs from the right. This is why camera traps are always deployed in pairs.',
  'The pug-mark census used until 2005 produced numbers that were far too high. Replacing it caused the national estimate to fall from over 3,500 to about 1,411 — the tigers had not vanished overnight; the earlier method had been wrong.',
  'Simlipal in Odisha is the only place in the world with a breeding population of pseudo-melanistic tigers, whose stripes have broadened until the coat appears almost black.',
  'Kaziranga has the highest tiger density of any Indian reserve, though it is far better known for holding two-thirds of the world\'s greater one-horned rhinos.',
  'Nagarjunsagar-Srisailam is the largest tiger reserve in India at close to 3,700 km², spanning Andhra Pradesh and Telangana.',
  'Namdapha in Arunachal Pradesh is the only protected area on earth recorded to hold tiger, leopard, snow leopard and clouded leopard.',
  'Sundarbans tigers regularly swim several kilometres between islands and are the only tiger population living in mangrove forest.',
  'The 2018 All India Tiger Estimation entered the Guinness Book of World Records as the largest camera-trap wildlife survey ever conducted, using close to 27,000 camera locations.',
  'Machhli of Ranthambore, who lived to about nineteen, is thought to be the most photographed wild tiger in history.',
  'A tiger reserve is not the same thing as a national park. The reserve is the larger unit, and usually contains one or more parks and sanctuaries inside it.',
];

/* --------------------------------------------------------------------- quiz */
const TR_QUIZ = [
  {
    q: 'In which year was Project Tiger launched, and with how many reserves?',
    options: ['1969, with 5 reserves', '1973, with 9 reserves', '1980, with 15 reserves', '1992, with 20 reserves'],
    answer: 1,
    explain: 'Project Tiger began on 1 April 1973 with nine reserves covering roughly 18,278 km². Corbett was the launch site.',
  },
  {
    q: 'What distinguishes a tiger reserve from a national park?',
    options: [
      'A tiger reserve is smaller and more strictly protected',
      'A tiger reserve has a mandatory core–buffer structure and a Tiger Conservation Plan under the NTCA',
      'They are two names for the same legal category',
      'A national park allows tourism while a tiger reserve does not',
    ],
    answer: 1,
    explain: 'The reserve is the larger unit. It requires an inviolate core plus a multiple-use buffer, is governed by a Tiger Conservation Plan approved by the NTCA, and usually contains national parks and sanctuaries within it.',
  },
  {
    q: 'Which reserve lost its entire tiger population, triggering the creation of the NTCA?',
    options: ['Panna', 'Sariska', 'Buxa', 'Palamau'],
    answer: 1,
    explain: 'Sariska was found to have lost every tiger by 2004–05. The Tiger Task Force followed, then the 2006 amendment to the Wild Life (Protection) Act that created the NTCA.',
  },
  {
    q: 'Which is the only place in the world with a breeding population of pseudo-melanistic tigers?',
    options: ['Sundarbans', 'Simlipal', 'Namdapha', 'Manas'],
    answer: 1,
    explain: 'Simlipal in Odisha. The broadened, merged stripes are a genetic trait whose concentration reflects a small and isolated population.',
  },
  {
    q: 'Why are camera traps always placed in pairs?',
    options: [
      'In case one camera fails',
      'To photograph both flanks, since the stripe patterns on the two sides differ',
      'To measure how fast the animal is moving',
      'To cover a wider area of forest',
    ],
    answer: 1,
    explain: 'A tiger\'s left and right flank patterns are different. Photographing only one side makes it impossible to match an individual reliably against the catalogue.',
  },
  {
    q: 'Which is the largest tiger reserve in India by area?',
    options: ['Sundarbans', 'Nagarjunsagar-Srisailam', 'Namdapha', 'Melghat'],
    answer: 1,
    explain: 'Nagarjunsagar-Srisailam, spanning Andhra Pradesh and Telangana, covers close to 3,700 km² including its buffer.',
  },
  {
    q: 'Why did India\'s national tiger estimate appear to fall sharply in 2006?',
    options: [
      'A poaching wave killed roughly half the population',
      'The unreliable pug-mark census was replaced with camera-trap-based sampling',
      'Several reserves were removed from the network',
      'Tigers moved across the border into Nepal',
    ],
    answer: 1,
    explain: 'The drop was a change of method, not of population. The pug-mark census had been systematically over-counting; the new approach put the figure near 1,411.',
  },
  {
    q: 'Which reserve is internationally cited as a model for voluntary village relocation?',
    options: ['Bhadra', 'Ranthambore', 'Corbett', 'Kaziranga'],
    answer: 0,
    explain: 'Sixteen villages moved out of Bhadra between 2002 and 2006 with land-for-land compensation and infrastructure provided before the move. Both wildlife and household incomes improved.',
  },
  {
    q: 'Which reserve holds the only tiger population living in mangrove forest?',
    options: ['Bhitarkanika', 'Sundarbans', 'Pichavaram', 'Coringa'],
    answer: 1,
    explain: 'The Sundarbans, shared between India and Bangladesh, is the only mangrove tiger habitat in the world.',
  },
  {
    q: 'Which protected area is the only one recorded to hold four big cat species?',
    options: ['Manas', 'Namdapha', 'Buxa', 'Pakke'],
    answer: 1,
    explain: 'Namdapha in Arunachal Pradesh, spanning roughly 200 m to over 4,500 m, has records of tiger, leopard, snow leopard and clouded leopard.',
  },
  {
    q: 'What does the buffer zone of a tiger reserve mean?',
    options: [
      'An area where no human activity of any kind is permitted',
      'A multiple-use area around the core where people and wildlife share the landscape',
      'A strip of land reserved for future expansion of the core',
      'The area open to tourist vehicles',
    ],
    answer: 1,
    explain: 'The buffer is deliberately multiple-use. It absorbs dispersing animals and supports local livelihoods, while the core is kept inviolate.',
  },
  {
    q: 'When did India meet the international TX2 goal of doubling wild tiger numbers?',
    options: ['2014', '2018, four years early', '2022, exactly on time', 'It has not yet been met'],
    answer: 1,
    explain: 'The 2018 estimate of 2,967 met the TX2 target set at St Petersburg in 2010, four years ahead of the 2022 deadline.',
  },
];
