/* ==========================================================================
   INDIAN MARITIME HERITAGE & MAJOR PORTS — DATASET
   Ancient dates are approximate and often debated; modern port figures are
   indicative. Every port carries an `era` and `coast` used by the filters.
   ========================================================================== */

const MH_ERAS = [
  { key: 'ancient', name: 'Ancient & Medieval', icon: '🏺', desc: 'Ports of the Harappans, the Sangam kingdoms, the Cholas and the sultanates — most of them silted up, buried or reduced to a village.' },
  { key: 'modern', name: 'Modern Major Ports', icon: '🚢', desc: 'The thirteen major ports administered under central law, which together handle the bulk of India\'s seaborne trade.' },
];

const MH_COASTS = [
  { key: 'west', name: 'West Coast', icon: '🌅' },
  { key: 'east', name: 'East Coast', icon: '🌄' },
  { key: 'islands', name: 'Islands', icon: '🏝️' },
];

const MH_PORTS = [
  /* ------------------------- ancient & medieval -------------------------- */
  {
    name: 'Lothal',
    icon: '🏺',
    era: 'ancient',
    coast: 'west',
    state: 'Gujarat',
    period: 'c. 2400 BCE onward',
    tagline: 'A Harappan dockyard on the Gulf of Khambhat',
    desc: 'Excavated in the 1950s and 60s, Lothal revealed a large baked-brick basin connected to a river channel, widely interpreted as a dockyard — which would make it one of the earliest known engineered harbour works anywhere. The site also yielded a bead factory and Persian Gulf seals, pointing to long-range trade.',
    traded: ['Carnelian and agate beads', 'Cotton textiles', 'Copper', 'Shell ornaments', 'Ivory'],
    note: 'The dockyard interpretation is the mainstream reading but has been contested; some scholars have argued the basin was an irrigation tank. The trade evidence, however, is not in doubt.',
  },
  {
    name: 'Muziris',
    icon: '🌶️',
    era: 'ancient',
    coast: 'west',
    state: 'Kerala',
    period: 'c. 1st century BCE – 14th century CE',
    tagline: 'Where Roman gold bought Malabar pepper',
    desc: 'The most important western port of the ancient Tamil world, Muziris appears in Roman sources and in Sangam poetry as the place where Yavana ships arrived with gold and left with pepper. Excavations at Pattanam near Kodungallur have produced Mediterranean amphorae and Roman-period material consistent with the location.',
    traded: ['Black pepper', 'Malabathrum', 'Pearls', 'Ivory', 'Roman gold coin (inbound)'],
    note: 'The exact location of Muziris has been debated for over a century; Pattanam is the leading candidate but the identification is still discussed.',
  },
  {
    name: 'Arikamedu',
    icon: '🏛️',
    era: 'ancient',
    coast: 'east',
    state: 'Puducherry',
    period: 'c. 2nd century BCE – 2nd century CE',
    tagline: 'A Roman trading station on the Coromandel',
    desc: 'Excavations here produced Arretine ware, amphora fragments and Roman glass alongside local rouletted pottery — the clearest physical evidence anywhere in India of a sustained Mediterranean trading presence on the east coast.',
    traded: ['Muslin and fine textiles', 'Beads and semi-precious stones', 'Spices', 'Roman wine and glassware (inbound)'],
    note: 'The finds established the chronology used to date rouletted ware across South and Southeast Asia.',
  },
  {
    name: 'Tamralipta',
    icon: '⛵',
    era: 'ancient',
    coast: 'east',
    state: 'West Bengal',
    period: 'c. 3rd century BCE – 8th century CE',
    tagline: 'The eastern gateway to Southeast Asia',
    desc: 'Modern Tamluk, on the Rupnarayan, was the principal eastern seaport of the Mauryan and Gupta periods. Buddhist pilgrims including Faxian embarked from here for Sri Lanka and Southeast Asia, and it was the terminus of the road from Pataliputra.',
    traded: ['Silk and cotton textiles', 'Pearls', 'Copper', 'Buddhist manuscripts and images'],
    note: 'Silting of the Rupnarayan gradually ended its usefulness as a port, and the coastline has since moved considerably.',
  },
  {
    name: 'Bharuch (Barygaza)',
    icon: '🏘️',
    era: 'ancient',
    coast: 'west',
    state: 'Gujarat',
    period: 'c. 3rd century BCE – 17th century CE',
    tagline: 'One of India\'s longest continuously used ports',
    desc: 'Bharuch on the Narmada estuary appears in the Periplus of the Erythraean Sea as Barygaza, complete with sailing directions warning of dangerous tidal bores. It stayed commercially active through the Kshatrapa, Gujarat Sultanate and Mughal periods.',
    traded: ['Cotton textiles', 'Indigo', 'Grain', 'Onyx and agate', 'Horses (inbound)'],
    note: 'The Periplus passage on Barygaza is one of the most detailed ancient descriptions of any Indian harbour.',
  },
  {
    name: 'Sopara',
    icon: '📜',
    era: 'ancient',
    coast: 'west',
    state: 'Maharashtra',
    period: 'c. 3rd century BCE – 9th century CE',
    tagline: 'A Konkan port with an Ashokan edict',
    desc: 'Shurparaka, near modern Nala Sopara north of Mumbai, was the leading port of the northern Konkan. A fragment of an Ashokan rock edict found here confirms it was a place of consequence in the Mauryan period.',
    traded: ['Cotton', 'Timber', 'Spices', 'Gold and glass (inbound)'],
    note: 'It declined as the coastline shifted and as trade moved south to the Thane creek and later to Mumbai.',
  },
  {
    name: 'Kaveripattinam (Puhar)',
    icon: '🌊',
    era: 'ancient',
    coast: 'east',
    state: 'Tamil Nadu',
    period: 'c. 3rd century BCE – 5th century CE',
    tagline: 'The Chola capital-port of Tamil epic',
    desc: 'At the mouth of the Kaveri, Puhar was the great port of the early Cholas and the setting for much of the Tamil epic Silappadikaram, which describes its warehouses, its customs officers and its foreign quarter in unusual detail.',
    traded: ['Pepper and spices', 'Pearls', 'Fine cotton', 'Gemstones'],
    note: 'Tamil tradition holds that much of the city was lost to the sea, and offshore surveys have recovered submerged structural remains.',
  },
  {
    name: 'Mahabalipuram',
    icon: '🛕',
    era: 'ancient',
    coast: 'east',
    state: 'Tamil Nadu',
    period: 'c. 7th – 9th century CE',
    tagline: 'The Pallava port beneath the Shore Temple',
    desc: 'Mamallapuram served the Pallava capital at Kanchipuram and was the departure point for the maritime contact that carried Pallava-influenced temple architecture to Southeast Asia. Its rock-cut monuments are a UNESCO World Heritage Site.',
    traded: ['Textiles', 'Spices', 'Sculpture and craft goods', 'Religious and architectural ideas'],
    note: 'The 2004 tsunami briefly exposed submerged structures offshore, prompting renewed underwater survey.',
  },
  {
    name: 'Nagapattinam',
    icon: '🪷',
    era: 'ancient',
    coast: 'east',
    state: 'Tamil Nadu',
    period: 'c. 9th – 16th century CE',
    tagline: 'The Chola link to Srivijaya',
    desc: 'Nagapattinam was the main outlet for Chola maritime activity in Southeast Asia. The Srivijayan ruler endowed a Buddhist vihara here — the Chudamani Vihara — with Chola consent, an unusually direct record of diplomatic and commercial ties across the Bay of Bengal.',
    traded: ['Textiles', 'Spices', 'Bronze images', 'Rice'],
    note: 'The Chola naval expeditions to Srivijaya in the 11th century are among the few recorded instances of a large Indian overseas military campaign.',
  },
  {
    name: 'Beypore',
    icon: '🛶',
    era: 'ancient',
    coast: 'west',
    state: 'Kerala',
    period: 'c. 1st century CE – Present',
    tagline: 'Cradle of Uru shipbuilding & Khalasi heritage',
    desc: 'Located at the mouth of the Chaliyar River near Kozhikode, Beypore is renowned worldwide for its 2,000-year-old traditional wooden Uru shipbuilding industry. Built using Nilambur teak and launched by legendary Khalasis using ancient winch mechanics, Beypore traded extensively with Arabia, Mesopotamia, and Rome.',
    traded: ['Nilambur Teak', 'Wooden Uru dhows', 'Coir cordage', 'Malabar Spices', 'Handloom textiles'],
    note: 'Beypore Urus are hand-crafted without written blueprints using traditional measurement rods (kolu), drawing commissioning orders from Gulf royalty even today.',
  },
  {
    name: 'Kozhikode (Calicut)',
    icon: '⚓',
    era: 'ancient',
    coast: 'west',
    state: 'Kerala',
    period: 'c. 13th – 18th century CE',
    tagline: 'Where Vasco da Gama landed in 1498',
    desc: 'Under the Zamorins, Calicut was the dominant pepper port of the Malabar coast, visited by Ibn Battuta and Zheng He before da Gama\'s arrival opened the direct Cape route from Europe and changed the terms of the trade entirely.',
    traded: ['Black pepper', 'Ginger', 'Cardamom', 'Teak', 'Coir'],
    note: 'Calicut gave its name to calico cloth, which entered English through the Portuguese trade.',
  },
  {
    name: 'Surat',
    icon: '🕌',
    era: 'ancient',
    coast: 'west',
    state: 'Gujarat',
    period: 'c. 16th – 18th century CE',
    tagline: 'The Mughal empire\'s principal port',
    desc: 'Surat was the busiest Indian port of the 17th century — the embarkation point for the Haj, the base of the largest Indian-owned merchant fleets, and the site of the first English factory in 1613. Its decline followed the rise of Bombay.',
    traded: ['Cotton textiles', 'Indigo', 'Saltpetre', 'Silk', 'Silver bullion (inbound)'],
    note: 'Contemporary accounts describe Surat shipowners operating vessels far larger than most European merchantmen of the period.',
  },
  {
    name: 'Machilipatnam',
    icon: '🎨',
    era: 'ancient',
    coast: 'east',
    state: 'Andhra Pradesh',
    period: 'c. 16th – 18th century CE',
    tagline: 'Golconda\'s outlet and a kalamkari centre',
    desc: 'Masulipatnam was the chief port of the Golconda sultanate and the site of early Dutch and English factories. It exported the painted and block-printed cotton — kalamkari — that became one of India\'s most sought-after commodities.',
    traded: ['Kalamkari painted cotton', 'Chintz', 'Diamonds from Golconda', 'Indigo'],
    note: 'Repeated cyclones and harbour silting ended its position as a leading port by the nineteenth century.',
  },

  /* ---------------------------- modern ports ----------------------------- */
  {
    name: 'Deendayal Port (Kandla)',
    icon: '🛢️',
    era: 'modern',
    coast: 'west',
    state: 'Gujarat',
    period: 'Established 1955',
    tagline: 'Built to replace Karachi after Partition',
    desc: 'Developed in the Gulf of Kutch specifically to give newly independent India a major west-coast port after Karachi went to Pakistan. It handles very large volumes of petroleum, chemicals, fertiliser and grain.',
    traded: ['Crude oil and POL products', 'Chemicals', 'Fertiliser', 'Foodgrain', 'Salt'],
    note: 'Renamed Deendayal Port in 2017. Consistently among India\'s highest-throughput ports by cargo tonnage.',
  },
  {
    name: 'Mumbai Port',
    icon: '🏙️',
    era: 'modern',
    coast: 'west',
    state: 'Maharashtra',
    period: 'Modern port from the 1870s',
    tagline: 'The natural harbour that made the city',
    desc: 'Mumbai\'s deep, sheltered harbour was the reason the settlement grew into India\'s commercial capital. It has progressively shifted container traffic to JNPA across the harbour and now handles more general and liquid cargo.',
    traded: ['Petroleum products', 'General cargo', 'Steel', 'Cruise passengers'],
    note: 'The port\'s eastern waterfront is being partly redeveloped for public and commercial use.',
  },
  {
    name: 'Jawaharlal Nehru Port (JNPA)',
    icon: '📦',
    era: 'modern',
    coast: 'west',
    state: 'Maharashtra',
    period: 'Commissioned 1989',
    tagline: "India's largest container port",
    desc: 'Built at Nhava Sheva to relieve Mumbai, JNPA handles the largest share of India\'s container traffic and is the country\'s main gateway for containerised exports and imports.',
    traded: ['Containerised general cargo', 'Textiles and garments', 'Chemicals', 'Machinery'],
    note: 'Connected to the Western Dedicated Freight Corridor, which links it directly to the northern hinterland.',
  },
  {
    name: 'Mormugao Port',
    icon: '⛏️',
    era: 'modern',
    coast: 'west',
    state: 'Goa',
    period: 'Developed from 1885',
    tagline: 'Built around the iron ore trade',
    desc: 'At the mouth of the Zuari, Mormugao developed as the export point for Goan iron ore. When ore mining was curtailed, the port diversified into coal, containers and cruise traffic.',
    traded: ['Iron ore (historically)', 'Coal', 'Containers', 'Cruise passengers'],
    note: 'Its fortunes have tracked mining policy more closely than any other Indian major port.',
  },
  {
    name: 'New Mangalore Port',
    icon: '🌴',
    era: 'modern',
    coast: 'west',
    state: 'Karnataka',
    period: 'Commissioned 1974',
    tagline: 'Karnataka\'s only major port',
    desc: 'An all-weather port on the Karnataka coast handling petroleum, LPG, fertiliser, iron ore pellets and containers, and serving the refinery and industrial cluster around Mangaluru.',
    traded: ['POL products and LPG', 'Fertiliser', 'Iron ore pellets', 'Cashew and coffee'],
    note: 'Also serves as an entry point for the Western Ghats hinterland of Karnataka.',
  },
  {
    name: 'Cochin Port',
    icon: '🚤',
    era: 'modern',
    coast: 'west',
    state: 'Kerala',
    period: 'Modern port from 1928',
    tagline: 'Engineered out of a backwater',
    desc: 'The modern port was created by dredging the Cochin backwaters and using the spoil to build Willingdon Island — a substantial feat of harbour engineering. It now includes an international container transhipment terminal and a major shipyard.',
    traded: ['Containers and transhipment cargo', 'Petroleum products', 'Spices', 'Cruise passengers'],
    note: 'Cochin Shipyard, adjacent to the port, built India\'s first indigenous aircraft carrier.',
  },
  {
    name: 'Syama Prasad Mookerjee Port (Kolkata)',
    icon: '🌉',
    era: 'modern',
    coast: 'east',
    state: 'West Bengal',
    period: 'Established 1870',
    tagline: 'India\'s only major riverine port',
    desc: 'Situated on the Hooghly nearly 200 km from the sea, Kolkata is India\'s oldest operating major port and its only riverine one. Continuous dredging is required to keep the channel navigable, and the deep-draught traffic is handled at Haldia downstream.',
    traded: ['Containers', 'Coal', 'Foodgrain', 'Project cargo', 'Tea'],
    note: 'Serves eastern India, Nepal, Bhutan and the northeast, giving it a hinterland far larger than its tonnage suggests.',
  },
  {
    name: 'Paradip Port',
    icon: '⚙️',
    era: 'modern',
    coast: 'east',
    state: 'Odisha',
    period: 'Commissioned 1966',
    tagline: 'The bulk-cargo giant of the east coast',
    desc: 'An artificial deep-water harbour on the Odisha coast, Paradip handles enormous volumes of coal, iron ore and crude oil, serving the mineral belt of eastern India and a large refinery.',
    traded: ['Thermal and coking coal', 'Iron ore', 'Crude oil', 'Fertiliser'],
    note: 'Regularly among the top Indian ports by total cargo handled.',
  },
  {
    name: 'Visakhapatnam Port',
    icon: '🛳️',
    era: 'modern',
    coast: 'east',
    state: 'Andhra Pradesh',
    period: 'Opened 1933',
    tagline: 'A natural harbour behind Dolphin\'s Nose',
    desc: 'Sheltered by the Dolphin\'s Nose headland, Visakhapatnam is one of the deepest natural harbours on the east coast. It serves a steel plant, a refinery, a shipyard and a major naval base.',
    traded: ['Iron ore and pellets', 'Coal', 'Crude oil', 'Alumina', 'Containers'],
    note: 'Headquarters of the Indian Navy\'s Eastern Naval Command.',
  },
  {
    name: 'Kamarajar Port (Ennore)',
    icon: '🔌',
    era: 'modern',
    coast: 'east',
    state: 'Tamil Nadu',
    period: 'Commissioned 2001',
    tagline: 'India\'s first corporatised major port',
    desc: 'Built north of Chennai principally to handle thermal coal for power generation, Ennore was the first Indian major port set up as a company rather than a trust, and has since added automobile and LNG capacity.',
    traded: ['Thermal coal', 'Automobiles', 'LNG', 'Petroleum products'],
    note: 'Its corporate structure anticipated the governance model later extended to other ports.',
  },
  {
    name: 'Chennai Port',
    icon: '🚗',
    era: 'modern',
    coast: 'east',
    state: 'Tamil Nadu',
    period: 'Artificial harbour from 1881',
    tagline: 'An artificial harbour on an open coast',
    desc: 'Chennai has no natural shelter, so the harbour was built outright with breakwaters on a surf-beaten coast. It is now a leading automobile export gateway alongside its container and general cargo business.',
    traded: ['Automobiles', 'Containers', 'Petroleum products', 'Fertiliser'],
    note: 'Before the breakwaters, cargo was carried through the surf in masula boats — flexible stitched craft built for exactly that.',
  },
  {
    name: 'V.O. Chidambaranar Port (Tuticorin)',
    icon: '🧂',
    era: 'modern',
    coast: 'east',
    state: 'Tamil Nadu',
    period: 'Major port since 1974',
    tagline: 'On an ancient pearl coast',
    desc: 'Thoothukudi sits on a stretch of coast associated with the Pandya pearl fishery in antiquity. The modern port is a container and bulk facility serving southern Tamil Nadu\'s industrial belt.',
    traded: ['Containers', 'Coal', 'Salt', 'Sugar', 'Granite'],
    note: 'Named after V.O. Chidambaram Pillai, who launched an Indian-owned shipping company in 1906 to challenge the British monopoly on the Tuticorin–Colombo route.',
  },
  {
    name: 'Port Blair',
    icon: '🏝️',
    era: 'modern',
    coast: 'islands',
    state: 'Andaman & Nicobar Islands',
    period: 'Declared a major port in 2010',
    tagline: 'India\'s island major port',
    desc: 'Port Blair is the lifeline of the Andaman and Nicobar Islands, handling nearly all supplies to the territory as well as passenger traffic between the islands and the mainland.',
    traded: ['General supplies and provisions', 'Petroleum products', 'Timber', 'Passenger traffic'],
    note: 'India\'s smallest major port by tonnage but essential to the territory\'s functioning.',
  },
];

/* Timeline ----------------------------------------------------------------- */
const MH_TIMELINE = [
  { year: 'c. 2400 BCE', title: 'Lothal', desc: 'A brick basin connected to a river channel is built at Lothal in Gujarat — widely read as a dockyard, and among the earliest known engineered harbour works.' },
  { year: 'c. 300 BCE', title: 'Mauryan shipping administration', desc: 'The Arthashastra describes a superintendent of shipping with responsibility for ports, ferries and maritime disputes — evidence of formal state involvement in seaborne trade.' },
  { year: 'c. 1st century CE', title: 'The Periplus and the monsoon', desc: 'The Periplus of the Erythraean Sea sets out sailing directions to Indian ports. Systematic use of the monsoon wind cycle turns the Arabian Sea crossing into a predictable annual run.' },
  { year: 'c. 2nd century CE', title: 'Roman trade at its height', desc: 'Amphorae, Arretine ware and Roman coin hoards across peninsular India mark a sustained trade in pepper, textiles and gems paid for largely in gold.' },
  { year: 'c. 1025 CE', title: 'The Chola expeditions', desc: 'Rajendra Chola despatches naval expeditions across the Bay of Bengal against Srivijaya — one of the very few large Indian overseas military campaigns on record.' },
  { year: '1498', title: 'Da Gama at Calicut', desc: 'The opening of the direct Cape route brings European powers into an Indian Ocean trade network they had previously reached only through intermediaries.' },
  { year: '17th century', title: 'Surat at its peak', desc: 'Surat becomes the busiest port in India — Haj embarkation point, home of large Indian merchant fleets, and site of the first English factory.' },
  { year: '1870 – 1930s', title: 'Colonial port building', desc: 'Kolkata, Chennai, Mumbai, Mormugao and Visakhapatnam are engineered into modern harbours, laid out to move raw material outward by rail.' },
  { year: '1906', title: 'Swadeshi shipping', desc: 'V.O. Chidambaram Pillai founds the Swadeshi Steam Navigation Company on the Tuticorin–Colombo route, directly challenging the British shipping monopoly.' },
  { year: '1955', title: 'Kandla', desc: 'A new major port is developed in the Gulf of Kutch to replace the loss of Karachi at Partition.' },
  { year: '1989', title: 'Nhava Sheva', desc: 'JNPA opens across the harbour from Mumbai and goes on to become India\'s largest container port.' },
  { year: '2015 onward', title: 'Sagarmala', desc: 'The Sagarmala programme reframes ports as the anchor of a port-led development strategy, followed by Maritime India Vision 2030 and the 2021 Major Port Authorities Act.' },
];

/* Traditional shipbuilding -------------------------------------------------- */
const MH_SHIPBUILDING = [
  { name: 'Beypore Uru', icon: '🛶', place: 'Kozhikode, Kerala', desc: 'Large wooden dhows built at Beypore by the Khalasi community, traditionally without formal drawings — the master shipwright carries the design. Beypore urus have been exported to Gulf owners for generations.' },
  { name: 'Stitched-plank craft', icon: '🪡', place: 'Kerala & Lakshadweep', desc: 'Hull planks sewn together with coir rope rather than nailed. The resulting hull flexes instead of splitting, which is exactly what is wanted in surf and on coral.' },
  { name: 'Kutch Dhow', icon: '⛵', place: 'Mandvi, Gujarat', desc: 'Mandvi has built wooden dhows on the open beach for centuries, and still does — vessels are laid down in the sand and launched directly into the Gulf of Kutch.' },
  { name: 'Catamaran', icon: '🪢', place: 'Coromandel coast', desc: 'From Tamil kattumaram, "tied wood" — logs lashed together into a raft that can be driven through surf where a rigid hull would be destroyed. The word entered English from Tamil.' },
  { name: 'Masula Boat', icon: '🌊', place: 'Andhra & Tamil Nadu coast', desc: 'A flexible surf boat with sewn planks and no rigid frame, used to move cargo and passengers between ship and beach before harbours were built at Chennai and Machilipatnam.' },
  { name: 'Kettuvallam', icon: '🏡', place: 'Kerala backwaters', desc: 'Rice barges built with coir-stitched jackwood planking and no nails, once the main freight carrier of the backwaters and now largely converted to houseboats.' },
];

/* Navigation and trade ------------------------------------------------------ */
const MH_NAVIGATION = [
  { title: 'The monsoon clock', icon: '🌬️', desc: 'The southwest monsoon carries ships towards India from roughly June, the northeast monsoon carries them back from around November. Understanding this turned an unpredictable crossing into a scheduled annual run — and set the rhythm of the entire Indian Ocean economy.' },
  { title: 'Coastal pilotage', icon: '🗺️', desc: 'Most voyages hugged the coast, navigating by landmark, depth soundings and local pilots. Open-ocean crossings were the exception, not the rule.' },
  { title: 'Star navigation', icon: '⭐', desc: 'Latitude was judged by the altitude of known stars above the horizon, measured with simple instruments and long-memorised tables of star positions for each destination.' },
  { title: 'The Periplus', icon: '📜', desc: 'A first-century Greek merchant\'s handbook listing Indian ports, what each bought and sold, and the hazards of approaching them — the closest thing we have to a commercial directory of the ancient Indian coast.' },
  { title: 'Exports', icon: '📤', desc: 'Pepper and spices, cotton textiles from muslin to chintz, indigo, pearls, gemstones, ivory, teak and sandalwood — India was a net exporter of manufactures for most of recorded history.' },
  { title: 'Imports', icon: '📥', desc: 'Gold and silver bullion, Roman wine, glassware, horses from Arabia and Central Asia, coral and dates. The persistent inflow of bullion in exchange for goods is a recurring theme in ancient and early modern accounts alike.' },
];

/* Institutions today -------------------------------------------------------- */
const MH_INSTITUTIONS = [
  { title: 'Indian Navy', icon: '⚓', org: 'Ministry of Defence', desc: 'Maintains the country\'s blue-water capability across three commands, including indigenous carrier and submarine construction programmes.' },
  { title: 'Indian Coast Guard', icon: '🚁', org: 'Established 1978', desc: 'Responsible for maritime search and rescue, pollution response, fisheries protection and coastal security in India\'s exclusive economic zone.' },
  { title: 'Sagarmala Programme', icon: '🔗', org: 'Ministry of Ports, Shipping & Waterways', desc: 'A port-led development programme covering port modernisation, hinterland connectivity, coastal shipping and community development in coastal districts.' },
  { title: 'Maritime India Vision 2030', icon: '🎯', org: 'Government of India', desc: 'A strategy document setting targets for port capacity, transhipment, shipbuilding and inland waterways, extended by a longer-horizon Amrit Kaal vision.' },
  { title: 'Directorate General of Shipping', icon: '📋', org: 'Regulator', desc: 'Regulates Indian merchant shipping, seafarer certification and maritime safety, and represents India at the International Maritime Organization.' },
  { title: 'Major Port Authorities Act, 2021', icon: '⚖️', org: 'Legislation', desc: 'Replaced the Major Port Trusts Act of 1963, converting port trusts into authorities with greater autonomy over tariffs and land use.' },
  { title: 'Cochin Shipyard', icon: '🔨', org: 'Public sector shipbuilder', desc: 'India\'s largest shipbuilding and repair yard, which built the country\'s first indigenously designed and constructed aircraft carrier.' },
  { title: 'National Maritime Heritage Complex', icon: '🏛️', org: 'Lothal, Gujarat', desc: 'A museum and research complex being developed at Lothal to present India\'s maritime history from the Harappan period to the present.' },
];

/* Facts --------------------------------------------------------------------- */
const MH_FACTS = [
  'India has a coastline of roughly 7,500 km and nine coastal states, plus two island territories.',
  'The English word "catamaran" comes from the Tamil kattumaram, meaning "tied wood".',
  'Calico cloth takes its name from Calicut (Kozhikode), the Malabar port where Europeans first bought it in quantity.',
  'Lothal in Gujarat has a baked-brick basin dated to around 2400 BCE that is widely interpreted as a dockyard.',
  'The Periplus of the Erythraean Sea, written in the first century CE, gives sailing directions and trade lists for Indian ports.',
  'Chola naval expeditions crossed the Bay of Bengal to Srivijaya in the 11th century — a rare instance of large-scale Indian overseas military action.',
  'Kolkata is India\'s only major riverine port, sitting nearly 200 km up the Hooghly from the sea.',
  'Chennai harbour is entirely artificial — before its breakwaters, cargo came ashore through the surf in flexible stitched masula boats.',
  'Kandla was developed after Partition specifically to replace the loss of Karachi as a west-coast port.',
  'Wooden dhows are still built by hand on the open beach at Mandvi in Gujarat and at Beypore in Kerala.',
];

/* Quiz ---------------------------------------------------------------------- */
const MH_QUIZ = [
  { q: 'Which Harappan site has a structure widely interpreted as a dockyard?', options: ['Dholavira', 'Lothal', 'Kalibangan', 'Rakhigarhi'], answer: 1, explain: 'Lothal in Gujarat has a large baked-brick basin connected to a river channel, generally read as a dockyard.' },
  { q: 'The English word "catamaran" comes from which language?', options: ['Malayalam', 'Tamil', 'Portuguese', 'Arabic'], answer: 1, explain: 'From Tamil kattumaram, "tied wood" — logs lashed together to cross surf.' },
  { q: 'Vasco da Gama landed in 1498 at which port?', options: ['Cochin', 'Calicut', 'Goa', 'Surat'], answer: 1, explain: 'He landed near Calicut (Kozhikode), then the dominant pepper port of the Malabar coast.' },
  { q: 'Which is India\'s largest container port?', options: ['Chennai Port', 'Mumbai Port', 'Jawaharlal Nehru Port (JNPA)', 'Paradip Port'], answer: 2, explain: 'JNPA at Nhava Sheva handles the largest share of India\'s container traffic.' },
  { q: 'Which major port is riverine rather than coastal?', options: ['Kolkata', 'Visakhapatnam', 'Cochin', 'Mormugao'], answer: 0, explain: 'Kolkata sits on the Hooghly, nearly 200 km inland, and needs continuous dredging.' },
  { q: 'Kandla (Deendayal) Port was developed mainly to…', options: ['Export iron ore', 'Replace Karachi after Partition', 'Serve the Andaman Islands', 'Handle cruise traffic'], answer: 1, explain: 'It was built to give independent India a major west-coast port after Karachi went to Pakistan.' },
  { q: 'The Periplus of the Erythraean Sea is best described as…', options: ['A Chola inscription', 'A Greek merchant\'s guide to Indian Ocean ports', 'A Mughal revenue record', 'A Portuguese naval log'], answer: 1, explain: 'It is a first-century CE Greek handbook listing ports, goods and sailing hazards.' },
  { q: 'Which ancient port was the eastern gateway to Southeast Asia in the Mauryan and Gupta periods?', options: ['Arikamedu', 'Tamralipta', 'Sopara', 'Korkai'], answer: 1, explain: 'Tamralipta, modern Tamluk on the Rupnarayan, was the principal eastern seaport of that era.' },
  { q: 'Beypore in Kerala is known for building which vessel?', options: ['Kettuvallam', 'Uru dhow', 'Masula boat', 'Catamaran'], answer: 1, explain: 'Beypore has built large wooden uru dhows for generations, many for Gulf owners.' },
  { q: 'Which programme reframed Indian ports as the anchor of a port-led development strategy?', options: ['Bharatmala', 'Sagarmala', 'Setu Bharatam', 'Jal Marg Vikas'], answer: 1, explain: 'Sagarmala, launched in 2015, covers port modernisation, connectivity and coastal shipping.' },
];

/* Gallery ------------------------------------------------------------------- */
const MH_GALLERY = [
  { icon: '🏺', title: 'Lothal Dockyard', caption: 'The Harappan brick basin at Lothal, Gujarat' },
  { icon: '🌶️', title: 'Pepper for Gold', caption: 'The Malabar coast trade that drew Roman ships to Muziris' },
  { icon: '🛕', title: 'Shore Temple', caption: 'The Pallava port of Mahabalipuram, Tamil Nadu' },
  { icon: '⚓', title: 'Calicut Roads', caption: 'Where the Cape route reached India in 1498, Kerala' },
  { icon: '🛶', title: 'Beypore Uru', caption: 'A wooden dhow under construction, Kozhikode' },
  { icon: '📦', title: 'Nhava Sheva', caption: 'Container gantries at JNPA, Maharashtra' },
  { icon: '🌉', title: 'Hooghly Approach', caption: 'India\'s only major riverine port, Kolkata' },
  { icon: '🏝️', title: 'Port Blair', caption: 'The island lifeline of the Andaman & Nicobar territory' },
];
