// data.js - Master timeline data for the Freedom Struggle Timeline (1857-1947)

window.FREEDOM_TIMELINE_DATA = [
    {
        year: 1857,
        title: "Revolt of 1857",
        imageEmoji: "⚔️",
        imageColor: "#ef4444",
        category: "Early Resistance",
        location: "Meerut, Delhi, Lucknow, Jhansi",
        coords: [28.9845, 77.7064],
        leaders: ["Mangal Pandey", "Rani Lakshmibai", "Bahadur Shah Zafar", "Tatya Tope"],
        description: "The first large-scale organized armed rebellion against British East India Company rule, triggered by sepoy grievances.",
        significance: "Brought an end to East India Company governance and shifted control directly to the British Crown, creating early national consciousness.",
        link: "../freedom-movement-explorer/index.html"
    },
    {
        year: 1859,
        title: "Indigo Revolt",
        imageEmoji: "🌿",
        imageColor: "#3b82f6",
        category: "Peasant/Tribal",
        location: "Nadia, Bengal",
        coords: [23.2324, 88.3639],
        leaders: ["Bishnucharan Biswas", "Digambar Biswas"],
        description: "Peasant uprising against British planters who forced cultivators to grow indigo under extremely exploitative terms.",
        significance: "Led to the appointment of the Indigo Commission, which ruled that peasants could not be forced to grow indigo, a major victory for peasant resistance.",
        link: "../freedom-movement-explorer/index.html"
    },
    {
        year: 1885,
        title: "Formation of Indian National Congress",
        imageEmoji: "📜",
        imageColor: "#1e3a8a",
        category: "Constitutional",
        location: "Bombay",
        coords: [18.9220, 72.8347],
        leaders: ["Allan Octavian Hume", "Dadabhai Naoroji", "Dinshaw Wacha"],
        description: "Educated Indians and British civil servants formed the INC in Bombay to create a platform for political dialogue.",
        significance: "Established the political organization that would eventually grow into the primary mass movement leading India to independence.",
        link: "../freedom-movement-explorer/index.html"
    },
    {
        year: 1905,
        title: "Swadeshi & Boycott Movement",
        imageEmoji: "🔥",
        imageColor: "#d97706",
        category: "Swadeshi",
        location: "Bengal & Nationwide",
        coords: [22.5726, 88.3639],
        leaders: ["Bal Gangadhar Tilak", "Bipin Chandra Pal", "Lala Lajpat Rai", "Aurobindo Ghosh"],
        description: "Launched in response to Lord Curzon's partition of Bengal, promoting domestic products (Swadeshi) and boycotting British imports.",
        significance: "Transformed Indian nationalism into an active mass economic and political campaign, setting the stage for future satyagrahas.",
        link: "../freedom-movement-explorer/index.html"
    },
    {
        year: 1913,
        title: "Ghadar Movement",
        imageEmoji: "📢",
        imageColor: "#b91c1c",
        category: "Revolutionary",
        location: "Punjab / San Francisco",
        coords: [31.1471, 75.3412],
        leaders: ["Lala Har Dayal", "Sohan Singh Bhakna", "Kartar Singh Sarabha"],
        description: "An international political movement founded by expatriate Indians, primarily from Punjab, to overthrow British rule through armed revolution.",
        significance: "Inspired revolutionary spirit in Punjab and among overseas Indians, leading to early conspiracies during World War I.",
        link: "../freedom-movement-explorer/index.html"
    },
    {
        year: 1915,
        title: "Gandhi Returns to India",
        imageEmoji: "🚢",
        imageColor: "#059669",
        category: "Gandhian",
        location: "Bombay",
        coords: [18.9220, 72.8347],
        leaders: ["Mahatma Gandhi"],
        description: "Mohandas Karamchand Gandhi returned to India on January 9, 1915, after 21 years of successful civil rights activism in South Africa.",
        significance: "Marked the beginning of the Gandhian era of the independence movement, introducing nonviolent Satyagraha on a national scale.",
        link: "../gandhi-explorer/index.html"
    },
    {
        year: 1917,
        title: "Champaran Satyagraha",
        imageEmoji: "🌾",
        imageColor: "#10b981",
        category: "Gandhian",
        location: "Champaran, Bihar",
        coords: [26.6536, 84.9126],
        leaders: ["Mahatma Gandhi", "Rajendra Prasad", "Raj Kumar Shukla"],
        description: "Gandhi's first Satyagraha campaign in India, defending indigo peasants against exploitative colonial land revenue contracts.",
        significance: "Demonstrated the power of Satyagraha in India, establishing Gandhi as a prominent leader of the poor masses.",
        link: "../gandhi-explorer/index.html"
    },
    {
        year: 1919,
        title: "Jallianwala Bagh Massacre",
        imageEmoji: "🕊️",
        imageColor: "#374151",
        category: "Early Resistance",
        location: "Amritsar, Punjab",
        coords: [31.6340, 74.8723],
        leaders: ["Dr. Saifuddin Kitchlew", "Dr. Satyapal", "General Dyer (Perpetrator)"],
        description: "British troops opened fire on a peaceful protest gathering at Jallianwala Bagh garden, killing hundreds of unarmed civilians.",
        significance: "Severely alienated Indians from the British Raj, leading to Rabindranath Tagore renouncing his knighthood and Gandhi launching the Non-Cooperation movement.",
        link: "../freedom-movement-explorer/index.html"
    },
    {
        year: 1920,
        title: "Non-Cooperation Movement",
        imageEmoji: "🛑",
        imageColor: "#f97316",
        category: "Gandhian",
        location: "Nationwide",
        coords: [21.1458, 79.0882],
        leaders: ["Mahatma Gandhi", "Chittaranjan Das", "Motilal Nehru", "Shaukat Ali"],
        description: "Mass civil disobedience campaign boycotting British government institutions, courts, educational centers, and foreign cloth.",
        significance: "The first nationwide mass Satyagraha campaign, transforming the Indian National Congress into a household political force.",
        link: "../gandhi-explorer/index.html"
    },
    {
        year: 1922,
        title: "Chauri Chaura Incident",
        imageEmoji: "🔥",
        imageColor: "#dc2626",
        category: "Gandhian",
        location: "Chauri Chaura, Gorakhpur, UP",
        coords: [26.6438, 83.5878],
        leaders: ["Mahatma Gandhi"],
        description: "A violent clash between protesters and police led to the burning of a police station. Outraged by the violence, Gandhi suspended the Non-Cooperation movement.",
        significance: "Reasserted Gandhi's strict adherence to absolute nonviolence (Ahimsa) as the foundational baseline of the struggle.",
        link: "../gandhi-explorer/index.html"
    },
    {
        year: 1925,
        title: "Kakori Train Action",
        imageEmoji: "🚂",
        imageColor: "#7c3aed",
        category: "Revolutionary",
        location: "Kakori, Uttar Pradesh",
        coords: [26.8687, 80.7951],
        leaders: ["Ram Prasad Bismil", "Ashfaqulla Khan", "Chandrashekhar Azad", "Rajendra Lahiri"],
        description: "HRA revolutionaries intercepted a British government treasury train to secure funding for armed activities.",
        significance: "Highlighted the active underground armed resistance movement and inspired deep patriotic sentiment among the youth.",
        link: "../freedom-movement-explorer/index.html"
    },
    {
        year: 1928,
        title: "Simon Commission Protests",
        imageEmoji: "🚫",
        imageColor: "#2563eb",
        category: "Constitutional",
        location: "Lahore, Punjab",
        coords: [31.5204, 74.3587],
        leaders: ["Lala Lajpat Rai", "Bhagat Singh"],
        description: "Mass protests against the all-British Simon Commission. Lala Lajpat Rai was fatally injured during a police lathi charge.",
        significance: "Triggered severe national resentment and directly led to retaliatory revolutionary activities by the HSRA.",
        link: "../freedom-movement-explorer/index.html"
    },
    {
        year: 1930,
        title: "Dandi March (Salt Satyagraha)",
        imageEmoji: "🧂",
        imageColor: "#059669",
        category: "Gandhian",
        location: "Sabarmati to Dandi, Gujarat",
        coords: [20.8879, 72.7844],
        leaders: ["Mahatma Gandhi", "Sarojini Naidu", "Kamaladevi Chattopadhyay"],
        description: "Gandhi led a 240-mile walk to the coast at Dandi to make salt from seawater, violating the British state salt tax monopoly.",
        significance: "Sparked the massive Civil Disobedience Movement, attracting global media attention to the Indian self-determination campaign.",
        link: "../gandhi-explorer/index.html"
    },
    {
        year: 1931,
        title: "Martyrdom of Bhagat Singh & HRA Heroes",
        imageEmoji: "🥀",
        imageColor: "#db2777",
        category: "Revolutionary",
        location: "Lahore Central Jail",
        coords: [31.5204, 74.3587],
        leaders: ["Bhagat Singh", "Shivaram Rajguru", "Sukhdev Thapar"],
        description: "The execution of young revolutionary leaders Bhagat Singh, Rajguru, and Sukhdev for their active resistance operations.",
        significance: "Immortalized the sacrifices of revolutionary nationalists and galvanized millions of youth across the country.",
        link: "../freedom-movement-explorer/index.html"
    },
    {
        year: 1942,
        title: "Quit India Movement",
        imageEmoji: "✊",
        imageColor: "#f97316",
        category: "Gandhian",
        location: "Bombay",
        coords: [18.9220, 72.8347],
        leaders: ["Mahatma Gandhi", "Aruna Asaf Ali", "Jayaprakash Narayan", "Maulana Azad"],
        description: "Launched during World War II with Gandhi's call to 'Do or Die', demanding immediate British withdrawal from India.",
        significance: "Despite the arrest of the entire Congress leadership, it sparked massive spontaneous protests, signaling the final phase of British colonial rule.",
        link: "../gandhi-explorer/index.html"
    },
    {
        year: 1944,
        title: "INA Battle of Imphal & Kohima",
        imageEmoji: "🎖️",
        imageColor: "#059669",
        category: "Armed/Military",
        location: "Imphal & Kohima",
        coords: [24.8170, 93.9368],
        leaders: ["Subhas Chandra Bose", "Shah Nawaz Khan", "Prem Sahgal"],
        description: "The Indian National Army (Azad Hind Fauj), allied with Japanese forces, advanced into Northeast India, engaging British forces.",
        significance: "The first armed campaign on Indian soil by an independent Indian military command, severely threatening British military prestige.",
        link: "../freedom-movement-explorer/index.html"
    },
    {
        year: 1946,
        title: "Royal Indian Navy Mutiny",
        imageEmoji: "⚓",
        imageColor: "#1e3a8a",
        category: "Armed/Military",
        location: "Bombay / Karachi",
        coords: [18.9220, 72.8347],
        leaders: ["M.S. Khan", "Madan Singh"],
        description: "A total strike and mutiny by Indian sailors of the Royal Indian Navy on ships and shore installations in Bombay and Karachi.",
        significance: "Demonstrated to the British government that they could no longer rely on the Indian armed forces to maintain control over the country.",
        link: "../freedom-movement-explorer/index.html"
    },
    {
        year: 1946,
        title: "Cabinet Mission Scheme",
        imageEmoji: "🏢",
        imageColor: "#4b5563",
        category: "Constitutional",
        location: "New Delhi",
        coords: [28.6139, 77.2090],
        leaders: ["Jawaharlal Nehru", "Sardar Patel", "Pethick-Lawrence", "Stafford Cripps"],
        description: "British delegation formulated plans for a federal union of India, transition of power, and establishment of a Constituent Assembly.",
        significance: "Laid the legal-constitutional groundwork for the transfer of power and creation of the Constituent Assembly.",
        link: "../freedom-movement-explorer/index.html"
    },
    {
        year: 1947,
        title: "Independence & Partition of India",
        imageEmoji: "🇮🇳",
        imageColor: "#ef4444",
        category: "Constitutional",
        location: "New Delhi",
        coords: [28.6139, 77.2090],
        leaders: ["Jawaharlal Nehru", "Sardar Vallabhbhai Patel", "Lord Mountbatten"],
        description: "The Indian Independence Act terminated British rule on August 15, 1947, partitioning the subcontinent into India and Pakistan.",
        significance: "Marked the culmination of nearly a century of struggle, birth of a free democratic nation, but accompanied by tragic partition violence.",
        link: "../freedom-movement-explorer/index.html"
    }
];
