const festivals = [
  {
    name: "Diwali",
    month: 10,
    day: 31,
    category: "Religious",
    region: "Pan-India",
    image: "assets/diwali.jpg",
    foods: ["Laddoo", "Barfi", "Namkeen"],
    description: "Festival of lights celebrated across India.",
  },
  {
    name: "Holi",
    month: 3,
    day: 17,
    category: "Cultural",
    region: "Pan-India",
    image: "assets/holi.jpg",
    foods: ["Gujiya", "Thandai", "Papri"],
    description: "Festival of colours celebrating the arrival of spring.",
  },
  {
    name: "Onam",
    month: 8,
    day: 28,
    category: "Harvest",
    region: "Kerala",
    image: "assets/onam.jpg",
    foods: ["Sadya", "Payasam"],
    description: "A major harvest festival celebrated with floral decorations, boat races, and elaborate feasts.",
  },
  {
    name: "Durga Puja",
    month: 10,
    day: 15,
    category: "Religious",
    region: "East India",
    image: "assets/durga-puja.jpg",
    foods: ["Bhog", "Mishti doi", "Pulao"],
    description: "A major festival worshipping the goddess Durga, especially in East India.",
  },
  {
    name: "Bihu",
    month: 1,
    day: 14,
    category: "Harvest",
    region: "Assam",
    image: "assets/bihu.jpg",
    foods: ["Pitha", "Laru", "Jolpan"],
    description: "Assamese New Year harvest festival celebrated with traditional music and dance.",
  },
  {
    name: "Pongal",
    month: 1,
    day: 15,
    category: "Harvest",
    region: "Tamil Nadu",
    image: "assets/pongal.jpg",
    foods: ["Pongal", "Sarkarai Pongal", "Venn Pongal"],
    description: "Tamil harvest festival thanking the sun god for a bountiful harvest.",
  },
  {
    name: "Raksha Bandhan",
    month: 8,
    day: 30,
    category: "Religious",
    region: "Pan-India",
    image: "assets/raksha-bandhan.jpg",
    foods: ["Rakhi sweets", "Kheer", "Thali"],
    description: "Celebrating the bond between brothers and sisters.",
  },
  {
    name: "Janmashtami",
    month: 8,
    day: 19,
    category: "Religious",
    region: "Pan-India",
    image: "assets/janmashtami.jpg",
    foods: ["Makhan", "Sweets", "Panchamrit"],
    description: "Celebrating the birth of Lord Krishna.",
  },
  {
    name: "Ganesh Chaturthi",
    month: 8,
    day: 7,
    category: "Religious",
    region: "Maharashtra",
    image: "assets/ganesh.jpg",
    foods: ["Modak", "Laddu", "Coconut rice"],
    description: "Worship of Lord Ganesha, especially in Maharashtra.",
  },
  {
    name: "Navratri",
    month: 10,
    day: 1,
    category: "Religious",
    region: "West India",
    image: "assets/navratri.jpg",
    foods: ["Falahar", "Sabudana khichdi", "Kuttu ki poori"],
    description: "Nine nights of dance and worship dedicated to the goddess Durga.",
  },
  {
    name: "Christmas",
    month: 12,
    day: 25,
    category: "Religious",
    region: "Pan-India",
    image: "assets/christmas.jpg",
    foods: ["Plum cake", "Vinho", "Roast turkey"],
    description: "Celebration of the birth of Jesus Christ.",
  },
  {
    name: "Eid al-Fitr",
    month: 10,
    day: 1,
    category: "Religious",
    region: "Pan-India",
    image: "assets/eid.jpg",
    foods: ["Seviyan", "Biryani", "Sheerkurma"],
    description: "Festival marking the end of Ramadan.",
  },
  {
    name: "Basant Panchami",
    month: 2,
    day: 15,
    category: "Cultural",
    region: "North India",
    image: "assets/basant.jpg",
    foods: ["Sweet rice", "Sarson ka saag", "Makki di roti"],
    description: "Welcome spring, worship of goddess Saraswati.",
  },
  {
    name: "Rath Yatra",
    month: 6,
    day: 20,
    category: "Religious",
    region: "East India",
    image: "assets/rath-yatra.jpg",
    foods: ["Puri", "Sabzi", "Sweets"],
    description: "Chariot festival of Lord Jagannath in Puri.",
  },
];

if (typeof window !== 'undefined') {
  window.festivalData = festivals;
}
export { festivals };