/* ==========================================================================
   INDIAN TRADITIONAL MARTIAL ARTS — DATASET
   Every section of the explorer renders from these arrays. To add a martial
   art, append one object to MARTIAL_ARTS — no rendering code needs to change.
   ========================================================================== */

const MA_REGIONS = [
  { key: 'south', name: 'South India', icon: '🌴' },
  { key: 'north', name: 'North India', icon: '🏔️' },
  { key: 'west', name: 'West India', icon: '🏜️' },
  { key: 'east', name: 'East India', icon: '🌾' },
  { key: 'northeast', name: 'Northeast India', icon: '🍃' },
];

const MA_WEAPON_CLASSES = [
  { key: 'unarmed', name: 'Unarmed', icon: '👊' },
  { key: 'sword', name: 'Sword & Shield', icon: '⚔️' },
  { key: 'staff', name: 'Staff & Stick', icon: '🥢' },
  { key: 'flexible', name: 'Flexible Weapons', icon: '🌀' },
  { key: 'spear', name: 'Spear & Polearm', icon: '🔱' },
];

/* Status is used to drive the endangerment indicator on each card. */
const MA_STATUS = {
  thriving: { label: 'Thriving', tone: 'good', desc: 'Actively taught, with a stable base of students and public performance.' },
  reviving: { label: 'Reviving', tone: 'warn', desc: 'Declined sharply but now supported by state bodies, festivals or new schools.' },
  endangered: { label: 'Endangered', tone: 'bad', desc: 'Very few living practitioners; transmission depends on a handful of families.' },
};

const MARTIAL_ARTS = [
  {
    name: 'Kalaripayattu',
    icon: '🤸',
    state: 'Kerala',
    region: 'south',
    era: 'References from the Sangam era; codified form by c. 11th–12th century CE',
    status: 'thriving',
    weaponClasses: ['unarmed', 'sword', 'staff', 'flexible'],
    tagline: 'Often described as among the oldest surviving fighting systems',
    summary: 'Practised inside a sunken earthen pit called a kalari, Kalaripayattu combines strikes, grappling, weapons and a healing tradition rooted in marma (vital point) knowledge. Training is as much about body conditioning and oil massage as it is about combat.',
    stages: [
      { name: 'Meithari', desc: 'Body conditioning — jumps, kicks, stances and flexibility sequences performed without weapons.' },
      { name: 'Kolthari', desc: 'Wooden weapons — the kettukari staff, cheruvadi short stick and otta, a curved wooden weapon shaped to strike marma points.' },
      { name: 'Ankathari', desc: 'Metal weapons — dagger, sword and shield, spear, and finally the urumi flexible sword.' },
      { name: 'Verumkai', desc: 'Bare-handed combat against armed and unarmed opponents, taught last because it requires marma knowledge.' },
    ],
    weapons: ['Urumi (flexible sword)', 'Otta', 'Kettukari staff', 'Val and paricha (sword and shield)', 'Kuntham (spear)'],
    where: 'Kalaris across Kerala, particularly Kozhikode, Thrissur, Kannur and Palakkad',
    note: 'The northern (vadakkan) and southern (thekkan) styles differ significantly in stance, emphasis and lineage.',
  },
  {
    name: 'Silambam',
    icon: '🥢',
    state: 'Tamil Nadu',
    region: 'south',
    era: 'Mentioned in Sangam literature; organised schools by the medieval period',
    status: 'thriving',
    weaponClasses: ['staff', 'flexible', 'unarmed'],
    tagline: 'The Tamil art of the bamboo staff',
    summary: 'Built around a bamboo staff roughly the height of the practitioner, Silambam emphasises continuous circular motion, footwork patterns called kaaladi, and the ability to hold off multiple attackers at once. It later spread with Tamil traders across Southeast Asia.',
    stages: [
      { name: 'Kaaladi', desc: 'Foot movement patterns — the foundation on which every strike and block in the system is built.' },
      { name: 'Nilai', desc: 'Stances and guard positions, each paired with a specific range and set of strikes.' },
      { name: 'Suttru', desc: 'Spinning and figure-of-eight staff work used to build defensive walls of motion.' },
      { name: 'Weapon transfer', desc: 'Applying staff principles to maru, aruval, sword and the flexible surul pattai.' },
    ],
    weapons: ['Silambam staff', 'Maru (deer-horn weapon)', 'Aruval (sickle)', 'Surul pattai (flexible blade)', 'Vaal (sword)'],
    where: 'Schools across Tamil Nadu, with strong presence in Thanjavur, Madurai and Chennai',
    note: 'Silambam was among the arts restricted under colonial-era weapons legislation, and revived after Independence.',
  },
  {
    name: 'Thang-Ta (Huyen Langlon)',
    icon: '⚔️',
    state: 'Manipur',
    region: 'northeast',
    era: 'Traced to the Meitei kingdom; systematised over several centuries',
    status: 'reviving',
    weaponClasses: ['sword', 'spear', 'unarmed'],
    tagline: 'The sword and the spear of the Meitei',
    summary: 'Huyen Langlon covers two branches: thang (sword) and ta (spear). It exists in three modes — a ritual mode tied to Meitei cosmology, a performance mode of choreographed sequences, and a combat mode taught only to advanced students.',
    stages: [
      { name: 'Leiteng thang', desc: 'Fundamental sword forms and cutting angles practised solo.' },
      { name: 'Ta khousaba', desc: 'Spear technique, including thrusting, sweeping and the paired spear-and-shield method.' },
      { name: 'Thengou', desc: 'Ritual sequences performed on ceremonial occasions, preserving the older forms intact.' },
      { name: 'Sarit sarak', desc: 'The unarmed component — strikes, locks and throws derived from armed principles.' },
    ],
    weapons: ['Thang (sword)', 'Ta (spear)', 'Chungoi (shield)', 'Cheibi (leather-covered club)'],
    where: 'Imphal valley and across Manipur; taught by state and private academies',
    note: 'Thang-Ta was suppressed during colonial rule and revived from the 1950s onward through cultural organisations.',
  },
  {
    name: 'Gatka',
    icon: '🛡️',
    state: 'Punjab',
    region: 'north',
    era: 'Developed within the Sikh martial tradition from the 17th century onward',
    status: 'thriving',
    weaponClasses: ['sword', 'staff', 'flexible'],
    tagline: 'The Sikh martial art of the soti and shield',
    summary: 'Gatka trains rhythmic, circular weapon movement synchronised to drumbeat. Students begin with a wooden soti and leather shield before moving to the sword. It is closely tied to Sikh religious practice and is performed at Hola Mohalla each spring.',
    stages: [
      { name: 'Pentra', desc: 'The footwork rhythm — a triangular stepping pattern that keeps the practitioner constantly mobile.' },
      { name: 'Soti and farri', desc: 'Wooden stick and small shield work, learned as a safe substitute for live steel.' },
      { name: 'Shastar vidiya', desc: 'The wider weapon curriculum: sword, spear, chakram and the flexible marati.' },
      { name: 'Rehearsed combat', desc: 'Paired and group sequences performed publicly at gurdwaras and festivals.' },
    ],
    weapons: ['Soti (wooden stick)', 'Farri (shield)', 'Kirpan', 'Chakram (throwing quoit)', 'Barcha (spear)'],
    where: 'Punjab, Haryana and Sikh communities worldwide; large displays at Anandpur Sahib',
    note: 'Hola Mohalla at Anandpur Sahib remains the largest public gathering of Gatka practitioners anywhere.',
  },
  {
    name: 'Mardani Khel',
    icon: '🐎',
    state: 'Maharashtra',
    region: 'west',
    era: 'Associated with Maratha warfare from the 17th century',
    status: 'reviving',
    weaponClasses: ['sword', 'flexible', 'staff'],
    tagline: 'Weapon art of the Maratha hill forts',
    summary: 'Shaped by fighting in the narrow passes and fort corridors of the Sahyadris, Mardani Khel favours quick close-range weapon work over long engagements. The dandpatta, a gauntlet sword, is its signature weapon.',
    stages: [
      { name: 'Conditioning', desc: 'Rope, mallakhamb pole and weight work to build the grip and shoulder strength the weapons demand.' },
      { name: 'Lathi', desc: 'Stick technique, taught first because it maps directly onto sword angles.' },
      { name: 'Dandpatta', desc: 'The gauntlet sword — a flexible blade fixed to a metal hand guard, wielded in wide sweeping arcs.' },
      { name: 'Paired combat', desc: 'Sparring sequences, often demonstrated at Dussehra and Shivaji Jayanti events.' },
    ],
    weapons: ['Dandpatta (gauntlet sword)', 'Vita (tethered spear)', 'Lathi', 'Talwar', 'Katar (push dagger)'],
    where: 'Kolhapur, Satara, Pune and the western Maharashtra fort belt',
    note: 'Kolhapur remains the recognised centre, with akharas that have taught the art continuously for generations.',
  },
  {
    name: 'Kushti (Pehlwani)',
    icon: '🤼',
    state: 'North and West India',
    region: 'north',
    era: 'Rooted in ancient malla-yuddha; the modern form shaped in the Mughal era',
    status: 'thriving',
    weaponClasses: ['unarmed'],
    tagline: 'Wrestling in the clay pit',
    summary: 'Practised in an akhara on a prepared bed of clay mixed with ghee, turmeric and buttermilk, Kushti is as much a way of life as a sport — governed by rules on diet, celibacy, sleep and daily labour alongside technique.',
    stages: [
      { name: 'Akhara discipline', desc: 'Life inside the wrestling school: early rising, communal cooking, and maintaining the clay pit itself.' },
      { name: 'Conditioning', desc: 'Thousands of daily dands and bethaks, plus mudgar clubs, gada mace and stone-ring training.' },
      { name: 'Technique', desc: 'Throws, holds and pins — dhobi pachad, kala jang, dhak and the counter chains built around them.' },
      { name: 'Competition', desc: 'Dangal bouts fought on clay, traditionally decided by pinning both shoulders to the ground.' },
    ],
    weapons: ['Unarmed only', 'Mudgar clubs (training)', 'Gada mace (training)'],
    where: 'Akharas across Punjab, Haryana, Uttar Pradesh, Maharashtra and Delhi',
    note: 'Indian clay wrestling produced the technical base for many of India\'s Olympic freestyle wrestlers.',
  },
  {
    name: 'Musti Yuddha',
    icon: '👊',
    state: 'Uttar Pradesh',
    region: 'north',
    era: 'Referenced in classical texts; the Varanasi form documented over centuries',
    status: 'endangered',
    weaponClasses: ['unarmed'],
    tagline: 'Bare-fist combat of Varanasi',
    summary: 'An unarmed striking art using fists, elbows, knees and headbutts, historically fought without protection. Its curriculum divides techniques by the part of the body struck, and it retains a strong connection to breath and meditation practice.',
    stages: [
      { name: 'Preparation', desc: 'Hand conditioning, breath control and stance work before any contact training.' },
      { name: 'Striking sets', desc: 'Fist, elbow, knee and head strikes drilled in fixed combinations.' },
      { name: 'Target division', desc: 'Techniques classified by the region of the body targeted — a system unusual among Indian arts.' },
      { name: 'Free exchange', desc: 'Controlled bouts, historically staged around Varanasi\'s wrestling grounds.' },
    ],
    weapons: ['Unarmed only'],
    where: 'Traditionally centred on Varanasi; very few active teachers remain',
    note: 'Among the most at-risk arts on this page — transmission now depends on a small number of elderly practitioners.',
  },
  {
    name: 'Cheibi Gad-ga',
    icon: '🏏',
    state: 'Manipur',
    region: 'northeast',
    era: 'A sportive form derived from Manipuri sword combat',
    status: 'reviving',
    weaponClasses: ['staff'],
    tagline: 'Club and shield duelling',
    summary: 'Two contestants face each other with a cheibi — a short stick wrapped in leather — and a round shield, inside a marked circle. It is the safe, competitive descendant of sword-and-shield fighting, with scoring based on clean contact.',
    stages: [
      { name: 'Circle discipline', desc: 'Learning to control distance inside a 7-metre ring without stepping out.' },
      { name: 'Shield work', desc: 'Deflection technique, since blocking rather than absorbing is the core defensive idea.' },
      { name: 'Strike scoring', desc: 'Targeting permitted areas cleanly, as bouts are judged on contact quality.' },
      { name: 'Competition', desc: 'Timed rounds contested at state-level Manipuri sporting events.' },
    ],
    weapons: ['Cheibi (leather-covered stick)', 'Round shield'],
    where: 'Manipur, at state sports meets and cultural festivals',
    note: 'Its rules make it one of the few Indian weapon arts that can be safely contested at full intent.',
  },
  {
    name: 'Inbuan Wrestling',
    icon: '🪢',
    state: 'Mizoram',
    region: 'northeast',
    era: 'Recorded among the Mizo since at least the 18th century',
    status: 'reviving',
    weaponClasses: ['unarmed'],
    tagline: 'Wrestling by the belt, without a step',
    summary: 'Contestants grip a belt worn at the waist and must throw their opponent without ever releasing it. Stepping outside the circle, bending the knee or kicking ends the bout — constraints that make it unusually technical.',
    stages: [
      { name: 'The grip', desc: 'Both hands take the opponent\'s waist belt and may not let go for the whole bout.' },
      { name: 'Balance', desc: 'Since knee bending is forbidden, everything depends on hip position and upper-body leverage.' },
      { name: 'Throws', desc: 'Lifts and rotations that unbalance the opponent while both wrestlers stay upright.' },
      { name: 'Ring control', desc: 'Winning by lifting the opponent clear of the ground, inside the marked circle.' },
    ],
    weapons: ['Unarmed only'],
    where: 'Mizoram, contested during the Mizo festival calendar',
    note: 'Traditionally held during Mim Kut and other Mizo festivals rather than as a standalone sport.',
  },
  {
    name: 'Thoda',
    icon: '🏹',
    state: 'Himachal Pradesh',
    region: 'north',
    era: 'Linked by local tradition to the archery of the Mahabharata narrative',
    status: 'endangered',
    weaponClasses: ['spear'],
    tagline: 'Ritual archery of the Kullu valley',
    summary: 'Two teams — the Pashi and the Saathi — shoot blunt-headed wooden arrows at each other\'s legs, accompanied by drums and dance. It is a spring festival contest as much as a martial contest, held around Baisakhi.',
    stages: [
      { name: 'Team formation', desc: 'Villages divide into the two traditional groups, each with its own drum rhythm and songs.' },
      { name: 'The dance', desc: 'Rounds open with a dance sequence in which both sides display before the shooting starts.' },
      { name: 'Shooting', desc: 'Blunt wooden arrows are aimed only below the knee; hits are counted for scoring.' },
      { name: 'Evasion', desc: 'Defenders use footwork and shin position rather than shields to avoid being struck.' },
    ],
    weapons: ['Longbow', 'Blunt wooden-headed arrows'],
    where: 'Kullu and Shimla districts of Himachal Pradesh, chiefly around Baisakhi',
    note: 'Fewer villages field teams each year, making Thoda one of the most fragile traditions on this page.',
  },
  {
    name: 'Paika Akhada',
    icon: '🗡️',
    state: 'Odisha',
    region: 'east',
    era: 'From the Paika militias of the Gajapati kingdom of Odisha',
    status: 'reviving',
    weaponClasses: ['sword', 'staff'],
    tagline: 'The warrior-peasant art of Odisha',
    summary: 'Paika Akhada trains sword and shield alongside acrobatics performed to drums. The Paikas were a landholding militia class, and the art survives today largely as a performance tradition tied to their memory.',
    stages: [
      { name: 'Drum time', desc: 'Every sequence is set to a dhol rhythm, so timing is trained before technique.' },
      { name: 'Acrobatics', desc: 'Rolls, cartwheels and leaps built into weapon routines, distinguishing it from other sword arts.' },
      { name: 'Khanda and dhala', desc: 'Straight sword and shield practice, the core armed component.' },
      { name: 'Group display', desc: 'Multi-person choreographed routines performed at festivals across Odisha.' },
    ],
    weapons: ['Khanda (straight sword)', 'Dhala (shield)', 'Banati (fire staff)', 'Lathi'],
    where: 'Khordha, Puri and coastal Odisha',
    note: 'Interest rose sharply around the bicentenary commemorations of the 1817 Paika rebellion.',
  },
  {
    name: 'Lathi Khela',
    icon: '🪵',
    state: 'West Bengal',
    region: 'east',
    era: 'A long-standing rural Bengali stick-fighting tradition',
    status: 'endangered',
    weaponClasses: ['staff'],
    tagline: 'Bengali stick fighting',
    summary: 'A bamboo staff art once maintained by village lathiyals who served as guards and enforcers for landholders. It survives mainly in demonstration form at rural fairs, with very few teaching akharas left.',
    stages: [
      { name: 'Grip and stance', desc: 'Single and double-handed grips, each suited to a different fighting range.' },
      { name: 'Spinning defence', desc: 'Continuous rotation used to hold off several opponents at once.' },
      { name: 'Strike lines', desc: 'Fixed cutting angles drilled against a post before any partner work.' },
      { name: 'Display bouts', desc: 'Paired sequences performed at melas, weddings and rural festivals.' },
    ],
    weapons: ['Bamboo lathi', 'Sarki (short spear)'],
    where: 'Rural West Bengal, mostly in Murshidabad, Birbhum and Bardhaman districts',
    note: 'The lathiyal profession disappeared with the abolition of the zamindari system, taking most of the teaching base with it.',
  },
];

/* Weapons reference -------------------------------------------------------- */
const MA_WEAPONS = [
  { name: 'Urumi', icon: '🌀', origin: 'Kerala', art: 'Kalaripayattu', desc: 'A flexible whip-sword of one or more thin steel blades. Taught last, because a mistake injures the wielder before the opponent.' },
  { name: 'Dandpatta', icon: '🤺', origin: 'Maharashtra', art: 'Mardani Khel', desc: 'A gauntlet sword whose flexible blade extends from a full hand-and-forearm guard, designed for sweeping cuts in confined fort corridors.' },
  { name: 'Katar', icon: '🔪', origin: 'North & West India', art: 'Mardani Khel, Gatka', desc: 'A push dagger with an H-shaped horizontal grip, punched forward rather than swung — some versions split on impact.' },
  { name: 'Chakram', icon: '⭕', origin: 'Punjab', art: 'Gatka', desc: 'A flat steel throwing quoit with a sharpened outer edge, spun off the finger or thrown overarm at range.' },
  { name: 'Maru', icon: '🦌', origin: 'Tamil Nadu', art: 'Silambam', desc: 'A parrying weapon made from two blackbuck horns joined at the centre, used for trapping and deflecting rather than cutting.' },
  { name: 'Vita', icon: '🪝', origin: 'Maharashtra', art: 'Mardani Khel', desc: 'A spear tethered to a cord so it can be thrown and pulled straight back to the hand for a second throw.' },
  { name: 'Valari', icon: '🪃', origin: 'Tamil Nadu', art: 'Tamil weapon traditions', desc: 'A curved metal throwing weapon that returns along an arc, used historically for hunting and in Tamil warfare.' },
  { name: 'Otta', icon: '🪝', origin: 'Kerala', art: 'Kalaripayattu', desc: 'An S-curved wooden weapon shaped like an elephant\'s tusk, used to train precise strikes at marma vital points.' },
  { name: 'Bagh Nakh', icon: '🐅', origin: 'Maharashtra', art: 'Concealed weapon traditions', desc: 'Curved claws fitted across the palm or fingers, designed to be hidden in a closed fist.' },
  { name: 'Kettukari', icon: '🥢', origin: 'Kerala', art: 'Kalaripayattu', desc: 'A long staff, usually cut to the practitioner\'s own height, forming the first weapon taught in the Kolthari stage.' },
  { name: 'Gada', icon: '🏋️', origin: 'North India', art: 'Kushti', desc: 'A stone or metal mace on a bamboo shaft, swung behind the back in sets to build shoulder and grip strength.' },
  { name: 'Aruval', icon: '🌾', origin: 'Tamil Nadu', art: 'Silambam', desc: 'A heavy curved sickle that doubles as a farm tool, which is exactly why it survived where swords were confiscated.' },
];

/* Timeline ----------------------------------------------------------------- */
const MA_TIMELINE = [
  { year: 'c. 300 BCE – 300 CE', title: 'The Sangam references', desc: 'Tamil Sangam poetry describes staff, spear and sword combat, giving the earliest literary evidence of organised martial practice in the south.' },
  { year: 'c. 200 BCE onward', title: 'Dhanurveda takes shape', desc: 'The Dhanurveda tradition, treated as an auxiliary body of knowledge to the Vedas, classifies weapons and sets out training principles later echoed across regional systems.' },
  { year: 'c. 11th–12th century', title: 'Kalaris across Kerala', desc: 'Kerala\'s long period of feudal warfare produces a dense network of kalari training halls, each attached to a locality and a lineage.' },
  { year: '17th century', title: 'Maratha and Sikh traditions', desc: 'Mardani Khel develops around Maratha fort warfare, while the Sikh martial tradition that later takes the name Gatka is consolidated in Punjab.' },
  { year: '18th century', title: 'Meitei codification', desc: 'Huyen Langlon is formalised in Manipur, with distinct ritual, performance and combat branches maintained side by side.' },
  { year: '1857 onward', title: 'Colonial restriction', desc: 'Post-rebellion arms legislation and the disarming of martial communities push weapon practice underground; several arts survive only as festival performance.' },
  { year: '1920s–1940s', title: 'Revival with the national movement', desc: 'Physical culture and indigenous martial arts are consciously revived as part of the cultural side of the freedom movement.' },
  { year: '1950s–1970s', title: 'State patronage begins', desc: 'Newly formed state academies and cultural bodies begin funding Thang-Ta, Kalaripayattu and other traditions as heritage practice.' },
  { year: '1990s–present', title: 'Global visibility', desc: 'Film, stage choreography and international workshops bring Kalaripayattu and Silambam to new audiences — though the least visible arts continue to decline.' },
];

/* Revival efforts ---------------------------------------------------------- */
const MA_REVIVAL = [
  { title: 'State cultural academies', icon: '🏛️', desc: 'Manipur, Kerala and Odisha fund training centres and stipends for teachers, treating the arts as intangible heritage rather than sport.' },
  { title: 'Festival platforms', icon: '🎪', desc: 'Hola Mohalla, Dussehra displays and state cultural festivals give practitioners a public stage — and a reason for young students to train.' },
  { title: 'Akhara networks', icon: '🏠', desc: 'Traditional akharas remain the backbone of Kushti and Lathi Khela, though many have closed as urban land pressure grows.' },
  { title: 'Performance and cinema', icon: '🎬', desc: 'Stage and film choreography has made Kalaripayattu widely visible, drawing students who might otherwise never have encountered it.' },
  { title: 'School programmes', icon: '🎒', desc: 'Silambam and Gatka are taught in some state school and university sports curricula, creating structured entry points.' },
  { title: 'Documentation projects', icon: '📹', desc: 'Video archives and oral-history work aim to record technique from senior practitioners before lineages break.' },
];

/* Threats ------------------------------------------------------------------ */
const MA_THREATS = [
  { title: 'Break in transmission', icon: '⛓️', desc: 'Most of these arts pass from teacher to student in person. When a lineage has only one or two elderly holders, a single death can end it.', severity: 'Critical' },
  { title: 'No economic return', icon: '💸', desc: 'Full-time practice rarely supports a livelihood, so students leave for salaried work in their twenties, exactly when they would become teachers.', severity: 'Critical' },
  { title: 'Loss of training space', icon: '🏗️', desc: 'Clay akharas and open grounds are being built over in growing towns, and the pits themselves are expensive to maintain.', severity: 'High' },
  { title: 'Competition from global sports', icon: '🥋', desc: 'Karate, taekwondo and MMA have organised gradings, competition ladders and career paths that most Indian arts lack.', severity: 'High' },
  { title: 'Performance over practice', icon: '🎭', desc: 'Arts kept alive as stage display can lose their combat content within a generation, retaining the form but not the function.', severity: 'Moderate' },
  { title: 'Fragmented documentation', icon: '📚', desc: 'Much technical knowledge is oral and undocumented, so what is not filmed or written down is simply lost.', severity: 'High' },
];

/* Facts -------------------------------------------------------------------- */
const MA_FACTS = [
  'Kalaripayattu is trained inside a kalari — a pit dug about a metre into the ground, so the floor stays cool and gives underfoot.',
  'In Kalaripayattu, bare-handed fighting is taught last, not first, because it requires knowledge of marma vital points.',
  'Silambam practitioners historically carried a staff as an everyday walking stick, which is part of why the art survived weapons restrictions.',
  'Gatka footwork is trained to a live drumbeat, so rhythm is taught before any strike.',
  'The urumi is a sword made of flexible steel that can be worn wrapped around the waist like a belt.',
  'Kushti wrestlers prepare the clay pit themselves, mixing in ghee, turmeric and buttermilk before every session.',
  'In Inbuan wrestling, a wrestler may never let go of the opponent\'s belt or bend a knee during the bout.',
  'Manipur\'s Huyen Langlon keeps ritual, performance and combat versions of the same techniques as separate branches.',
  'Thoda archers shoot at the legs only, using arrows with deliberately blunt wooden heads.',
  'The vita is a spear on a cord — thrown at an opponent and pulled straight back for the next throw.',
];

/* Quiz --------------------------------------------------------------------- */
const MA_QUIZ = [
  { q: 'In which state is Kalaripayattu traditionally practised?', options: ['Tamil Nadu', 'Kerala', 'Karnataka', 'Manipur'], answer: 1, explain: 'Kalaripayattu is the martial tradition of Kerala, trained in a sunken pit called a kalari.' },
  { q: 'What is the primary weapon of Silambam?', options: ['Curved sword', 'Bamboo staff', 'Throwing quoit', 'Push dagger'], answer: 1, explain: 'Silambam is built around a bamboo staff roughly the height of the practitioner.' },
  { q: 'Thang-Ta comes from which state?', options: ['Mizoram', 'Assam', 'Manipur', 'Nagaland'], answer: 2, explain: 'Thang-Ta, also called Huyen Langlon, is the Meitei martial tradition of Manipur.' },
  { q: 'The urumi is best described as a…', options: ['Throwing axe', 'Flexible whip-sword', 'Spiked shield', 'Long spear'], answer: 1, explain: 'The urumi is a flexible steel whip-sword from Kerala, taught only to advanced students.' },
  { q: 'Which festival features the largest public display of Gatka?', options: ['Baisakhi', 'Hola Mohalla', 'Lohri', 'Diwali'], answer: 1, explain: 'Hola Mohalla at Anandpur Sahib is the largest annual gathering of Gatka practitioners.' },
  { q: 'The dandpatta, signature weapon of Mardani Khel, is a…', options: ['Gauntlet sword', 'Curved dagger', 'Chain whip', 'Battle axe'], answer: 0, explain: 'The dandpatta is a gauntlet sword whose blade extends from a full hand-and-forearm guard.' },
  { q: 'In Inbuan wrestling, which action ends the bout immediately?', options: ['Grabbing the belt', 'Bending the knee', 'Lifting the opponent', 'Stepping forward'], answer: 1, explain: 'Bending a knee, kicking, or stepping out of the circle all end an Inbuan bout.' },
  { q: 'Which order does Kalaripayattu training actually follow?', options: ['Weapons → body conditioning → bare hands', 'Body conditioning → wooden weapons → metal weapons → bare hands', 'Bare hands → weapons → conditioning', 'Metal weapons → bare hands → staff'], answer: 1, explain: 'Meithari, then Kolthari, then Ankathari, and finally Verumkai — bare-handed combat comes last.' },
  { q: 'Thoda, the ritual archery contest, belongs to which state?', options: ['Uttarakhand', 'Himachal Pradesh', 'Sikkim', 'Jammu & Kashmir'], answer: 1, explain: 'Thoda is contested in the Kullu and Shimla districts of Himachal Pradesh around Baisakhi.' },
  { q: 'Paika Akhada is associated with which region?', options: ['Odisha', 'Bihar', 'Jharkhand', 'Chhattisgarh'], answer: 0, explain: 'Paika Akhada comes from Odisha, from the Paika militia tradition of the Gajapati kingdom.' },
];

/* Gallery ------------------------------------------------------------------ */
const MA_GALLERY = [
  { icon: '🤸', title: 'Inside a Kalari', caption: 'The sunken earthen training pit of a Kerala kalari' },
  { icon: '🥢', title: 'Silambam Footwork', caption: 'Kaaladi stepping patterns drilled before any strike, Tamil Nadu' },
  { icon: '🛡️', title: 'Gatka at Hola Mohalla', caption: 'Soti and farri display at Anandpur Sahib, Punjab' },
  { icon: '⚔️', title: 'Thang-Ta Sword Form', caption: 'Meitei sword sequence, Imphal valley, Manipur' },
  { icon: '🤼', title: 'The Clay Akhara', caption: 'Kushti wrestlers preparing the pit before training' },
  { icon: '🐎', title: 'Dandpatta Practice', caption: 'Gauntlet sword work in a Kolhapur akhara, Maharashtra' },
  { icon: '🗡️', title: 'Paika Akhada Display', caption: 'Sword, shield and acrobatics performed to dhol, Odisha' },
  { icon: '🏹', title: 'Thoda at Baisakhi', caption: 'Blunt-arrow archery between Pashi and Saathi teams, Himachal Pradesh' },
];
