export const rbiGovernors = [
    {
        name: "Sir Osborne Smith",
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Sir_Osborne_Smith.jpg/220px-Sir_Osborne_Smith.jpg",
        appointmentDate: "1 Apr 1935",
        endDate: "30 Jun 1937",
        tenure: "2 years, 90 days",
        reforms: ["Set up the initial organizational framework of the RBI.", "Organized the issue and banking departments."],
        monetaryPolicy: ["Maintained exchange rate stability during the initial years of the bank."],
        achievements: ["First Governor of the Reserve Bank of India."],
        facts: ["Resigned before his term ended due to differences with the Government of India over exchange rates and interest rates.", "Did not sign any Indian Rupee notes during his tenure."]
    },
    {
        name: "Sir James Braid Taylor",
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Sir_James_Braid_Taylor.jpg/220px-Sir_James_Braid_Taylor.jpg",
        appointmentDate: "1 Jul 1937",
        endDate: "17 Feb 1943",
        tenure: "5 years, 231 days",
        reforms: ["Introduced the first currency notes issued by RBI.", "Prepared the RBI for wartime financing (World War II)."],
        monetaryPolicy: ["Managed the accumulation of Sterling balances during the war."],
        achievements: ["Successfully steered India's monetary policy through the early years of WWII."],
        facts: ["First RBI Governor whose signature appeared on Indian currency notes.", "Died in office."]
    },
    {
        name: "Sir C. D. Deshmukh",
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/C_D_Deshmukh.jpg/220px-C_D_Deshmukh.jpg",
        appointmentDate: "11 Aug 1943",
        endDate: "30 Jun 1949",
        tenure: "5 years, 323 days",
        reforms: ["Oversaw the transition of the RBI from a shareholder's bank to a nationalized institution (1949).", "Regulated the banking sector under the new Banking Regulation Act."],
        monetaryPolicy: ["Handled post-war inflation and the division of assets following the Partition of India."],
        achievements: ["Represented India at the Bretton Woods Conference.", "First Indian Governor of the RBI."],
        facts: ["Later served as the Finance Minister of India.", "Married to Durgabai Deshmukh, a prominent freedom fighter and social worker."]
    },
    {
        name: "Sir Benegal Rama Rau",
        photo: "https://via.placeholder.com/150",
        appointmentDate: "1 Jul 1949",
        endDate: "14 Jan 1957",
        tenure: "7 years, 197 days",
        reforms: ["Fostered the expansion of rural credit and cooperative banking.", "Initiated the setting up of the All India Rural Credit Survey Committee."],
        monetaryPolicy: ["Managed the financial needs of the first Five-Year Plan."],
        achievements: ["Longest-serving Governor of the RBI."],
        facts: ["Resigned due to serious differences with Finance Minister T.T. Krishnamachari over the RBI's autonomy."]
    },
    {
        name: "K. G. Ambegaokar",
        photo: "https://via.placeholder.com/150",
        appointmentDate: "14 Jan 1957",
        endDate: "28 Feb 1957",
        tenure: "45 days",
        reforms: ["Interim management following the resignation of B. Rama Rau."],
        monetaryPolicy: ["Maintained status quo during the transition period."],
        achievements: ["Provided stability during a brief constitutional crisis between the Ministry of Finance and the RBI."],
        facts: ["Did not sign any banknotes during his brief acting tenure."]
    },
    {
        name: "H. V. R. Iyengar",
        photo: "https://via.placeholder.com/150",
        appointmentDate: "1 Mar 1957",
        endDate: "28 Feb 1962",
        tenure: "5 years",
        reforms: ["Introduced the Deposit Insurance Corporation in 1962.", "Expanded the institutional framework for industrial finance."],
        monetaryPolicy: ["Shifted towards a more active monetary policy including the use of variable reserve ratios."],
        achievements: ["Steered the transition to the decimal coinage system in India (1957)."],
        facts: ["Previously served as the Home Secretary and Chairman of the State Bank of India."]
    },
    {
        name: "P. C. Bhattacharya",
        photo: "https://via.placeholder.com/150",
        appointmentDate: "1 Mar 1962",
        endDate: "30 Jun 1967",
        tenure: "5 years, 121 days",
        reforms: ["Established the Industrial Development Bank of India (IDBI) in 1964.", "Setup the Unit Trust of India (UTI)."],
        monetaryPolicy: ["Navigated severe economic strain caused by the Sino-Indian War (1962) and Indo-Pak War (1965)."],
        achievements: ["Managed the controversial devaluation of the Rupee in 1966."],
        facts: ["His signature appeared on the first Rs. 5, Rs. 10, and Rs. 100 notes that featured the size reductions to save paper."]
    },
    {
        name: "L. K. Jha",
        photo: "https://via.placeholder.com/150",
        appointmentDate: "1 Jul 1967",
        endDate: "3 May 1970",
        tenure: "2 years, 306 days",
        reforms: ["Supported the establishment of the National Credit Council.", "Prepared the groundwork for the social control over commercial banks."],
        monetaryPolicy: ["Focused on credit planning to align with five-year plan objectives."],
        achievements: ["Oversaw the monumental nationalization of 14 major commercial banks in 1969 (though the RBI was initially hesitant)."],
        facts: ["An ICS officer who later served as India's Ambassador to the USA."]
    },
    {
        name: "B. N. Adarkar",
        photo: "https://via.placeholder.com/150",
        appointmentDate: "4 May 1970",
        endDate: "15 Jun 1970",
        tenure: "42 days",
        reforms: ["Managed the transition phase post-bank nationalization."],
        monetaryPolicy: ["Continued the credit policies laid down by L.K. Jha."],
        achievements: ["Ensured continuity before the appointment of a full-time Governor."],
        facts: ["An economist who played a key role in the creation of the National Institute of Bank Management."]
    },
    {
        name: "S. Jagannathan",
        photo: "https://via.placeholder.com/150",
        appointmentDate: "16 Jun 1970",
        endDate: "19 May 1975",
        tenure: "4 years, 337 days",
        reforms: ["Expanded the branch network of nationalized banks heavily into rural areas.", "Set up the Credit Guarantee Corporation of India."],
        monetaryPolicy: ["Adopted an extremely tight monetary policy to combat hyperinflation following the 1971 war and the 1973 oil shock."],
        achievements: ["Successfully brought down inflation from over 30% to manageable levels through severe credit squeeze."],
        facts: ["Resigned to become the Executive Director at the International Monetary Fund (IMF)."]
    },
    {
        name: "N. C. Sen Gupta",
        photo: "https://via.placeholder.com/150",
        appointmentDate: "19 May 1975",
        endDate: "19 Aug 1975",
        tenure: "92 days",
        reforms: ["Interim administration during the early days of the Emergency."],
        monetaryPolicy: ["Maintained the tight anti-inflationary stance."],
        achievements: ["Ensured stability during a sudden transition."],
        facts: ["His signature appears on a very rare series of Rs. 1000 notes."]
    },
    {
        name: "K. R. Puri",
        photo: "https://via.placeholder.com/150",
        appointmentDate: "20 Aug 1975",
        endDate: "2 May 1977",
        tenure: "1 year, 255 days",
        reforms: ["Established the Regional Rural Banks (RRBs) to serve the rural economy.", "Set up the Deposit Insurance and Credit Guarantee Corporation (DICGC)."],
        monetaryPolicy: ["Continued credit restraint while directing credit to priority sectors."],
        achievements: ["Oversaw a period of price stability during the Emergency years."],
        facts: ["His appointment was heavily influenced by Sanjay Gandhi, leading to controversies regarding RBI autonomy."]
    },
    {
        name: "M. Narasimham",
        photo: "https://via.placeholder.com/150",
        appointmentDate: "2 May 1977",
        endDate: "30 Nov 1977",
        tenure: "212 days",
        reforms: ["Contributed to the restructuring of the banking sector."],
        monetaryPolicy: ["Navigated monetary policy during the transition from the Emergency to the Janata Party government."],
        achievements: ["First and only Governor to be appointed from the Reserve Bank cadre (he joined RBI as a Research Officer)."],
        facts: ["Later chaired the famous Narasimham Committees on banking and financial sector reforms in 1991 and 1998."]
    },
    {
        name: "Dr. I. G. Patel",
        photo: "https://upload.wikimedia.org/wikipedia/en/thumb/0/07/I._G._Patel.jpg/220px-I._G._Patel.jpg",
        appointmentDate: "1 Dec 1977",
        endDate: "15 Sep 1982",
        tenure: "4 years, 288 days",
        reforms: ["Oversaw the demonetization of high-denomination notes in 1978.", "Established the National Bank for Agriculture and Rural Development (NABARD)."],
        monetaryPolicy: ["Managed the balance of payments crisis triggered by the second oil shock (1979)."],
        achievements: ["Steered India's negotiation for the massive IMF Extended Fund Facility loan in 1981."],
        facts: ["A world-renowned economist who later served as the Director of the London School of Economics."]
    },
    {
        name: "Dr. Manmohan Singh",
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Manmohan_Singh_Portrait.jpg/220px-Manmohan_Singh_Portrait.jpg",
        appointmentDate: "16 Sep 1982",
        endDate: "14 Jan 1985",
        tenure: "2 years, 120 days",
        reforms: ["Initiated comprehensive legal reforms for the banking sector.", "Set up the Urban Banks Department in the RBI."],
        monetaryPolicy: ["Focused heavily on inflation management through quantitative credit controls."],
        achievements: ["Oversaw the establishment of the Board for Industrial and Financial Reconstruction (BIFR)."],
        facts: ["Later became the Finance Minister who liberalized the Indian economy (1991) and served as the Prime Minister of India (2004-2014)."]
    },
    {
        name: "A. Ghosh",
        photo: "https://via.placeholder.com/150",
        appointmentDate: "15 Jan 1985",
        endDate: "4 Feb 1985",
        tenure: "20 days",
        reforms: ["Interim management."],
        monetaryPolicy: ["Maintained status quo."],
        achievements: ["Shortest serving Governor in the history of the RBI (20 days)."],
        facts: ["Served as Deputy Governor and took over briefly pending the arrival of R.N. Malhotra."]
    },
    {
        name: "R. N. Malhotra",
        photo: "https://via.placeholder.com/150",
        appointmentDate: "4 Feb 1985",
        endDate: "22 Dec 1990",
        tenure: "5 years, 321 days",
        reforms: ["Introduced the Discount and Finance House of India (DFHI).", "Set up the National Housing Bank (NHB)."],
        monetaryPolicy: ["Introduced new money market instruments like Commercial Paper and Certificates of Deposit."],
        achievements: ["Pioneered early financial market reforms and mechanization of banking operations."],
        facts: ["Previously served as the Secretary of Finance and Executive Director at the IMF."]
    },
    {
        name: "S. Venkitaramanan",
        photo: "https://via.placeholder.com/150",
        appointmentDate: "22 Dec 1990",
        endDate: "21 Dec 1992",
        tenure: "2 years",
        reforms: ["Led the RBI during the massive 1991 balance of payments crisis.", "Initiated the first wave of financial sector reforms post-liberalization."],
        monetaryPolicy: ["Executed extreme measures including pledging RBI's gold reserves to avoid sovereign default."],
        achievements: ["Successfully steered the Indian economy away from the brink of default in 1991."],
        facts: ["His tenure witnessed a severe tightening of import financing to save foreign exchange."]
    },
    {
        name: "Dr. C. Rangarajan",
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/C._Rangarajan.jpg/220px-C._Rangarajan.jpg",
        appointmentDate: "22 Dec 1992",
        endDate: "21 Nov 1997",
        tenure: "4 years, 334 days",
        reforms: ["Dismantled the complex system of administered interest rates.", "Phased out the automatic monetization of fiscal deficits by ending ad-hoc treasury bills."],
        monetaryPolicy: ["Shifted the monetary policy framework towards market-determined exchange rates (Liberalised Exchange Rate Management System)."],
        achievements: ["Architect of India's early economic liberalization in the financial sector.", "Established the primacy of inflation control in RBI's mandate."],
        facts: ["A highly respected academic economist who reshaped the central bank's autonomy."]
    },
    {
        name: "Dr. Bimal Jalan",
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Bimal_Jalan.jpg/220px-Bimal_Jalan.jpg",
        appointmentDate: "22 Nov 1997",
        endDate: "6 Sep 2003",
        tenure: "5 years, 288 days",
        reforms: ["Introduced the Liquidity Adjustment Facility (LAF).", "Replaced the archaic FERA with the modern Foreign Exchange Management Act (FEMA)."],
        monetaryPolicy: ["Successfully managed the fallout from the Asian Financial Crisis and post-Pokhran nuclear sanctions without letting the Rupee crash."],
        achievements: ["Built up India's massive foreign exchange reserves from a position of vulnerability to absolute strength."],
        facts: ["His signature is on the Rs. 1000 note introduced in the year 2000."]
    },
    {
        name: "Dr. Y. V. Reddy",
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Yaga_Venugopal_Reddy.jpg/220px-Yaga_Venugopal_Reddy.jpg",
        appointmentDate: "6 Sep 2003",
        endDate: "5 Sep 2008",
        tenure: "4 years, 365 days",
        reforms: ["Banned banks from excessive exposure to the real estate and capital markets.", "Pioneered macro-prudential regulations long before they became a global standard."],
        monetaryPolicy: ["Aggressively increased risk weights and provisioning norms during a boom period to prevent a housing bubble."],
        achievements: ["Credited with saving the Indian banking system from the 2008 Global Financial Crisis through his conservative policies."],
        facts: ["Nobel Laureate Joseph Stiglitz praised him as the central banker who correctly saw the dangers of deregulation."]
    },
    {
        name: "Dr. D. Subbarao",
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Duvvuri_Subbarao.jpg/220px-Duvvuri_Subbarao.jpg",
        appointmentDate: "5 Sep 2008",
        endDate: "4 Sep 2013",
        tenure: "4 years, 364 days",
        reforms: ["Demystified the RBI, introducing extensive communication policies to guide market expectations.", "Deregulated savings bank interest rates."],
        monetaryPolicy: ["Managed the severe liquidity crunch post-Lehman Brothers collapse.", "Combated the double-digit inflation and 'Taper Tantrum' currency crisis of 2013."],
        achievements: ["Steered the economy through the Global Financial Crisis using unconventional monetary easing, followed by aggressive tightening to fight inflation."],
        facts: ["Wrote a critically acclaimed memoir of his time at the RBI titled 'Who Moved My Interest Rate?'."]
    },
    {
        name: "Dr. Raghuram Rajan",
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Raghuram_Rajan_2014.jpg/220px-Raghuram_Rajan_2014.jpg",
        appointmentDate: "4 Sep 2013",
        endDate: "4 Sep 2016",
        tenure: "3 years",
        reforms: ["Initiated the Asset Quality Review (AQR) forcing banks to recognize hidden bad loans (NPAs).", "Introduced new banking licenses (Payments Banks and Small Finance Banks)."],
        monetaryPolicy: ["Stabilized the tumbling Rupee during the 2013 Taper Tantrum through innovative FCNR(B) swap schemes.", "Transitioned the RBI to an inflation-targeting framework based on CPI."],
        achievements: ["Restored international confidence in the Indian economy and stabilized inflation."],
        facts: ["Famous for predicting the 2008 global financial crisis back in 2005.", "Former Chief Economist at the IMF."]
    },
    {
        name: "Dr. Urjit Patel",
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Urjit_Patel.jpg/220px-Urjit_Patel.jpg",
        appointmentDate: "4 Sep 2016",
        endDate: "10 Dec 2018",
        tenure: "2 years, 97 days",
        reforms: ["Oversaw the institutionalization of the Monetary Policy Committee (MPC).", "Steered the massive operational challenge of the 2016 Demonetization of Rs. 500 and Rs. 1000 notes."],
        monetaryPolicy: ["First Governor to operate under the newly legislated flexible inflation-targeting framework."],
        achievements: ["Successfully completed the transition to a committee-based rate-setting mechanism."],
        facts: ["Resigned abruptly citing personal reasons, following tensions with the government over RBI reserves and PCA norms."]
    },
    {
        name: "Shaktikanta Das",
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Shaktikanta_Das_Official_Portrait.jpg/220px-Shaktikanta_Das_Official_Portrait.jpg",
        appointmentDate: "12 Dec 2018",
        endDate: "Present",
        tenure: "Ongoing",
        reforms: ["Revolutionized digital payments oversight and launched the Central Bank Digital Currency (e₹) pilots.", "Resolved the crisis at Yes Bank and PMC Bank."],
        monetaryPolicy: ["Unleashed unprecedented liquidity measures and rate cuts to support the economy during the COVID-19 lockdowns.", "Managed rapid tightening to combat post-pandemic inflation."],
        achievements: ["Navigated the Indian economy through the COVID-19 pandemic and the Ukraine war shocks.", "Awarded 'Governor of the Year' by Central Banking Awards in 2023."],
        facts: ["The first non-economist bureaucrat to be appointed Governor in several decades."]
    }
];
