export const chiefElectionCommissioners = [
    {
        name: "Sukumar Sen",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Sukumar_Sen.jpg/220px-Sukumar_Sen.jpg",
        appointmentDate: "21 Mar 1950",
        endDate: "19 Dec 1958",
        tenure: "8 years, 273 days",
        reforms: ["Set up the original electoral machinery from scratch.", "Pioneered the use of distinct colored ballot boxes for different candidates due to low literacy."],
        electionsConducted: ["1951-52 General Election (First in India)", "1957 General Election"],
        achievements: ["Successfully conducted the largest democratic election in history at that time with universal adult suffrage.", "Also served as the first Chief Election Commissioner in Sudan."],
        facts: ["Awarded the Padma Bhushan in 1954."]
    },
    {
        name: "Kalyan Sundaram (K.V.K. Sundaram)",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Kalyan_Sundaram.jpg/220px-Kalyan_Sundaram.jpg",
        appointmentDate: "20 Dec 1958",
        endDate: "30 Sep 1967",
        tenure: "8 years, 284 days",
        reforms: ["Streamlined the delimitation of constituencies.", "Introduced the marking system on ballot papers instead of separate boxes."],
        electionsConducted: ["1962 General Election", "1967 General Election"],
        achievements: ["Guided the Delimitation Commission as its chairman for multiple terms.", "Helped draft the White Paper which led to the creation of the Constitution."],
        facts: ["Second longest-serving CEC in Indian history.", "Was an ICS officer who translated Sanskrit poetry to English."]
    },
    {
        name: "S. P. Sen Verma",
        portrait: "https://via.placeholder.com/150",
        appointmentDate: "1 Oct 1967",
        endDate: "30 Sep 1972",
        tenure: "5 years, 0 days",
        reforms: ["Managed the splitting of political parties and their symbol allocations.", "Improved logistics for polling booths in remote areas."],
        electionsConducted: ["1971 General Election"],
        achievements: ["Handled the historic 1971 elections post the split of the Indian National Congress.", "Ensured smooth functioning during the tense period surrounding the Indo-Pak war."],
        facts: ["His tenure witnessed the rise of Indira Gandhi's massive mandate in 1971."]
    },
    {
        name: "Dr. Nagendra Singh",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Nagendra_Singh.jpg/220px-Nagendra_Singh.jpg",
        appointmentDate: "1 Oct 1972",
        endDate: "6 Feb 1973",
        tenure: "128 days",
        reforms: ["Maintained electoral rolls in preparation for upcoming state assembly elections."],
        electionsConducted: ["Various by-elections"],
        achievements: ["Transitioned out of the role quickly to pursue a career in international law."],
        facts: ["Later served as the President of the International Court of Justice (ICJ) at The Hague.", "Born into the royal family of Dungarpur."]
    },
    {
        name: "T. Swaminathan",
        portrait: "https://via.placeholder.com/150",
        appointmentDate: "7 Feb 1973",
        endDate: "17 Jun 1977",
        tenure: "4 years, 130 days",
        reforms: ["Prepared the electoral machinery for the critical post-Emergency elections.", "Navigated symbol disputes during the Emergency."],
        electionsConducted: ["1977 General Election"],
        achievements: ["Successfully conducted the 1977 elections which led to the first non-Congress government at the Centre.", "Ensured electoral integrity immediately after the lifting of the Emergency."],
        facts: ["Previously served as the Cabinet Secretary of India."]
    },
    {
        name: "S. L. Shakdhar",
        portrait: "https://via.placeholder.com/150",
        appointmentDate: "18 Jun 1977",
        endDate: "17 Jun 1982",
        tenure: "5 years, 0 days",
        reforms: ["Proposed the introduction of voter identity cards.", "Initiated discussions on state funding of elections to curb money power."],
        electionsConducted: ["1980 General Election"],
        achievements: ["Oversaw the return of Indira Gandhi to power in 1980.", "Known as an authority on parliamentary procedures and co-authored 'Practice and Procedure of Parliament'."],
        facts: ["Previously served as the Secretary-General of the Lok Sabha."]
    },
    {
        name: "R. K. Trivedi",
        portrait: "https://via.placeholder.com/150",
        appointmentDate: "18 Jun 1982",
        endDate: "31 Dec 1985",
        tenure: "3 years, 196 days",
        reforms: ["Pushed for the computerization of electoral rolls.", "Advocated for stronger anti-defection laws (which culminated in the 10th Schedule)."],
        electionsConducted: ["1984 General Election"],
        achievements: ["Conducted the massive 1984 elections smoothly following the assassination of PM Indira Gandhi.", "Implemented early technological modernization in the ECI."],
        facts: ["Also served as the Governor of Gujarat."]
    },
    {
        name: "R. V. S. Peri Sastri",
        portrait: "https://via.placeholder.com/150",
        appointmentDate: "1 Jan 1986",
        endDate: "25 Nov 1990",
        tenure: "4 years, 328 days",
        reforms: ["Introduced the use of Electronic Voting Machines (EVMs) in experimental phases (1989).", "Oversaw the reduction of the voting age from 21 to 18 years (61st Amendment)."],
        electionsConducted: ["1989 General Election"],
        achievements: ["Steered the Commission during the transition to a multi-member body (briefly in 1989 before returning to a single-member)."],
        facts: ["During his tenure, the Election Commission was made a multi-member body for the first time by the Rajiv Gandhi government, a move that was highly controversial."]
    },
    {
        name: "V. S. Ramadevi",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/V_S_Ramadevi.jpg/220px-V_S_Ramadevi.jpg",
        appointmentDate: "26 Nov 1990",
        endDate: "11 Dec 1990",
        tenure: "16 days",
        reforms: ["Maintained institutional stability during a brief transitional period."],
        electionsConducted: ["None at the national level"],
        achievements: ["Broke the glass ceiling at the highest level of India's electoral machinery."],
        facts: ["The first and only woman to serve as Chief Election Commissioner of India.", "Also served as the Governor of Karnataka and Himachal Pradesh."]
    },
    {
        name: "T. N. Seshan",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/T.N.Seshan_pic.jpg/220px-T.N.Seshan_pic.jpg",
        appointmentDate: "12 Dec 1990",
        endDate: "11 Dec 1996",
        tenure: "6 years, 0 days",
        reforms: ["Strict enforcement of the Model Code of Conduct.", "Introduced Voter ID cards (EPIC).", "Cracked down on electoral malpractices like booth capturing, bribery, and use of loud speakers without permission."],
        electionsConducted: ["1991 General Election", "1996 General Election"],
        achievements: ["Fundamentally altered the perception of the Election Commission, transforming it into a fiercely independent and powerful institution.", "Won the Ramon Magsaysay Award for Government Service in 1996."],
        facts: ["Famous quote: 'I eat politicians for breakfast.'", "Under his tenure, the ECI became a permanently multi-member body in 1993."]
    },
    {
        name: "M. S. Gill",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/M.S._Gill.jpg/220px-M.S._Gill.jpg",
        appointmentDate: "12 Dec 1996",
        endDate: "13 Jun 2001",
        tenure: "4 years, 183 days",
        reforms: ["Massive push for the nationwide deployment of Electronic Voting Machines (EVMs).", "Enhanced the computerization of the Election Commission."],
        electionsConducted: ["1998 General Election", "1999 General Election"],
        achievements: ["Successfully guided the EC through an era of extreme political instability and frequent mid-term polls.", "Awarded the Padma Vibhushan in 2000."],
        facts: ["Later joined politics and served as a Union Minister in the UPA government.", "Was the first CEC to succeed T.N. Seshan after the intense power struggles between the CEC and Election Commissioners."]
    },
    {
        name: "J. M. Lyngdoh",
        portrait: "https://via.placeholder.com/150",
        appointmentDate: "14 Jun 2001",
        endDate: "7 Feb 2004",
        tenure: "2 years, 238 days",
        reforms: ["Pushed for the criminal background disclosure of candidates (following a Supreme Court order).", "Strict enforcement of electoral rules during tense state elections."],
        electionsConducted: ["Various state assembly elections including J&K and Gujarat."],
        achievements: ["Conducted the highly sensitive 2002 Jammu & Kashmir assembly elections fairly, defying militant threats.", "Won the Ramon Magsaysay Award in 2003 for Government Service."],
        facts: ["Clashed heavily with the Gujarat state government over the timing of assembly elections following the 2002 riots."]
    },
    {
        name: "T. S. Krishnamurthy",
        portrait: "https://via.placeholder.com/150",
        appointmentDate: "8 Feb 2004",
        endDate: "15 May 2005",
        tenure: "1 year, 96 days",
        reforms: ["First to use EVMs universally across all polling booths in a general election.", "Proposed state funding of elections and banning candidates with criminal charges."],
        electionsConducted: ["2004 General Election"],
        achievements: ["Smoothly conducted the 2004 elections where EVMs completely replaced paper ballots for the first time nationally."],
        facts: ["The first Indian Revenue Service (IRS) officer to become CEC; all predecessors were from the IAS or ICS."]
    },
    {
        name: "B. B. Tandon",
        portrait: "https://via.placeholder.com/150",
        appointmentDate: "16 May 2005",
        endDate: "29 Jun 2006",
        tenure: "1 year, 44 days",
        reforms: ["Enhanced the transparency of the electoral roll revision process.", "Initiated the concept of vulnerability mapping of polling stations."],
        electionsConducted: ["Various crucial state assembly elections, notably in Bihar."],
        achievements: ["Handled the complex situation in Bihar when elections were held twice in 2005 to break a hung assembly."],
        facts: ["Oversaw a period of relative calm and consolidation of the EVM technology."]
    },
    {
        name: "N. Gopalaswami",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/N_Gopalaswami.jpg/220px-N_Gopalaswami.jpg",
        appointmentDate: "30 Jun 2006",
        endDate: "20 Apr 2009",
        tenure: "2 years, 294 days",
        reforms: ["Introduced Braille signage on EVMs for the visually impaired.", "Pushed for photo electoral rolls."],
        electionsConducted: ["Phase 1 of 2009 General Election", "Various state elections"],
        achievements: ["Began the mammoth task of preparing for the 2009 general elections.", "Awarded the Padma Bhushan in 2015."],
        facts: ["Caused a major constitutional controversy by formally recommending the removal of fellow Election Commissioner Navin Chawla to the President (which was rejected)."]
    },
    {
        name: "Navin Chawla",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Navin_Chawla.jpg/220px-Navin_Chawla.jpg",
        appointmentDate: "21 Apr 2009",
        endDate: "29 Jul 2010",
        tenure: "1 year, 99 days",
        reforms: ["Focused on the inclusion of marginalized sections like lepers and the homeless in the electoral roll.", "Introduced the concept of 'voter slips' distributed by the ECI."],
        electionsConducted: ["2009 General Election"],
        achievements: ["Successfully conducted the 2009 General Elections, which were widely praised for their logistical execution."],
        facts: ["A well-known author who wrote the authorized biography of Mother Teresa."]
    },
    {
        name: "S. Y. Quraishi",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Dr._S._Y._Quraishi.jpg/220px-Dr._S._Y._Quraishi.jpg",
        appointmentDate: "30 Jul 2010",
        endDate: "10 Jun 2012",
        tenure: "1 year, 316 days",
        reforms: ["Established the Expenditure Monitoring Division to tackle 'money power' in elections.", "Founded the India International Institute of Democracy and Election Management (IIIDEM).", "Introduced National Voters' Day."],
        electionsConducted: ["Numerous crucial state elections including UP and Tamil Nadu."],
        achievements: ["Brought an unprecedented focus on voter education and participation (SVEEP)."],
        facts: ["First Muslim to serve as the Chief Election Commissioner.", "Authored the book 'An Undocumented Wonder: The Making of the Great Indian Election'."]
    },
    {
        name: "V. S. Sampath",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/V._S._Sampath.jpg/220px-V._S._Sampath.jpg",
        appointmentDate: "11 Jun 2012",
        endDate: "15 Jan 2015",
        tenure: "2 years, 218 days",
        reforms: ["Oversaw the introduction of the NOTA (None of the Above) option on EVMs following a Supreme Court directive.", "Piloted the VVPAT (Voter Verifiable Paper Audit Trail) system."],
        electionsConducted: ["2014 General Election"],
        achievements: ["Conducted the 2014 general elections with a record voter turnout of 66.4%."],
        facts: ["Dealt with the complex bifurcation of Andhra Pradesh and the subsequent electoral logistics."]
    },
    {
        name: "H. S. Brahma",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/H_S_Brahma_2015.jpg/220px-H_S_Brahma_2015.jpg",
        appointmentDate: "16 Jan 2015",
        endDate: "18 Apr 2015",
        tenure: "92 days",
        reforms: ["Pushed for the linking of Aadhaar cards with Voter IDs to eliminate duplicates (National Electoral Roll Purification and Authentication Programme - NERPAP)."],
        electionsConducted: ["2015 Delhi Assembly Election"],
        achievements: ["Initiated major database cleanup drives.", "Second CEC from Northeast India (after J.M. Lyngdoh)."],
        facts: ["His tenure was very brief due to hitting the mandatory retirement age of 65."]
    },
    {
        name: "Nasim Zaidi",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Dr._Nasim_Zaidi.jpg/220px-Dr._Nasim_Zaidi.jpg",
        appointmentDate: "19 Apr 2015",
        endDate: "5 Jul 2017",
        tenure: "2 years, 77 days",
        reforms: ["Aggressively expanded the use of VVPAT machines in all state elections.", "Introduced IT initiatives like the Suvidha and Samadhan portals for candidates and voters."],
        electionsConducted: ["Various state elections including UP (2017) and Bihar (2015)."],
        achievements: ["Defended the integrity of EVMs by organizing a 'hackathon' open challenge to political parties."],
        facts: ["Held a PhD in Biochemistry before joining the IAS.", "Also served as the Director General of Civil Aviation."]
    },
    {
        name: "A. K. Joti",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Achal_Kumar_Jyoti.jpg/220px-Achal_Kumar_Jyoti.jpg",
        appointmentDate: "6 Jul 2017",
        endDate: "22 Jan 2018",
        tenure: "200 days",
        reforms: ["Mandated VVPATs in all booths for the Gujarat and Himachal Pradesh assembly elections for the first time."],
        electionsConducted: ["2017 Gujarat and Himachal Pradesh Assembly Elections"],
        achievements: ["Successfully scaled up the logistics for 100% VVPAT deployment in state elections."],
        facts: ["Faced criticism from the opposition regarding the delay in announcing the Gujarat election dates."]
    },
    {
        name: "Om Prakash Rawat",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/O.P._Rawat.jpg/220px-O.P._Rawat.jpg",
        appointmentDate: "23 Jan 2018",
        endDate: "1 Dec 2018",
        tenure: "312 days",
        reforms: ["Introduced the cVIGIL app for citizens to report Model Code of Conduct violations directly to the ECI.", "Tightened rules around paid news and social media monitoring."],
        electionsConducted: ["Crucial state elections including Karnataka, MP, and Rajasthan."],
        achievements: ["Pioneered the integration of technology in direct citizen oversight of elections."],
        facts: ["Served extensively in Madhya Pradesh and received the Prime Minister's Award for Excellence in Public Administration in 2010."]
    },
    {
        name: "Sunil Arora",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Sunil_Arora.jpg/220px-Sunil_Arora.jpg",
        appointmentDate: "2 Dec 2018",
        endDate: "12 Apr 2021",
        tenure: "2 years, 131 days",
        reforms: ["Implemented postal ballots for senior citizens (80+) and PwDs.", "Navigated election protocols during the COVID-19 pandemic."],
        electionsConducted: ["2019 General Election", "2020 Bihar Assembly Election"],
        achievements: ["Conducted the massive 2019 General Elections with the highest ever voter turnout.", "Conducted the world's first major election (Bihar) amid the COVID-19 pandemic with stringent safety protocols."],
        facts: ["Also served as the Chairman of the Association of World Election Bodies (A-WEB)."]
    },
    {
        name: "Sushil Chandra",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Sushil_Chandra_Official_Portrait.jpg/220px-Sushil_Chandra_Official_Portrait.jpg",
        appointmentDate: "13 Apr 2021",
        endDate: "14 May 2022",
        tenure: "1 year, 31 days",
        reforms: ["Furthered the digitization of electoral services through the Voter Portal.", "Pushed for multiple qualifying dates in a year for youth to enroll as voters (Amendment to RP Act)."],
        electionsConducted: ["2022 State Elections (UP, Punjab, Goa, Uttarakhand, Manipur)"],
        achievements: ["Managed massive multi-phase elections during the later waves of the COVID-19 pandemic.", "Clamped down heavily on illegal cash seizures during elections."],
        facts: ["The second IRS officer (after T.S. Krishnamurthy) to become CEC.", "Previously served as the Chairman of the Central Board of Direct Taxes (CBDT)."]
    },
    {
        name: "Rajiv Kumar",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Rajiv_Kumar_Chief_Election_Commissioner.jpg/220px-Rajiv_Kumar_Chief_Election_Commissioner.jpg",
        appointmentDate: "15 May 2022",
        endDate: "Present",
        tenure: "Ongoing",
        reforms: ["Focusing on curbing deepfakes and misinformation on social media.", "Enhancing voter turnout in urban centers (tackling urban apathy)."],
        electionsConducted: ["2024 General Election", "Various State Elections"],
        achievements: ["Oversaw the 2024 General Elections, managing a 900+ million electorate with unprecedented transparency initiatives."],
        facts: ["An avid trekker who visited remote polling booths in the Himalayas to ensure last-mile electoral connectivity."]
    }
];
