
document.addEventListener("DOMContentLoaded", () => {
  const facts = [{"label": "Height", "value": "7,355 m", "detail": "A major high-altitude summit of the central Garhwal Himalayas."}, {"label": "State", "value": "Uttarakhand", "detail": "Mostly associated with Chamoli district in Uttarakhand, near the Indo-Tibetan border region."}, {"label": "Range", "value": "Garhwal Himalayas", "detail": "Often described near Kamet and the upper Alaknanda–Dhauli watershed."}, {"label": "First ascent", "value": "1950", "detail": "First ascent is credited to an Anglo-Swiss team including R. Dittert, A. Tissières, and G. Chevalley."}, {"label": "Nearby peak", "value": "Kamet", "detail": "Abi Gamin lies close to Kamet, one of the best-known high peaks of the Garhwal Himalayas."}, {"label": "Route nature", "value": "Glacier / snow climb", "detail": "High-altitude climbing involves snow, ice, glacier travel, weather windows, and acclimatisation."}];
  const timeline = [{"year": "1855", "title": "Early high-altitude attempt", "text": "The Schlagintweit brothers explored the Kamet/Abi Gamin area and reached a remarkable height for the period."}, {"year": "1950", "title": "First ascent", "text": "Abi Gamin was first climbed by an Anglo-Swiss party, marking an important moment in Garhwal mountaineering history."}, {"year": "1955", "title": "Indian mountaineering milestone", "text": "Indian expeditions in the Kamet–Abi Gamin area strengthened the region’s place in Indian climbing history."}, {"year": "Modern era", "title": "Training and expedition peak", "text": "Abi Gamin continues to appear in high-altitude expedition planning and mountaineering preparation routes."}];
  const gallery = [{"title": "Garhwal snow wall", "image": "../../assets/travel_mountains.png", "caption": "High Himalayan terrain, glaciers, and steep snow slopes."}, {"title": "Approach valley", "image": "../../assets/travel_hidden.png", "caption": "Remote valleys and passes shape the expedition approach."}, {"title": "Alpine camp", "image": "../../assets/hero_banner.png", "caption": "Climbers depend on staged camps, weather windows, and acclimatisation."}, {"title": "Ridge route", "image": "../../assets/travel_mountains.png", "caption": "The summit push demands careful snow and ridge movement."}];
  const escapeHtml = (value) => String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;");
  document.getElementById("facts-grid").innerHTML = facts.map((fact) => `<article class="fact-card"><span>${escapeHtml(fact.label)}</span><strong>${escapeHtml(fact.value)}</strong><p>${escapeHtml(fact.detail)}</p></article>`).join("");
  document.getElementById("timeline").innerHTML = timeline.map((item) => `<article class="timeline-item"><span>${escapeHtml(item.year)}</span><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.text)}</p></article>`).join("");
  document.getElementById("gallery-grid").innerHTML = gallery.map((item) => `<article class="gallery-card"><img src="${escapeHtml(item.image)}" alt="${escapeHtml(item.title)}" onerror="this.src='../../assets/hero_banner.png'"><div><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.caption)}</p></div></article>`).join("");
  window.AbiGaminMountainPage = { facts: () => [...facts], timeline: () => [...timeline] };
});
