/**
 * Forgotten Women of Indian History — Data Module
 * Digital Archive covering 50 pioneering and historically significant Indian women across
 * Ancient, Early Medieval, Medieval, Colonial, Freedom Struggle, and Post-Independence eras.
 */

const ERAS = [
    { id: "all", label: "All Eras" },
    { id: "ancient", label: "Ancient India (c. 1500 BCE – 600 CE)" },
    { id: "early-medieval", label: "Early Medieval India (c. 600 – 1200 CE)" },
    { id: "medieval", label: "Medieval India (c. 1200 – 1750 CE)" },
    { id: "colonial", label: "Colonial India (c. 1750 – 1900 CE)" },
    { id: "freedom-struggle", label: "Freedom Struggle (c. 1900 – 1947 CE)" },
    { id: "post-independence", label: "Post-Independence India (1947 CE+)" }
];

const CATEGORIES = [
    { id: "all", label: "All Categories", icon: "✨" },
    { id: "queens-rulers", label: "Queens & Rulers", icon: "👑" },
    { id: "warriors", label: "Warriors & Military Leaders", icon: "⚔️" },
    { id: "freedom-fighters", label: "Freedom Fighters", icon: "🇮🇳" },
    { id: "philosophers", label: "Philosophers & Scholars", icon: "📜" },
    { id: "scientists", label: "Scientists & Botanists", icon: "🔬" },
    { id: "doctors", label: "Doctors & Medical Pioneers", icon: "🩺" },
    { id: "writers", label: "Writers & Poets", icon: "✍️" },
    { id: "artists", label: "Artists & Performers", icon: "🎨" },
    { id: "social-reformers", label: "Social Reformers & Educators", icon: "⚖️" }
];

const WOMEN_PROFILES = [
    // --- Ancient Era ---
    {
        id: "gargi-vachaknavi",
        name: "Gargi Vachaknavi",
        era: "ancient",
        eraLabel: "c. 8th–7th Century BCE",
        region: "Mithila (Bihar)",
        category: "philosophers",
        contribution: "Challenged Sage Yajnavalkya on the nature of reality in King Janaka's philosophical congress.",
        bio: "Celebrated ancient Vedic philosopher and brahmavadini who debated the cosmos and supreme reality in the Brihadaranyaka Upanishad.",
        dynasty: "Videha Kingdom",
        featured: true,
        icon: "📜",
        mapCoords: { lat: 26.1, lng: 85.9 }
    },
    {
        id: "maitreyi",
        name: "Maitreyi",
        era: "ancient",
        eraLabel: "c. 8th Century BCE",
        region: "Mithila / Vedic Aryavarta",
        category: "philosophers",
        contribution: "Famous dialogue on immortality, self-knowledge (Atman), and true wealth in the Upanishads.",
        bio: "Vedic philosopher who chose the pursuit of spiritual wisdom and immortality over material riches.",
        dynasty: "Vedic Period",
        featured: true,
        icon: "🕉️",
        mapCoords: { lat: 25.6, lng: 85.1 }
    },
    {
        id: "lopamudra",
        name: "Lopamudra",
        era: "ancient",
        eraLabel: "c. 1500–1000 BCE",
        region: "Vidarbha (Maharashtra)",
        category: "philosophers",
        contribution: "Vedic rishika and hymn composer in the Rigveda; co-founder of the Panchadasi Lalita tradition.",
        bio: "Scholar-philosopher celebrated in Vedic hymns and the Mahabharata for her philosophical mastery.",
        dynasty: "Vedic Period",
        featured: false,
        icon: "📜",
        mapCoords: { lat: 21.1, lng: 79.0 }
    },
    {
        id: "prabhavatigupta",
        name: "Prabhavatigupta",
        era: "ancient",
        eraLabel: "c. 385 – 405 CE",
        region: "Nagpur / Vidarbha (Maharashtra)",
        category: "queens-rulers",
        contribution: "Daughter of Chandragupta II; served as sovereign regent of the Vakataka Dynasty for over two decades.",
        bio: "One of ancient India's most powerful queens whose copper plate charters demonstrate exceptional statecraft.",
        dynasty: "Vakataka & Gupta Dynasties",
        featured: false,
        icon: "👑",
        mapCoords: { lat: 21.2, lng: 79.1 }
    },
    {
        id: "sanghamitta",
        name: "Sanghamitta",
        era: "ancient",
        eraLabel: "c. 3rd Century BCE",
        region: "Pataliputra (Bihar) & Sri Lanka",
        category: "philosophers",
        contribution: "Daughter of Emperor Ashoka; established the Buddhist Bhikkhuni order and planted the Bodhi Tree in Sri Lanka.",
        bio: "Pioneering spiritual diplomat who established female monasticism across South Asia.",
        dynasty: "Maurya Dynasty",
        featured: false,
        icon: "🌱",
        mapCoords: { lat: 25.6, lng: 85.1 }
    },
    {
        id: "avvaiyar",
        name: "Avvaiyar",
        era: "ancient",
        eraLabel: "c. 1st–3rd Century CE",
        region: "Tamil Nadu",
        category: "writers",
        contribution: "Legendary Sangam poet, royal diplomat, and philosopher respected across Chera, Chola, and Pandya courts.",
        bio: "Emvered Tamil poet whose ethical verses in Aathichoodi continue to teach foundational ethics.",
        dynasty: "Sangam Era",
        featured: false,
        icon: "✍️",
        mapCoords: { lat: 9.9, lng: 78.1 }
    },

    // --- Early Medieval Era ---
    {
        id: "queen-diddi",
        name: "Queen Didda",
        era: "early-medieval",
        eraLabel: "958 – 1003 CE",
        region: "Kashmir",
        category: "queens-rulers",
        contribution: "Ruled Kashmir for nearly five decades with iron political willpower and administrative mastery.",
        bio: "Celebrated in Kalhana's Rajatarangini for consolidating power, subduing feudal revolts, and stabilizing Kashmir.",
        dynasty: "Utpala & Lohara Dynasties",
        featured: false,
        icon: "👑",
        mapCoords: { lat: 34.0, lng: 74.8 }
    },
    {
        id: "akkadevi",
        name: "Akkadevi",
        era: "early-medieval",
        eraLabel: "1010 – 1064 CE",
        region: "Kalyani (Karnataka)",
        category: "warriors",
        contribution: "Chalukya princess and provincial governor known as 'Gunadabedangi' (beauty of virtues) who commanded troops.",
        bio: "Warrior administrator who besieged enemy forts and patronized Jaina and Hindu educational institutions.",
        dynasty: "Western Chalukya Dynasty",
        featured: false,
        icon: "⚔️",
        mapCoords: { lat: 17.8, lng: 76.9 }
    },
    {
        id: "rudrama-devi",
        name: "Rani Rudrama Devi",
        era: "early-medieval",
        eraLabel: "1262 – 1289 CE",
        region: "Warangal (Telangana)",
        category: "queens-rulers",
        contribution: "Monarch of the Kakatiya Dynasty who defended the Deccan against Yadavas and Pandyas; praised by Marco Polo.",
        bio: "Defied gender norms, adopted the male regnal name Rudradeva, constructed Warangal's stone fort, and created an invincible military.",
        dynasty: "Kakatiya Dynasty",
        featured: true,
        icon: "👑",
        mapCoords: { lat: 17.9, lng: 79.5 }
    },
    {
        id: "kundavai-pirattiyar",
        name: "Kundavai Pirattiyar",
        era: "early-medieval",
        eraLabel: "c. 941 – 1018 CE",
        region: "Thanjavur (Tamil Nadu)",
        category: "queens-rulers",
        contribution: "Elder sister and chief advisor to Rajaraja Chola I; master of diplomacy, public hospitals, and temples.",
        bio: "Political mastermind behind the golden age of the Imperial Cholas, establishing free hospitals and temples across South India.",
        dynasty: "Chola Dynasty",
        featured: false,
        icon: "🏛️",
        mapCoords: { lat: 10.7, lng: 79.1 }
    },
    {
        id: "sugandha-of-kashmir",
        name: "Queen Sugandha",
        era: "early-medieval",
        eraLabel: "904 – 906 CE",
        region: "Kashmir",
        category: "queens-rulers",
        contribution: "Sovereign ruler of Kashmir of the Utpala dynasty who founded the towns of Sugandhapura and Gopalapura.",
        bio: "Adept ruler who attempted to restore stable central monarchy against factional military oligarchs.",
        dynasty: "Utpala Dynasty",
        featured: false,
        icon: "👑",
        mapCoords: { lat: 34.1, lng: 74.9 }
    },

    // --- Medieval Era ---
    {
        id: "rani-durgavati",
        name: "Rani Durgavati",
        era: "medieval",
        eraLabel: "1524 – 1564 CE",
        region: "Garha-Mandla / Gondwana (Madhya Pradesh)",
        category: "warriors",
        contribution: "Chandel-Gond warrior queen who expanded Gondwana and fought valiantly to the death against Mughal invasion.",
        bio: "Built public reservoirs, patronized learning, and led her cavalry in armor into battle at Narrai against Asaf Khan.",
        dynasty: "Gond Dynasty",
        featured: true,
        icon: "⚔️",
        mapCoords: { lat: 23.1, lng: 79.9 }
    },
    {
        id: "abbakka-chowta",
        name: "Rani Abbakka Chowta I",
        era: "medieval",
        eraLabel: "c. 1525 – 1570s CE",
        region: "Ullal / Coastal Karnataka",
        category: "warriors",
        contribution: "Known as 'Abhaya Rani'; repelled six major Portuguese naval invasions of the Malabar/Kanara coast.",
        bio: "Pioneering anti-colonial freedom fighter who forged inter-religious alliances with Zamorin and Moplahs against Portuguese colonialists.",
        dynasty: "Chowta Dynasty",
        featured: true,
        icon: "⚓",
        mapCoords: { lat: 12.8, lng: 74.8 }
    },
    {
        id: "chand-bibi",
        url: "../chand-bibi-explorer/",
        name: "Chand Bibi",
        era: "medieval",
        eraLabel: "1550 – 1599 CE",
        region: "Ahmadnagar & Bijapur (Maharashtra/Karnataka)",
        category: "queens-rulers",
        contribution: "Regent of Bijapur and Ahmadnagar who defended Ahmadnagar Fort against Mughal Prince Murad's imperial siege.",
        bio: "Polyglot scholar, diplomat, and warrior who united Deccan Sultanates and personally directed artillery counter-mines.",
        dynasty: "Nizam Shahi & Adil Shahi Dynasties",
        featured: true,
        icon: "🛡️",
        mapCoords: { lat: 19.1, lng: 74.7 }
    },
    {
        id: "keladi-chennamma",
        name: "Keladi Chennamma",
        era: "medieval",
        eraLabel: "1671 – 1696 CE",
        region: "Bednore / Malenadu (Karnataka)",
        category: "queens-rulers",
        contribution: "Protected Chhatrapati Rajaram and defeated Mughal Emperor Aurangzeb's invading armies in the Western Ghats.",
        bio: "Courageous Lingayat monarch who preserved regional sovereignty, spice trade, and religious pluralism.",
        dynasty: "Keladi Nayaka Dynasty",
        featured: true,
        icon: "👑",
        mapCoords: { lat: 14.0, lng: 75.0 }
    },
    {
        id: "tarabai-bhonsle",
        url: "../tarabai-maratha-regent-explorer/",
        name: "Maharani Tarabai",
        era: "medieval",
        eraLabel: "1675 – 1761 CE",
        region: "Kolhapur / Maratha Empire (Maharashtra)",
        category: "warriors",
        contribution: "Led the Maratha war of resistance against Mughal Emperor Aurangzeb following Rajaram's demise (1700–1707).",
        bio: "Master of mobile cavalry warfare and fort sieges whose leadership kept the Maratha Empire alive and expanding.",
        dynasty: "Maratha Empire",
        featured: true,
        icon: "🚩",
        mapCoords: { lat: 16.7, lng: 74.2 }
    },
    {
        id: "ahilyabai-holkar",
        url: "../ahilyabai-holkar-explorer/",
        name: "Ahilyabai Holkar",
        era: "medieval",
        eraLabel: "1725 – 1795 CE",
        region: "Maheshwar / Malwa (Madhya Pradesh)",
        category: "queens-rulers",
        contribution: "Philosopher Queen of Malwa; rebuilt Kashi Vishwanath, Somnath, and Gaya, and fostered Maheshwari handlooms.",
        bio: "Renowned across India for ethical administration, open Darbars, agrarian welfare, and massive pan-Indian temple restorations.",
        dynasty: "Holkar Dynasty",
        featured: true,
        icon: "⚖️",
        mapCoords: { lat: 22.1, lng: 75.5 }
    },
    {
        id: "gangadevi",
        name: "Gangadevi",
        era: "medieval",
        eraLabel: "c. 14th Century CE",
        region: "Vijayanagara (Karnataka)",
        category: "writers",
        contribution: "Authored the classical Sanskrit epic 'Madhura Vijayam' documenting Prince Kumara Kampana's southern campaign.",
        bio: "Warrior princess and eminent Sanskrit poet whose firsthand chronicles remain vital historical sources.",
        dynasty: "Vijayanagara Empire",
        featured: false,
        icon: "✍️",
        mapCoords: { lat: 15.3, lng: 76.4 }
    },
    {
        id: "mirabai",
        name: "Mirabai",
        era: "medieval",
        eraLabel: "1498 – 1546 CE",
        region: "Mewar (Rajasthan)",
        category: "artists",
        contribution: "Bhakti saint and poet whose impassioned devotional bhajans redefined Indian spiritual music and literature.",
        bio: "Rajput princess who rejected patriarchal royal constraints in total devotion to Lord Krishna.",
        dynasty: "Rathore & Sisodia Dynasties",
        featured: false,
        icon: "🎵",
        mapCoords: { lat: 24.8, lng: 74.6 }
    },
    {
        id: "habba-khatoon",
        name: "Habba Khatoon",
        era: "medieval",
        eraLabel: "1554 – 1609 CE",
        region: "Kashmir",
        category: "writers",
        contribution: "Known as 'Nightingale of Kashmir' (Zoon); introduced the lol lyric to Kashmiri literature.",
        bio: "Peasant girl who became Queen consort of Yusuf Shah Chak and composed poignant verses of love and exile.",
        dynasty: "Chak Dynasty",
        featured: false,
        icon: "✍️",
        mapCoords: { lat: 34.0, lng: 74.8 }
    },

    // --- Colonial Era ---
    {
        id: "velu-nachiyar",
        url: "../velu-nachiyar-explorer/",
        name: "Rani Velu Nachiyar",
        era: "colonial",
        eraLabel: "1730 – 1796 CE",
        region: "Sivaganga (Tamil Nadu)",
        category: "warriors",
        contribution: "First Indian queen to wage armed war against the British East India Company; reconquered Sivaganga in 1780.",
        bio: "Known as 'Veeramangai' (Brave Woman); formed an alliance with Hyder Ali and deployed the world's first recorded suicide bomber (Kuyili).",
        dynasty: "Sivaganga Kingdom",
        featured: true,
        icon: "⚔️",
        mapCoords: { lat: 9.8, lng: 78.4 }
    },
    {
        id: "kuyili",
        name: "Kuyili",
        era: "colonial",
        eraLabel: "c. 1760 – 1780 CE",
        region: "Sivaganga (Tamil Nadu)",
        category: "warriors",
        contribution: "Commander of Velu Nachiyar's women's army (Udaiyaal); blew up British ammunition depot by setting herself ablaze.",
        bio: "Dalit commander and supreme martyr whose ultimate sacrifice enabled the recapture of Sivaganga Kingdom.",
        dynasty: "Sivaganga Kingdom",
        featured: false,
        icon: "🔥",
        mapCoords: { lat: 9.8, lng: 78.4 }
    },
    {
        id: "kittur-chennamma",
        name: "Rani Kittur Chennamma",
        era: "colonial",
        eraLabel: "1778 – 1829 CE",
        region: "Kittur (Karnataka)",
        category: "warriors",
        contribution: "Led an armed rebellion against the British East India Company in 1824 against the Doctrine of Lapse.",
        bio: "Defeated the British forces in the first battle at Kittur, killing British collector Thackeray; immortalized in Kannada folklore.",
        dynasty: "Kittur Kingdom",
        featured: true,
        icon: "⚔️",
        mapCoords: { lat: 15.6, lng: 74.7 }
    },
    {
        id: "rani-lakshmibai",
        url: "../rani-lakshmibai-explorer/",
        name: "Rani Lakshmibai",
        era: "colonial",
        eraLabel: "1828 – 1858 CE",
        region: "Jhansi (Uttar Pradesh)",
        category: "freedom-fighters",
        contribution: "Iconic military leader and symbol of resistance in the Indian Revolt of 1857.",
        bio: "Fought fearlessly on horseback commanding cavalry during the defense of Jhansi, Kalpi, and Gwalior.",
        dynasty: "Maratha Kingdom of Jhansi",
        featured: true,
        icon: "⚔️",
        mapCoords: { lat: 25.4, lng: 78.5 }
    },
    {
        id: "begum-hazrat-mahal",
        url: "../begum-hazrat-mahal-explorer/",
        name: "Begum Hazrat Mahal",
        era: "colonial",
        eraLabel: "1820 – 1879 CE",
        region: "Awadh / Lucknow (Uttar Pradesh)",
        category: "freedom-fighters",
        contribution: "Seized Lucknow during 1857 Revolt, crowned son Birjis Qadr, and led united resistance against British annexation.",
        bio: "Refused British pensions and amnesty, issuing a counter-proclamation against Queen Victoria.",
        dynasty: "Nawabs of Awadh",
        featured: true,
        icon: "👑",
        mapCoords: { lat: 26.8, lng: 80.9 }
    },
    {
        id: "jhalkaribai",
        name: "Jhalkaribai",
        era: "colonial",
        eraLabel: "1830 – 1858 CE",
        region: "Jhansi (Uttar Pradesh)",
        category: "warriors",
        contribution: "Commander in the Durga Dal; disguised herself as Rani Lakshmibai to allow the Queen to escape Jhansi fort.",
        bio: "Koli warrior whose supreme courage and tactical deception saved the Jhansi leadership during the British siege.",
        dynasty: "Kingdom of Jhansi",
        featured: false,
        icon: "🛡️",
        mapCoords: { lat: 25.4, lng: 78.5 }
    },
    {
        id: "savitribai-phule",
        name: "Savitribai Phule",
        era: "colonial",
        eraLabel: "1831 – 1897 CE",
        region: "Pune (Maharashtra)",
        category: "social-reformers",
        contribution: "India's first female teacher; established the first school for girls at Bhide Wada (Pune) in 1848.",
        bio: "Trailblazing social reformer, poet, and crusader against casteism, female infanticide, and untouchability.",
        dynasty: "Satyashodhak Samaj",
        featured: true,
        icon: "📚",
        mapCoords: { lat: 18.5, lng: 73.8 }
    },
    {
        id: "fatima-sheikh",
        name: "Fatima Sheikh",
        era: "colonial",
        eraLabel: "1831 – 1900 CE",
        region: "Pune (Maharashtra)",
        category: "social-reformers",
        contribution: "India's first Muslim woman teacher; co-founded and taught in girls' schools alongside Savitribai Phule.",
        bio: "Provided refuge in her own home to Jyotirao and Savitribai Phule to run schools for marginalized girls and Dalits.",
        dynasty: "Social Reform Movement",
        featured: false,
        icon: "📖",
        mapCoords: { lat: 18.5, lng: 73.8 }
    },
    {
        id: "tarabai-shinde",
        name: "Tarabai Shinde",
        era: "colonial",
        eraLabel: "1850 – 1910 CE",
        region: "Buldhana (Maharashtra)",
        category: "writers",
        contribution: "Published 'Stri Purush Tulana' (A Comparison Between Women and Men) in 1882, India's first modern feminist text.",
        bio: "Radical social critic who challenged patriarchal hypocrisy, double standards, and caste-based oppression.",
        dynasty: "Satyashodhak Movement",
        featured: false,
        icon: "✍️",
        mapCoords: { lat: 20.5, lng: 76.1 }
    },
    {
        id: "pandita-ramabai",
        name: "Pandita Ramabai",
        era: "colonial",
        eraLabel: "1858 – 1922 CE",
        region: "Pune (Maharashtra)",
        category: "social-reformers",
        contribution: "Sanskrit scholar, social reformer, and founder of the Mukti Mission and Sharada Sadan for widows.",
        bio: "First woman accorded the titles of 'Pandita' and 'Saraswati' by Calcutta University for Sanskrit erudition.",
        dynasty: "Social Reform Movement",
        featured: false,
        icon: "🕊️",
        mapCoords: { lat: 18.5, lng: 73.8 }
    },
    {
        id: "anandibai-joshi",
        name: "Dr. Anandibai Joshi",
        era: "colonial",
        eraLabel: "1865 – 1887 CE",
        region: "Kalyan (Maharashtra) & USA",
        category: "doctors",
        contribution: "First Indian female physician to earn a degree in Western medicine (MD from WMC Pennsylvania in 1886).",
        bio: "Overcame immense societal ostracization and illness to pioneer medical education for Indian women.",
        dynasty: "Pioneering Science",
        featured: true,
        icon: "🩺",
        mapCoords: { lat: 19.2, lng: 73.1 }
    },
    {
        id: "kadambini-ganguly",
        name: "Dr. Kadambini Ganguly",
        era: "colonial",
        eraLabel: "1861 – 1923 CE",
        region: "Calcutta (West Bengal)",
        category: "doctors",
        contribution: "One of the first female graduates in the British Empire (1882) and first practicing female physician in India.",
        bio: "Co-addressed the Indian National Congress in 1889; advocated for working conditions of female tea plantation laborers.",
        dynasty: "Brahmo Samaj & INC",
        featured: false,
        icon: "🩺",
        mapCoords: { lat: 22.5, lng: 88.3 }
    },
    {
        id: "dr-rukhmabai-raut",
        url: "../rukhmabai-raut-profile/",
        name: "Dr. Rukhmabai Raut",
        era: "colonial",
        eraLabel: "1864 – 1955 CE",
        region: "Bombay / Surat",
        category: "doctors",
        contribution: "Challenged child marriage in landmark legal case leading to Age of Consent Act 1891; pioneering doctor for 35 yrs.",
        bio: "Graduated from London School of Medicine for Women (1894) and served as Chief Medical Officer in Rajkot and Surat.",
        dynasty: "Medical Pioneers",
        featured: false,
        icon: "🩺",
        mapCoords: { lat: 18.9, lng: 72.8 }
    },
    {
        id: "toru-dutt",
        name: "Toru Dutt",
        era: "colonial",
        eraLabel: "1856 – 1877 CE",
        region: "Calcutta (West Bengal)",
        category: "writers",
        contribution: "Pioneering Indian English poet; author of 'Ancient Ballads and Legends of Hindustan'.",
        bio: "Master of English and French poetry whose lyrical genius won international acclaim before her tragic death at age 21.",
        dynasty: "Literary Renaissance",
        featured: false,
        icon: "✍️",
        mapCoords: { lat: 22.5, lng: 88.3 }
    },

    // --- Freedom Struggle Era ---
    {
        id: "bhikaiji-cama",
        url: "../bhikaji-cama/",
        name: "Madam Bhikaiji Cama",
        era: "freedom-struggle",
        eraLabel: "1861 – 1936 CE",
        region: "Bombay & Paris/Stuttgart",
        category: "freedom-fighters",
        contribution: "Unfurled the first version of India's national flag on foreign soil at the 1907 International Socialist Congress.",
        bio: "Exiled revolutionary who published Bande Mataram and funded freedom movements from Paris and London.",
        dynasty: "Revolutionary Freedom Movement",
        featured: false,
        icon: "🇮🇳",
        mapCoords: { lat: 18.9, lng: 72.8 }
    },
    {
        id: "sarojini-naidu",
        url: "../sarojini-naidu-explorer/",
        name: "Sarojini Naidu",
        era: "freedom-struggle",
        eraLabel: "1879 – 1949 CE",
        region: "Hyderabad & Uttar Pradesh",
        category: "freedom-fighters",
        contribution: "Known as 'Nightingale of India'; first Indian woman President of INC (1925) and first female Governor (UP).",
        bio: "Poet, orator, and central leader of Non-Cooperation, Civil Disobedience (Dharasana Salt Works), and Quit India.",
        dynasty: "Indian National Congress",
        featured: true,
        icon: "✍️",
        mapCoords: { lat: 17.3, lng: 78.4 }
    },
    {
        id: "kamaladevi-chattopadhyay",
        name: "Kamaladevi Chattopadhyay",
        era: "freedom-struggle",
        eraLabel: "1903 – 1988 CE",
        region: "Mangalore (Karnataka)",
        category: "freedom-fighters",
        contribution: "Revived Indian handicrafts, theatre, handlooms, and played a fearless role in the 1930 Salt Satyagraha.",
        bio: "First woman to contest a legislative seat in India; established the National School of Drama, Sangeet Natak Akademi, and Crafts Council.",
        dynasty: "Freedom & Cultural Renaissance",
        featured: false,
        icon: "🧵",
        mapCoords: { lat: 12.9, lng: 74.8 }
    },
    {
        id: "aruna-asaf-ali",
        url: "../aruna-asaf-ali-explorer/",
        name: "Aruna Asaf Ali",
        era: "freedom-struggle",
        eraLabel: "1909 – 1996 CE",
        region: "Kalka (Haryana) & Delhi",
        category: "freedom-fighters",
        contribution: "Hoisted the Indian National Flag at Gowalia Tank Maidan, Bombay, launching the 1942 Quit India Movement.",
        bio: "Known as 'Grand Old Lady of the Independence Movement'; edited the underground monthly Inquilab and evaded arrest.",
        dynasty: "Quit India Underground",
        featured: false,
        icon: "🚩",
        mapCoords: { lat: 28.6, lng: 77.2 }
    },
    {
        id: "usha-mehta",
        url: "../usha-mehta-explorer/",
        name: "Dr. Usha Mehta",
        era: "freedom-struggle",
        eraLabel: "1920 – 2000 CE",
        region: "Saras (Gujarat) & Bombay",
        category: "freedom-fighters",
        contribution: "Operated the underground 'Secret Congress Radio' broadcasting news and Gandhi's messages during Quit India (1942).",
        bio: "Gandhian freedom fighter who endured harsh imprisonment without betraying comrades; awarded Padma Vibhushan.",
        dynasty: "Congress Radio Movement",
        featured: false,
        icon: "📻",
        mapCoords: { lat: 21.1, lng: 72.8 }
    },
    {
        id: "matangini-hazra",
        url: "../matangini-hazra-explorer/",
        name: "Matangini Hazra",
        era: "freedom-struggle",
        eraLabel: "1869 – 1942 CE",
        region: "Tamluk, Midnapore (West Bengal)",
        category: "freedom-fighters",
        contribution: "Known as 'Gandhi Buri'; shot dead while holding the national tricolor aloft leading 6,000 Quit India protestors.",
        bio: "73-year-old peasant revolutionary who kept chanting 'Vande Mataram' as British police repeatedly fired at her.",
        dynasty: "Quit India Movement",
        featured: false,
        icon: "🇮🇳",
        mapCoords: { lat: 22.3, lng: 87.9 }
    },
    {
        id: "kanaklata-barua",
        name: "Kanaklata Barua",
        era: "freedom-struggle",
        eraLabel: "1924 – 1942 CE",
        region: "Gohpur (Assam)",
        category: "freedom-fighters",
        contribution: "Led the Mrityu Bahini (Death Squad) to hoist the national flag at Gohpur Police Station during Quit India.",
        bio: "17-year-old martyr shot dead by colonial police while steadfastly holding the tricolor from falling.",
        dynasty: "Assam Freedom Movement",
        featured: false,
        icon: "🇮🇳",
        mapCoords: { lat: 26.8, lng: 93.6 }
    },
    {
        id: "captain-lakshmi-sahgal",
        name: "Captain Lakshmi Sahgal",
        era: "freedom-struggle",
        eraLabel: "1914 – 2012 CE",
        region: "Madras & Singapore/Burma",
        category: "freedom-fighters",
        contribution: "Commander of the all-female Rani of Jhansi Regiment in Subhas Chandra Bose's Indian National Army (INA).",
        bio: "Doctor and revolutionary officer who led combat troops into the Burma Campaign and spent life serving impoverished patients.",
        dynasty: "Indian National Army (INA)",
        featured: true,
        icon: "⚔️",
        mapCoords: { lat: 13.0, lng: 80.2 }
    },
    {
        id: "pritilata-waddedar",
        name: "Pritilata Waddedar",
        era: "freedom-struggle",
        eraLabel: "1911 – 1932 CE",
        region: "Chittagong (Bengal)",
        category: "freedom-fighters",
        contribution: "Surya Sen's revolutionary lieutenant who led the raid on the segregated Pahartali European Club in 1932.",
        bio: "Educated school headmistress who sacrificed her life by consuming potassium cyanide rather than surrender to colonial police.",
        dynasty: "Chittagong Revolutionary Group",
        featured: true,
        icon: "✊",
        mapCoords: { lat: 22.3, lng: 91.8 }
    },
    {
        id: "bina-das",
        name: "Bina Das",
        era: "freedom-struggle",
        eraLabel: "1911 – 1986 CE",
        region: "Calcutta (West Bengal)",
        category: "freedom-fighters",
        contribution: "Attempted to assassinate Bengal Governor Stanley Jackson at Calcutta University Convocation in 1932.",
        bio: "Member of Chhatri Sangha who spent 7 years in hard labor; refused to express regret in her fiery court defense.",
        dynasty: "Bengal Revolutionary Movement",
        featured: false,
        icon: "✊",
        mapCoords: { lat: 22.5, lng: 88.3 }
    },
    {
        id: "kalpana-datta",
        name: "Kalpana Datta",
        era: "freedom-struggle",
        eraLabel: "1913 – 1995 CE",
        region: "Chittagong (Bengal)",
        category: "freedom-fighters",
        contribution: "Bomb-maker and armed revolutionary in Masterda Surya Sen's Indian Republican Army during the Chittagong Armoury Raid.",
        bio: "Engaged in armed firefights against British forces, sentenced to transportation for life, and later active in social welfare.",
        dynasty: "Chittagong Armoury Movement",
        featured: false,
        icon: "💣",
        mapCoords: { lat: 22.3, lng: 91.8 }
    },
    {
        id: "rani-gaidinliu",
        url: "../rani-gaidinliu/",
        name: "Rani Gaidinliu",
        era: "freedom-struggle",
        eraLabel: "1915 – 1993 CE",
        region: "Tamenglong (Manipur/Nagaland)",
        category: "freedom-fighters",
        contribution: "Led the Heraka anti-colonial resistance across Manipur, Nagaland, and Assam at age 16; imprisoned for 14 years.",
        bio: "Named 'Rani' of the hills by Jawaharlal Nehru; fought for indigenous cultural pride and self-rule.",
        dynasty: "Heraka Tribal Movement",
        featured: true,
        icon: "🌿",
        mapCoords: { lat: 24.9, lng: 93.4 }
    },
    {
        id: "durga-bhabhi",
        name: "Durgawati Devi (Durga Bhabhi)",
        era: "freedom-struggle",
        eraLabel: "1907 – 1999 CE",
        region: "Allahabad & Lahore",
        category: "freedom-fighters",
        contribution: "Disguised as Bhagat Singh's wife to escort him on a train escape from Lahore after Saunders' assassination.",
        bio: "Key member of HSRA, transported arms and funds, attempted to assassinate Lord Hailey, and ran schools for orphans.",
        dynasty: "Hindustan Socialist Republican Association",
        featured: false,
        icon: "🚂",
        mapCoords: { lat: 25.4, lng: 81.8 }
    },
    {
        id: "tara-rani-srivastava",
        name: "Tara Rani Srivastava",
        era: "freedom-struggle",
        eraLabel: "c. 1920 – 1942 CE+",
        region: "Saran / Siwan (Bihar)",
        category: "freedom-fighters",
        contribution: "Bandaged her husband after he was shot, continued marching, and hoisted the national tricolor on Siwan Police Station.",
        bio: "Quit India heroine who held the national flag aloft despite police firing.",
        dynasty: "Quit India Movement",
        featured: false,
        icon: "🇮🇳",
        mapCoords: { lat: 26.2, lng: 84.3 }
    },
    {
        id: "annie-mascarene",
        name: "Annie Mascarene",
        era: "freedom-struggle",
        eraLabel: "1902 – 1963 CE",
        region: "Thiruvananthapuram (Kerala)",
        category: "freedom-fighters",
        contribution: "Pioneer of Travancore State Congress; one of 15 women elected to the Constituent Assembly of India.",
        bio: "First woman to serve in Travancore-Cochin state cabinet; advocated for constitutional rights and federal union integration.",
        dynasty: "Constituent Assembly of India",
        featured: false,
        icon: "📜",
        mapCoords: { lat: 8.5, lng: 76.9 }
    },
    {
        id: "dakshayani-velayudhan",
        name: "Dakshayani Velayudhan",
        era: "freedom-struggle",
        eraLabel: "1912 – 1978 CE",
        region: "Kochi (Kerala)",
        category: "social-reformers",
        contribution: "First and only Dalit woman elected to the Constituent Assembly of India; fought against untouchability in the Constitution.",
        bio: "First Dalit woman in India to earn a science degree; championed non-discrimination and fundamental equality.",
        dynasty: "Constituent Assembly of India",
        featured: false,
        icon: "⚖️",
        mapCoords: { lat: 9.9, lng: 76.2 }
    },
    {
        id: "hansa-jivraj-mehta",
        name: "Hansa Jivraj Mehta",
        era: "freedom-struggle",
        eraLabel: "1897 – 1995 CE",
        region: "Surat & Baroda (Gujarat)",
        category: "social-reformers",
        contribution: "Constituent Assembly member; successfully changed UDHR wording from 'All men are born free' to 'All human beings'.",
        bio: "Educationalist, Vice-Chancellor of MS University Baroda, and president of the All India Women's Conference.",
        dynasty: "Constituent Assembly & UN Human Rights",
        featured: false,
        icon: "🌐",
        mapCoords: { lat: 21.1, lng: 72.8 }
    },
    {
        id: "begum-aizaz-rasul",
        name: "Begum Aizaz Rasul",
        era: "freedom-struggle",
        eraLabel: "1909 – 2001 CE",
        region: "Malerkotla (Punjab) & Lucknow",
        category: "queens-rulers",
        contribution: "Only Muslim woman member of the Constituent Assembly of India; successfully opposed separate religious electorates.",
        bio: "Championed Indian secular democracy, women's sports (President of Indian Women's Hockey Federation), and education.",
        dynasty: "Constituent Assembly of India",
        featured: false,
        icon: "⚖️",
        mapCoords: { lat: 30.5, lng: 75.8 }
    },
    {
        id: "ammu-swaminathan",
        name: "Ammu Swaminathan",
        era: "freedom-struggle",
        eraLabel: "1894 – 1978 CE",
        region: "Palakkad (Kerala) & Madras",
        category: "freedom-fighters",
        contribution: "Constituent Assembly member, founder of AIWC, and fearless voice against caste rituals and gender discrimination.",
        bio: "Signatory of the Indian Constitution; mother of Captain Lakshmi Sahgal and Mrinalini Sarabhai.",
        dynasty: "Constituent Assembly of India",
        featured: false,
        icon: "📜",
        mapCoords: { lat: 10.7, lng: 76.6 }
    },
    {
        id: "sucheta-kripalani",
        name: "Sucheta Kripalani",
        era: "freedom-struggle",
        eraLabel: "1908 – 1974 CE",
        region: "Ambala (Haryana) & UP",
        category: "freedom-fighters",
        contribution: "First female Chief Minister of an Indian state (Uttar Pradesh, 1963–67); sang Vande Mataram at independence midnight session.",
        bio: "Central organizer of the 1942 Quit India underground relief and Noakhali peace mission with Mahatma Gandhi.",
        dynasty: "Indian National Congress",
        featured: false,
        icon: "🏛️",
        mapCoords: { lat: 30.3, lng: 76.7 }
    },

    // --- Scientists, Doctors, Artists, Post-Independence ---
    {
        id: "edavalath-kakkad-janaki-ammal",
        name: "Dr. Janaki Ammal",
        era: "post-independence",
        eraLabel: "1897 – 1984 CE",
        region: "Thalassery (Kerala)",
        category: "scientists",
        contribution: "Pioneering cytogeneticist and botanist; co-authored the Chromosome Atlas and developed indigenous sugarcane hybrids.",
        bio: "First Indian woman to obtain a PhD in botany (University of Michigan, 1931); spearheaded Save Silent Valley campaign.",
        dynasty: "Botanical Survey of India",
        featured: true,
        icon: "🔬",
        mapCoords: { lat: 11.7, lng: 75.4 }
    },
    {
        id: "asima-chatterjee",
        name: "Dr. Asima Chatterjee",
        era: "post-independence",
        eraLabel: "1917 – 2006 CE",
        region: "Calcutta (West Bengal)",
        category: "scientists",
        contribution: "Pioneering organic chemist; developed anti-epileptic drug 'Ayush-56' and anti-malarial drugs from vinca alkaloids.",
        bio: "First woman recipient of a Doctor of Science from an Indian university (Calcutta, 1944) and first female Shanti Swarup Bhatnagar laureate.",
        dynasty: "Indian Science Congress",
        featured: true,
        icon: "🧪",
        mapCoords: { lat: 22.5, lng: 88.3 }
    },
    {
        id: "anna-mani",
        name: "Anna Mani",
        era: "post-independence",
        eraLabel: "1918 – 2001 CE",
        region: "Peermade (Kerala) & Bangalore",
        category: "scientists",
        contribution: "Physicist and meteorologist; invented over 100 weather instruments and standardized ozone and solar measuring devices.",
        bio: "Mentored by C. V. Raman; served as Deputy Director General of the India Meteorological Department (IMD).",
        dynasty: "Indian Meteorological Department",
        featured: false,
        icon: "☀️",
        mapCoords: { lat: 9.5, lng: 77.0 }
    },
    {
        id: "kamala-sohonie",
        name: "Dr. Kamala Sohonie",
        era: "post-independence",
        eraLabel: "1911 – 1998 CE",
        region: "Indore (MP) & Bombay",
        category: "scientists",
        contribution: "First Indian woman to receive a PhD in a scientific discipline (Cambridge University, 1939); discovered Cytochrome C.",
        bio: "Pioneered nutritional enhancements from Neera to combat malnutrition among tribal and impoverished children.",
        dynasty: "Biochemistry & IISc",
        featured: false,
        icon: "🔬",
        mapCoords: { lat: 22.7, lng: 75.8 }
    },
    {
        id: "rajeshwari-chatterjee",
        name: "Prof. Rajeshwari Chatterjee",
        era: "post-independence",
        eraLabel: "1922 – 2010 CE",
        region: "Karnataka",
        category: "scientists",
        contribution: "First woman engineer in Karnataka; pioneering microwave and radar antennas researcher at IISc Bangalore.",
        bio: "Chaired the Department of Electrical Communication Engineering at IISc and co-authored foundational antenna textbooks.",
        dynasty: "IISc Bangalore",
        featured: false,
        icon: "📡",
        mapCoords: { lat: 12.9, lng: 77.5 }
    },
    {
        id: "dr-muthulakshmi-reddi",
        name: "Dr. Muthulakshmi Reddi",
        era: "freedom-struggle",
        eraLabel: "1886 – 1968 CE",
        region: "Pudukkottai & Madras (Tamil Nadu)",
        category: "doctors",
        contribution: "First female legislator in India; founded the Adyar Cancer Institute and established Avvai Home for girls.",
        bio: "Pioneered the abolition of the Devadasi system, raised the age of marriage, and dedicated her life to medical service.",
        dynasty: "Madras Legislative Council",
        featured: false,
        icon: "🏥",
        mapCoords: { lat: 13.0, lng: 80.2 }
    },
    {
        id: "kadambari-devi",
        name: "Kadambari Devi",
        era: "colonial",
        eraLabel: "1859 – 1884 CE",
        region: "Calcutta (West Bengal)",
        category: "artists",
        contribution: "Literary muse, critic, and patron of Rabindranath Tagore; central catalyst of Bengal Renaissance literary arts.",
        bio: "Inspiring intellectual figure in the Jorasanko Tagore household whose feedback shaped modern Bengali poetry.",
        dynasty: "Bengal Renaissance",
        featured: false,
        icon: "🎨",
        mapCoords: { lat: 22.5, lng: 88.3 }
    },
    {
        id: "amrita-sher-gil",
        name: "Amrita Sher-Gil",
        era: "freedom-struggle",
        eraLabel: "1913 – 1941 CE",
        region: "Budapest & Shimla/Gorakhpur",
        category: "artists",
        contribution: "Pioneer of modern Indian art; bridged Western avant-garde techniques with traditional Indian miniature aesthetics.",
        bio: "One of the most celebrated 'Nine National Masters' of India; portrayed poignant rural lives and women's internal worlds.",
        dynasty: "Modern Indian Art",
        featured: true,
        icon: "🎨",
        mapCoords: { lat: 31.1, lng: 77.1 }
    },
    {
        id: "ms-subbulakshmi",
        name: "M. S. Subbulakshmi",
        era: "post-independence",
        eraLabel: "1916 – 2004 CE",
        region: "Madurai & Madras (Tamil Nadu)",
        category: "artists",
        contribution: "Doyen of Carnatic classical vocal music; first musician to receive Bharat Ratna and Ramon Magsaysay Award.",
        bio: "First Indian musician to perform at the United Nations General Assembly (1966); voice of iconic Suprabhatam and Bhaja Govindam.",
        dynasty: "Carnatic Music",
        featured: false,
        icon: "🎶",
        mapCoords: { lat: 9.9, lng: 78.1 }
    },
    {
        id: "rukmini-devi-arundale",
        name: "Rukmini Devi Arundale",
        era: "post-independence",
        eraLabel: "1904 – 1986 CE",
        region: "Madurai & Chennai (Tamil Nadu)",
        category: "artists",
        contribution: "Revived and revitalized Bharatanatyam; founded Kalakshetra Foundation and Animal Welfare Board of India.",
        bio: "Nominated to Rajya Sabha; transformed classical dance education and introduced landmark Prevention of Cruelty to Animals Act.",
        dynasty: "Kalakshetra Foundation",
        featured: false,
        icon: "💃",
        mapCoords: { lat: 13.0, lng: 80.2 }
    },
    {
        id: "mahadevi-varma",
        name: "Mahadevi Varma",
        era: "freedom-struggle",
        eraLabel: "1907 – 1987 CE",
        region: "Farrukhabad & Allahabad (UP)",
        category: "writers",
        contribution: "Major pillar of the Chhayavad romantic movement in Hindi literature; Jnanpith and Padma Vibhushan laureate.",
        bio: "Vice-chancellor of Prayag Mahila Vidyapeeth; championed women's economic independence and education.",
        dynasty: "Hindi Chhayavad Movement",
        featured: false,
        icon: "✍️",
        mapCoords: { lat: 25.4, lng: 81.8 }
    },
    {
        id: "ismath-chughtai",
        name: "Ismat Chughtai",
        era: "freedom-struggle",
        eraLabel: "1915 – 1991 CE",
        region: "Badayun & Bombay",
        category: "writers",
        contribution: "Grand dame of modern Urdu fiction; vanguard of Progressive Writers' Movement exploring female sexuality and realism.",
        bio: "Fearless writer of 'Lihaaf' who defended artistic free expression against colonial obscenity trials in Lahore.",
        dynasty: "Progressive Writers' Association",
        featured: false,
        icon: "✍️",
        mapCoords: { lat: 28.0, lng: 79.1 }
    },
    {
        id: "amrita-pritam",
        name: "Amrita Pritam",
        era: "post-independence",
        eraLabel: "1919 – 2005 CE",
        region: "Gujranwala (Punjab) & Delhi",
        category: "writers",
        contribution: "Eminent Punjabi poet and novelist; author of poignant Partition elegy 'Ajj Aakhaan Waris Shah Nu' and 'Pinjar'.",
        bio: "First woman to win the Sahitya Akademi Award (1956) and Bharatiya Jnanpith (1981); celebrated across India and Pakistan.",
        dynasty: "Punjabi Literature",
        featured: false,
        icon: "✍️",
        mapCoords: { lat: 28.6, lng: 77.2 }
    },
    {
        id: "kalpana-chawla",
        name: "Dr. Kalpana Chawla",
        era: "post-independence",
        eraLabel: "1962 – 2003 CE",
        region: "Karnal (Haryana)",
        category: "scientists",
        contribution: "First woman of Indian origin in space; aerospace engineer and NASA astronaut on STS-87 and STS-107 missions.",
        bio: "Inspiring global role model whose passion for celestial discovery opened astronomical horizons for millions.",
        dynasty: "Space Exploration",
        featured: false,
        icon: "🚀",
        mapCoords: { lat: 29.6, lng: 76.9 }
    },
    {
        id: "ramabai-ranade",
        url: "../ramabai-ranade-explorer/",
        name: "Ramabai Ranade",
        era: "colonial",
        eraLabel: "1862 – 1924 CE",
        region: "Sangli / Pune & Bombay",
        category: "social-reformers",
        contribution: "Pioneer of female vocational training, co-founder of Seva Sadan and Arya Mahila Samaj, and advocate for women's suffrage.",
        bio: "Leading social reformer who established India's premier female nursing and vocational institution, fought for female voting rights in 1919, and authored celebrated Marathi memoirs.",
        dynasty: "Seva Sadan & Social Reform",
        featured: true,
        icon: "📖",
        mapCoords: { lat: 18.52, lng: 73.85 }
    },
    {
        id: "anandibai-joshi",
        url: "../anandibai-joshi-explorer/",
        name: "Dr. Anandibai Joshi",
        era: "colonial",
        eraLabel: "1865 – 1887 CE",
        region: "Kalyan / Pune & Philadelphia",
        category: "doctors",
        contribution: "First Indian woman to earn a Doctor of Medicine (M.D.) degree in the USA (WMCP 1886) and pioneer of maternal health.",
        bio: "Overcame tremendous personal tragedy and social excommunication to study medicine at WMCP Philadelphia, authoring a landmark thesis on Indian obstetrics.",
        dynasty: "Pioneering Indian Medicine",
        featured: true,
        icon: "🩺",
        mapCoords: { lat: 19.24, lng: 73.13 }
    },
    {
        id: "janaki-ammal",
        url: "../janaki-ammal-explorer/",
        name: "Dr. E. K. Janaki Ammal",
        era: "post-independence",
        eraLabel: "1897 – 1984 CE",
        region: "Thalassery (Kerala) & Coimbatore / London",
        category: "scientists",
        contribution: "Pioneering cytogeneticist who developed high-sucrose hybrid sugarcane, co-authored the Chromosome Atlas, and saved Silent Valley.",
        bio: "First Indian woman to earn a D.Sc. in Botany (Univ. of Michigan 1931). Master of polyploid plant genetics, Director-General of BSI, and defender of India's biodiversity.",
        dynasty: "Sugarcane Genetics & BSI",
        featured: true,
        icon: "🔬",
        mapCoords: { lat: 11.75, lng: 75.49 }
    },
    {
        id: "cornelia-sorabji",
        url: "../cornelia-sorabji-explorer/",
        name: "Cornelia Sorabji",
        era: "colonial",
        eraLabel: "1866 – 1954 CE",
        region: "Nashik / Pune & London / Calcutta",
        category: "social-reformers",
        contribution: "First female advocate of India, first woman to read law at Oxford (BCL 1892), and protector of Purdahnashin women's rights.",
        bio: "Pioneering legal reformer who broke gender barriers at Oxford and in the Indian courts, representing over 600 secluded purdahnashin women and minor orphans.",
        dynasty: "Indian Legal Heritage",
        featured: true,
        icon: "⚖️",
        mapCoords: { lat: 19.99, lng: 73.79 }
    },
    {
        id: "mary-kom",
        name: "M. C. Mary Kom",
        era: "post-independence",
        eraLabel: "1982 CE – Present",
        region: "Kangathei, Churachandpur (Manipur)",
        category: "artists",
        contribution: "Legendary boxer; only boxer (male or female) to become World Amateur Boxing Champion six times.",
        bio: "Olympic bronze medallist, Rajya Sabha MP, and icon of resilience for women athletes across the world.",
        dynasty: "Indian Sports Icons",
        featured: false,
        icon: "🥊",
        mapCoords: { lat: 24.3, lng: 93.6 }
    }
];

const HISTORICAL_METHODOLOGY = {
    title: "Historical Sources & Preserving Women's History",
    principles: [
        {
            title: "Primary Inscriptions & Epigraphy",
            text: "Ancient and medieval women rulers (Prabhavatigupta, Rudrama Devi, Akkadevi) are corroborated via contemporary stone inscriptions, copper-plate charters, and temple grants that document authentic royal titles and administrative decisions."
        },
        {
            title: "Distinguishing History from Folklore",
            text: "Later bardic lore often embellishes military deeds with mythic exaggerations (e.g. firing gold coins from cannons). This archive prioritizes contemporary chronicles (Firishta, Akbarnama, Kalhana's Rajatarangini, British East India Company records) to establish empirical historical groundings."
        },
        {
            title: "Overcoming Archival Erasure",
            text: "Women's contributions were frequently recorded only as appendages to male dynasties or omitted from colonial official gazetteers. Modern historical scholarship restores these agency-rich voices to central historical narratives."
        }
    ]
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        ERAS,
        CATEGORIES,
        WOMEN_PROFILES,
        HISTORICAL_METHODOLOGY
    };
}
