/**
 * coins-data.js
 * Dataset of Indian Coinage across periods, dynasties, metals, and regions.
 */

window.COINS_DATA = [
  {
    id: "indo-greek-drachm",
    name: "Menander I Silver Drachm",
    period: "ancient",
    dynasty: "Indo-Greek",
    region: "North",
    metal: "Silver",
    denomination: "Drachm",
    ruler: "Menander I Soter (Milinda)",
    dateRange: "c. 165–130 BCE",
    image: "../../assets/images/coins/indo-greek-menander.svg",
    description: "Features realistic helmeted royal portrait of Menander I on obverse with Greek legend 'BASILEOS SOTEROS MENANDROU' and reverse Athena Alkidemos with Kharosthi script.",
    explorerUrl: "../indo-greek-coins-explorer/index.html",
    isInteractive: true,
    tags: ["Indo-Greek", "Portrait", "Kharosthi", "Athena", "Taxila"]
  },
  {
    id: "satavahana-ship-coin",
    name: "Vashishtiputra Pulumavi Ship Lead Coin",
    period: "classical",
    dynasty: "Satavahana",
    region: "Deccan",
    metal: "Potin",
    denomination: "Karshapana",
    ruler: "Vashishtiputra Pulumavi / Yajna Sri Satakarni",
    dateRange: "c. 130–170 CE",
    image: "../../assets/images/coins/satavahana-ship.svg",
    description: "Famous maritime coin of the Satavahana Empire depicting a two-masted ocean-going sailing ship with rigged sails, highlighting Indian Ocean sea trade with Rome.",
    explorerUrl: "../satavahana-coins-deccan/index.html",
    isInteractive: true,
    tags: ["Satavahana", "Deccan", "Maritime", "Ship", "Prakrit"]
  },
  {
    id: "gupta-ashvamedha",
    name: "Samudragupta Ashvamedha Gold Dinara",
    period: "classical",
    dynasty: "Gupta",
    region: "North",
    metal: "Gold",
    denomination: "Dinara",
    ruler: "Samudragupta",
    dateRange: "c. 335–375 CE",
    image: "../../assets/images/coins/gupta-ashvamedha.svg",
    description: "Gold coin commemorating the horse sacrifice (Ashvamedha) ritual, showing sacrificial horse tied to Yupa post on obverse and Queen Dattadevi holding a fly-whisk on reverse.",
    explorerUrl: "../gupta-coinage-gallery/index.html",
    isInteractive: true,
    tags: ["Gupta", "Gold", "Ashvamedha", "Sanskrit", "Bayana"]
  },
  {
    id: "kushan-kanishka-buddha",
    name: "Kanishka I Buddha Gold Dinar",
    period: "ancient",
    dynasty: "Kushan",
    region: "North",
    metal: "Gold",
    denomination: "Dinar",
    ruler: "Kanishka the Great",
    dateRange: "c. 127–150 CE",
    image: "../../assets/images/coins/kushan-kanishka.svg",
    description: "Rare Kushan gold coin depicting Emperor Kanishka sacrificing at an altar on the obverse and standing Buddha (BODDO) in Bactrian Greek script on reverse.",
    explorerUrl: "../kushan-gold-coinage/index.html",
    isInteractive: true,
    tags: ["Kushan", "Gold", "Buddha", "Bactrian", "Gandhara"]
  },
  {
    id: "chola-rajaraja",
    name: "Rajaraja Chola Standing King Gold Coin",
    period: "classical",
    dynasty: "Chola",
    region: "South",
    metal: "Gold",
    denomination: "Kasu",
    ruler: "Rajaraja Chola I",
    dateRange: "c. 985–1014 CE",
    image: "../../assets/images/coins/chola-rajaraja.svg",
    description: "Imperial Chola gold coin depicting standing king holding lotus on obverse and seated king with Nagari legend 'Sri Rajaraja' on reverse alongside Chola tiger and twin fish.",
    explorerUrl: "../chola-coin-decoder/index.html",
    isInteractive: true,
    tags: ["Chola", "South", "Tiger", "Kasu", "Nagari"]
  },
  {
    id: "mughal-zodiac-leo",
    name: "Jahangir Leo Zodiac Gold Mohur",
    period: "medieval",
    dynasty: "Mughal",
    region: "North",
    metal: "Gold",
    denomination: "Mohur",
    ruler: "Jahangir",
    dateRange: "c. 1618–1624 CE",
    image: "../../assets/images/coins/mughal-leo.svg",
    description: "Iconic artistic gold mohur issued by Emperor Jahangir featuring the constellation Leo (Lion radiating solar rays) minted at Agra with Persian poetic couplet.",
    explorerUrl: "../jahangir-zodiac-coins-explorer/index.html",
    isInteractive: true,
    tags: ["Mughal", "Zodiac", "Gold", "Persian", "Agra"]
  },
  {
    id: "maratha-shivrai",
    name: "Chhatrapati Shivaji Maharaj Shivrai Copper Coin",
    period: "princely",
    dynasty: "Maratha",
    region: "Deccan",
    metal: "Copper",
    denomination: "Paisa / Shivrai",
    ruler: "Chhatrapati Shivaji Maharaj",
    dateRange: "c. 1674–1680 CE",
    image: "../../assets/images/coins/maratha-shivrai.svg",
    description: "Official copper coin minted at Raigad Fort after Shivaji Maharaj's coronation (Rajyabhisheka), featuring Devanagari legend 'Sri Raja Siva' and 'Chhatrapati'.",
    explorerUrl: "../maratha-coinage-explorer/index.html",
    isInteractive: true,
    tags: ["Maratha", "Coronation", "Devanagari", "Raigad", "Copper"]
  },
  {
    id: "mysore-double-pagoda",
    name: "Tipu Sultan Double Gold Pagoda (Ahmadi)",
    period: "princely",
    dynasty: "Mysore",
    region: "South",
    metal: "Gold",
    denomination: "Double Pagoda (Ahmadi)",
    ruler: "Tipu Sultan",
    dateRange: "c. 1782–1799 CE",
    image: "../../assets/images/coins/mysore-pagoda.svg",
    description: "Exquisite gold coin from Seringapatam mint using Mauludi calendar, featuring royal insignia and Islamic dates, reflecting Tipu Sultan's advanced mint reform.",
    explorerUrl: "../mysore-coinage-explorer/index.html",
    isInteractive: true,
    tags: ["Mysore", "Tipu Sultan", "Gold", "Pagoda", "Mauludi"]
  },
  {
    id: "sikh-nanakshahi-rupee",
    name: "Maharaja Ranjit Singh Nanakshahi Silver Rupee",
    period: "princely",
    dynasty: "Sikh",
    region: "North",
    metal: "Silver",
    denomination: "Rupee",
    ruler: "Maharaja Ranjit Singh",
    dateRange: "c. 1801–1839 CE",
    image: "../../assets/images/coins/sikh-nanakshahi.svg",
    description: "Minted at Amritsar and Lahore featuring Gurmukhi leaf symbol (peepal leaf) and Persian couplets dedicated to Guru Nanak Dev Ji and Guru Gobind Singh Ji.",
    explorerUrl: "../sikh-empire-coinage-explorer/index.html",
    isInteractive: true,
    tags: ["Sikh Empire", "Amritsar", "Nanakshahi", "Peepal Leaf", "Silver"]
  },
  {
    id: "akbar-ilahi-square",
    name: "Akbar Square Silver Rupee (Ilahi Era)",
    period: "medieval",
    dynasty: "Mughal",
    region: "Central",
    metal: "Silver",
    denomination: "Rupee",
    ruler: "Akbar the Great",
    dateRange: "c. 1584–1605 CE",
    image: "../../assets/images/coins/akbar-ilahi.svg",
    description: "Square silver rupee introducing the Din-i-Ilahi era motto 'Allahu Akbar Jalla Jalalahu', breaking from traditional circular Coin forms.",
    explorerUrl: "../akbar-ilahi-coinage-explorer/index.html",
    isInteractive: true,
    tags: ["Mughal", "Akbar", "Square Rupee", "Ilahi Era", "Urdu Zafarabad"]
  },
  {
    id: "pandya-fish-coin",
    name: "Pandya Empire Twin Fish Copper Coin",
    period: "classical",
    dynasty: "Pandya",
    region: "South",
    metal: "Copper",
    denomination: "Kasu",
    ruler: "Jatavarman Sundara Pandya",
    dateRange: "c. 1251–1268 CE",
    image: "../../assets/images/coins/pandya-fish.svg",
    description: "Featuring the royal Pandyan emblem of twin carp fishes beneath a royal umbrella on the obverse and Tamil legend 'Ellam Thalaiyanan' on reverse.",
    explorerUrl: "../pandya-fish-coins-explorer/index.html",
    isInteractive: true,
    tags: ["Pandya", "Madurai", "Twin Fish", "Tamil", "Copper"]
  },
  {
    id: "delhi-sultanate-tanka",
    name: "Alauddin Khalji Silver Tanka",
    period: "medieval",
    dynasty: "Delhi Sultanate",
    region: "North",
    metal: "Silver",
    denomination: "Tanka",
    ruler: "Alauddin Khalji",
    dateRange: "c. 1296–1316 CE",
    image: "../../assets/images/coins/khalji-tanka.svg",
    description: "Heavy silver tanka minted at Hazrat Delhi proclaiming the Sultan as 'Sikandar al-Sani' (Alexander the Second) in bold Naskh Arabic script.",
    explorerUrl: "../delhi-sultanate-coin-timeline/index.html",
    isInteractive: true,
    tags: ["Delhi Sultanate", "Khalji", "Tanka", "Arabic", "Delhi"]
  }
];
