/* ==========================================================================
   Waterfalls Data
   Comprehensive dataset of Indian waterfalls with map coordinates and metadata.
   ========================================================================== */
const waterfallsData = [
    { id: 'kunchikal', name: 'Kunchikal Falls', state: 'Karnataka', region: 'South', river: 'Varahi', height: 455, type: 'highest', season: 'Monsoon', desc: 'The tallest waterfall in India, formed by the Varahi river in the Western Ghats.', img: 'https://placehold.co/400x300/0077B6/fff?text=Kunchikal', mapX: 35, mapY: 75 },
    { id: 'nohkalikai', name: 'Nohkalikai Falls', state: 'Meghalaya', region: 'Northeast', river: 'Nohkalikai', height: 340, type: 'highest', season: 'Monsoon', desc: 'India\'s tallest plunge waterfall, famous for its vivid green plunge pool.', img: 'https://placehold.co/400x300/2D6A4F/fff?text=Nohkalikai', mapX: 80, mapY: 45 },
    { id: 'dudhsagar', name: 'Dudhsagar Falls', state: 'Goa/Karnataka', region: 'West', river: 'Mandovi', height: 310, type: 'multi-tier', season: 'Monsoon', desc: 'The "Sea of Milk", a spectacular four-tiered waterfall on the Goa-Karnataka border.', img: 'https://placehold.co/400x300/00B4D8/fff?text=Dudhsagar', mapX: 32, mapY: 68 },
    { id: 'jog', name: 'Jog Falls', state: 'Karnataka', region: 'South', river: 'Sharavathi', height: 253, type: 'monsoon', season: 'Monsoon', desc: 'One of India\'s highest plunge waterfalls, transforming into a roaring cascade during monsoons.', img: 'https://placehold.co/400x300/1A365D/fff?text=Jog', mapX: 33, mapY: 72 },
    { id: 'athirappilly', name: 'Athirappilly Falls', state: 'Kerala', region: 'South', river: 'Chalakudy', height: 25, type: 'monsoon', season: 'Monsoon', desc: 'Known as the "Niagara of India", located in the lush Sholayar forest ranges.', img: 'https://placehold.co/400x300/2D6A4F/fff?text=Athirappilly', mapX: 38, mapY: 85 },
    { id: 'chitrakote', name: 'Chitrakote Falls', state: 'Chhattisgarh', region: 'Central', river: 'Indravati', height: 29, type: 'monsoon', season: 'Monsoon', desc: 'The widest waterfall in India, often called the "Niagara Falls of India".', img: 'https://placehold.co/400x300/0077B6/fff?text=Chitrakote', mapX: 55, mapY: 60 },
    { id: 'shivanasamudra', name: 'Shivanasamudra Falls', state: 'Karnataka', region: 'South', river: 'Kaveri', height: 98, type: 'multi-tier', season: 'Year-round', desc: 'A segmented waterfall on the Kaveri river, home to Asia\'s first hydroelectric plant.', img: 'https://placehold.co/400x300/1A365D/fff?text=Shivanasamudra', mapX: 40, mapY: 80 },
    { id: 'talakona', name: 'Talakona Falls', state: 'Andhra Pradesh', region: 'South', river: 'Talakona', height: 82, type: 'hidden', season: 'Monsoon', desc: 'The highest waterfall in Andhra Pradesh, nestled deep within the Sri Venkateswara National Park.', img: 'https://placehold.co/400x300/2D6A4F/fff?text=Talakona', mapX: 45, mapY: 78 },
    { id: 'nuranang', name: 'Nuranang Falls', state: 'Arunachal Pradesh', region: 'Northeast', river: 'Nuranang Chu', height: 100, type: 'hidden', season: 'Summer', desc: 'A stunning high-altitude cascade near the Sela Pass in the Himalayas.', img: 'https://placehold.co/400x300/0B192C/fff?text=Nuranang', mapX: 82, mapY: 35 },
    { id: 'usri', name: 'Usri Falls', state: 'Jharkhand', region: 'East', river: 'Usri', height: 12, type: 'hidden', season: 'Monsoon', desc: 'A beautiful three-stream forest waterfall in the Giridih district.', img: 'https://placehold.co/400x300/2D6A4F/fff?text=Usri', mapX: 65, mapY: 50 }
];
