// data.js - Traditional Music Instruments Data

window.instrumentsData = [
    {
        id: "sitar",
        name: "Sitar",
        category: "String Instruments",
        region: "North India",
        image: "assets/sitar.jpg",
        audio: "assets/audio/sitar.mp3",
        description: "A plucked string instrument central to Hindustani classical music traditions, known for its resonant, sympathetic strings and distinct twang.",
        history: "Developed in the Indian subcontinent, its origins are traced back to the Mughal era, evolving from the Persian setar and traditional Indian veena.",
        construction: "Made of teak wood and a gourd resonator, featuring movable frets and 18-21 strings.",
        playingTechnique: "Played while seated, plucked with a metallic wire plectrum (mizrab) worn on the right index finger.",
        musicalTradition: "Hindustani Classical",
        notableExponents: "Ravi Shankar, Vilayat Khan, Nikhil Banerjee"
    },
    {
        id: "tabla",
        name: "Tabla",
        category: "Percussion Instruments",
        region: "North India",
        image: "assets/tabla.jpg",
        audio: "assets/audio/tabla.mp3",
        description: "A pair of hand drums forming the principal percussion instrument in Hindustani classical music and popular in devotional and folk music.",
        history: "Emerged in the 18th century, likely evolving from the older mridangam and pushkara drums, heavily refined by Amir Khusrow.",
        construction: "Consists of two drums: the smaller, higher-pitched 'dayan' (wood) and the larger, deeper 'bayan' (metal or clay). Both have goat skin heads with a central tuning paste (syahi).",
        playingTechnique: "Played with fingers and palms in complex, highly developed rhythmic patterns (bols).",
        musicalTradition: "Hindustani Classical, Ghazal, Qawwali",
        notableExponents: "Zakir Hussain, Alla Rakha, Kishan Maharaj"
    },
    {
        id: "veena",
        name: "Saraswati Veena",
        category: "String Instruments",
        region: "South India",
        image: "assets/veena.jpg",
        audio: "assets/audio/veena.mp3",
        description: "An ancient Indian plucked string instrument, considered the premier instrument in Carnatic classical music.",
        history: "Mentioned in the Vedas and ancient texts, it is associated with Saraswati, the Hindu goddess of knowledge and arts.",
        construction: "Carved from jackwood with a large resonator bowl, a long neck with 24 brass frets, and a secondary gourd resonator. It has 4 playing strings and 3 drone strings.",
        playingTechnique: "Finger plucking with a seated posture, utilizing heavy string bending (gamakas).",
        musicalTradition: "Carnatic Classical",
        notableExponents: "Emani Sankara Sastry, S. Balachander, Chitti Babu"
    },
    {
        id: "bansuri",
        name: "Bansuri (Flute)",
        category: "Wind Instruments",
        region: "All India",
        image: "assets/bansuri.jpg",
        audio: "assets/audio/bansuri.mp3",
        description: "A side-blown bamboo flute intimately associated with Lord Krishna and pastoral traditions.",
        history: "One of the oldest musical instruments of India, deeply rooted in Hindu mythology and folk music before being elevated to classical concert status in the 20th century.",
        construction: "Crafted from a single hollow shaft of bamboo with six or seven finger holes.",
        playingTechnique: "Blown transversely, notes are controlled by covering holes with the finger pads. Microtones are produced by partial hole coverage.",
        musicalTradition: "Hindustani Classical, Folk",
        notableExponents: "Hariprasad Chaurasia, Pannalal Ghosh"
    },
    {
        id: "sarod",
        name: "Sarod",
        category: "String Instruments",
        region: "North India",
        image: "assets/sarod.jpg",
        audio: "assets/audio/sarod.mp3",
        description: "A fretless, plucked string instrument known for its deep, weighty, and introspective sound.",
        history: "Adapted from the Afghan rubab in the 19th century by musicians in the royal courts of Awadh and Gwalior.",
        construction: "Has a wooden body with a skin belly and a fretless steel fingerboard. Contains 4 main playing strings, drone strings, and numerous sympathetic strings.",
        playingTechnique: "Plucked with a coconut shell plectrum (java). The lack of frets allows for continuous slides (meend) between notes.",
        musicalTradition: "Hindustani Classical",
        notableExponents: "Ali Akbar Khan, Amjad Ali Khan"
    },
    {
        id: "santoor",
        name: "Santoor",
        category: "String Instruments",
        region: "Kashmir",
        image: "assets/santoor.jpg",
        audio: "assets/audio/santoor.mp3",
        description: "A hammered dulcimer that produces a shimmering, echoing sound reminiscent of water droplets.",
        history: "Originally a folk instrument from the Kashmir valley used in Sufiana Kalam, it was adapted for classical music in the mid-20th century.",
        construction: "A trapezoidal wooden box (walnut or maple) strung with up to 100 steel strings stretched over wooden bridges.",
        playingTechnique: "Played while seated, striking the strings with a pair of curved wooden mallets (mezrab).",
        musicalTradition: "Hindustani Classical, Sufi, Folk",
        notableExponents: "Shivkumar Sharma, Bhajan Sopori"
    },
    {
        id: "shehnai",
        name: "Shehnai",
        category: "Wind Instruments",
        region: "North India",
        image: "assets/shehnai.jpg",
        audio: "assets/audio/shehnai.mp3",
        description: "A double-reed oboe-like instrument traditionally associated with auspicious occasions, weddings, and temples.",
        history: "Evolved from traditional folk reed instruments; it was brought to the concert stage as a respected classical instrument in the 20th century.",
        construction: "Made of wood with a metal flare bell at the end, containing 6 to 9 holes and a double reed.",
        playingTechnique: "Requires immense breath control and circular breathing. Pitch is bent by adjusting lip pressure and finger placement.",
        musicalTradition: "Hindustani Classical, Devotional, Folk",
        notableExponents: "Bismillah Khan, Ali Ahmad Hussain Khan"
    },
    {
        id: "mridangam",
        name: "Mridangam",
        category: "Percussion Instruments",
        region: "South India",
        image: "assets/mridangam.jpg",
        audio: "assets/audio/mridangam.mp3",
        description: "An ancient double-sided drum that is the primary rhythmic accompaniment in Carnatic music.",
        history: "Its name derives from 'mrid' (clay) and 'ang' (body), pointing to its ancient origins. Depicted in early temple sculptures and Hindu mythology.",
        construction: "A barrel-shaped wooden shell covered with multiple layers of leather. The right head has a permanent tuning paste, while the left head uses a temporary semolina paste for lower tones.",
        playingTechnique: "Played with hands and fingers on both sides simultaneously, producing complex cross-rhythms and tonal variations.",
        musicalTradition: "Carnatic Classical",
        notableExponents: "Palghat Mani Iyer, Umayalpuram K. Sivaraman"
    },
    {
        id: "tanpura",
        name: "Tanpura",
        category: "Drone Instruments",
        region: "All India",
        image: "assets/tanpura.jpg",
        audio: "assets/audio/tanpura.mp3",
        description: "A long-necked plucked drone instrument that provides the foundational harmonic background (shruti) for singers and instrumentalists.",
        history: "A crucial evolution in Indian music that allowed the establishment of a continuous, unchanging tonic pitch against which ragas are developed.",
        construction: "Fretless, usually with four strings, a wooden neck, and a large gourd resonator. Small threads (jivari) under the strings create a rich buzzing overtone spectrum.",
        playingTechnique: "Strings are plucked continuously in a gentle, rhythmic loop, not to play melodies, but to sustain the drone.",
        musicalTradition: "Hindustani and Carnatic Classical",
        notableExponents: "Traditionally played by accompanists or students."
    }
];
