/**
 * Smart Local Transportation Planner
 * Static transportation dataset.
 */

const TRANSPORTATION_DATA = {

    Delhi: [
        {
            id: "delhi-metro",
            name: "Delhi Metro",
            type: "metro",
            icon: "🚇",
            costMin: 10,
            costMax: 60,
            duration: 25,
            hours: "05:30 AM – 11:30 PM",
            accessibility: "yes",
            accessibilityText: "Accessible stations, elevators and reserved spaces",
            ecoScore: 5,
            convenience: 5,
            description: "Fast and reliable way to travel across Delhi and NCR.",
            suitableFor: ["Long distances", "Airport travel", "Budget travel"]
        },
        {
            id: "delhi-bus",
            name: "DTC / Cluster Bus",
            type: "bus",
            icon: "🚌",
            costMin: 10,
            costMax: 40,
            duration: 45,
            hours: "05:00 AM – 11:00 PM",
            accessibility: "partial",
            accessibilityText: "Accessibility varies by bus and route",
            ecoScore: 4,
            convenience: 4,
            description: "Affordable buses connecting major neighborhoods.",
            suitableFor: ["Budget travel", "Local routes"]
        },
        {
            id: "delhi-auto",
            name: "Auto-rickshaw",
            type: "auto",
            icon: "🛺",
            costMin: 40,
            costMax: 250,
            duration: 25,
            hours: "24 hours",
            accessibility: "partial",
            accessibilityText: "Limited wheelchair accommodation",
            ecoScore: 3,
            convenience: 4,
            description: "Convenient for short-distance city travel.",
            suitableFor: ["Short distances", "Last-mile travel"]
        },
        {
            id: "delhi-taxi",
            name: "Taxi / Cab",
            type: "taxi",
            icon: "🚕",
            costMin: 120,
            costMax: 600,
            duration: 25,
            hours: "24 hours",
            accessibility: "partial",
            accessibilityText: "Accessible vehicles available on request",
            ecoScore: 2,
            convenience: 5,
            description: "Door-to-door travel with high convenience.",
            suitableFor: ["Families", "Luggage", "Late-night travel"]
        }
    ],

    Mumbai: [
        {
            id: "mumbai-local",
            name: "Mumbai Local Train",
            type: "train",
            icon: "🚆",
            costMin: 5,
            costMax: 50,
            duration: 30,
            hours: "04:00 AM – 01:00 AM",
            accessibility: "partial",
            accessibilityText: "Accessibility facilities available at selected stations",
            ecoScore: 5,
            convenience: 5,
            description: "One of Mumbai's most important public transport systems.",
            suitableFor: ["Long distances", "Budget travel", "Daily commuting"]
        },
        {
            id: "mumbai-metro",
            name: "Mumbai Metro",
            type: "metro",
            icon: "🚇",
            costMin: 10,
            costMax: 50,
            duration: 25,
            hours: "05:30 AM – 11:00 PM",
            accessibility: "yes",
            accessibilityText: "Elevators, ramps and accessible stations",
            ecoScore: 5,
            convenience: 5,
            description: "Modern rapid transit connecting major areas.",
            suitableFor: ["Sightseeing", "Long distances"]
        },
        {
            id: "mumbai-auto",
            name: "Auto-rickshaw",
            type: "auto",
            icon: "🛺",
            costMin: 30,
            costMax: 250,
            duration: 20,
            hours: "06:00 AM – 12:00 AM",
            accessibility: "partial",
            accessibilityText: "Limited accessibility",
            ecoScore: 3,
            convenience: 4,
            description: "Useful for short city journeys.",
            suitableFor: ["Short distances", "Last-mile travel"]
        },
        {
            id: "mumbai-ferry",
            name: "Mumbai Harbour Ferry",
            type: "ferry",
            icon: "⛴️",
            costMin: 50,
            costMax: 300,
            duration: 60,
            hours: "07:00 AM – 07:00 PM",
            accessibility: "partial",
            accessibilityText: "Accessibility depends on terminal and vessel",
            ecoScore: 4,
            convenience: 3,
            description: "Scenic water transportation across Mumbai Harbour.",
            suitableFor: ["Sightseeing", "Island travel"]
        }
    ],

    Bengaluru: [
        {
            id: "blr-metro",
            name: "Namma Metro",
            type: "metro",
            icon: "🚇",
            costMin: 10,
            costMax: 60,
            duration: 30,
            hours: "05:00 AM – 11:00 PM",
            accessibility: "yes",
            accessibilityText: "Elevators, ramps and accessible stations",
            ecoScore: 5,
            convenience: 5,
            description: "Efficient metro service for Bengaluru.",
            suitableFor: ["Long distances", "Budget travel"]
        },
        {
            id: "blr-bus",
            name: "BMTC Bus",
            type: "bus",
            icon: "🚌",
            costMin: 10,
            costMax: 60,
            duration: 50,
            hours: "05:00 AM – 11:00 PM",
            accessibility: "partial",
            accessibilityText: "Accessibility depends on bus type",
            ecoScore: 4,
            convenience: 4,
            description: "Extensive bus network covering Bengaluru.",
            suitableFor: ["Local travel", "Budget travel"]
        },
        {
            id: "blr-auto",
            name: "Auto-rickshaw",
            type: "auto",
            icon: "🛺",
            costMin: 40,
            costMax: 300,
            duration: 25,
            hours: "24 hours",
            accessibility: "partial",
            accessibilityText: "Limited wheelchair access",
            ecoScore: 3,
            convenience: 4,
            description: "Convenient option for short trips.",
            suitableFor: ["Short distances", "Last-mile travel"]
        }
    ],

    Kolkata: [
        {
            id: "kolkata-metro",
            name: "Kolkata Metro",
            type: "metro",
            icon: "🚇",
            costMin: 10,
            costMax: 40,
            duration: 30,
            hours: "06:45 AM – 10:30 PM",
            accessibility: "yes",
            accessibilityText: "Accessible stations and elevators available",
            ecoScore: 5,
            convenience: 5,
            description: "A convenient rapid transit network.",
            suitableFor: ["Long distances", "Budget travel"]
        },
        {
            id: "kolkata-tram",
            name: "Kolkata Tram",
            type: "train",
            icon: "🚋",
            costMin: 7,
            costMax: 20,
            duration: 45,
            hours: "06:00 AM – 10:00 PM",
            accessibility: "partial",
            accessibilityText: "Accessibility varies by tram",
            ecoScore: 5,
            convenience: 3,
            description: "Historic electric tram transportation.",
            suitableFor: ["Sightseeing", "Heritage experience"]
        },
        {
            id: "kolkata-bus",
            name: "Public Bus",
            type: "bus",
            icon: "🚌",
            costMin: 10,
            costMax: 40,
            duration: 45,
            hours: "05:00 AM – 11:00 PM",
            accessibility: "partial",
            accessibilityText: "Accessibility varies",
            ecoScore: 4,
            convenience: 4,
            description: "Affordable city-wide bus transportation.",
            suitableFor: ["Budget travel", "Local routes"]
        },
        {
            id: "kolkata-ferry",
            name: "Hooghly Ferry",
            type: "ferry",
            icon: "⛴️",
            costMin: 10,
            costMax: 30,
            duration: 25,
            hours: "06:00 AM – 09:00 PM",
            accessibility: "partial",
            accessibilityText: "Accessibility varies by terminal",
            ecoScore: 4,
            convenience: 4,
            description: "River transport across the Hooghly.",
            suitableFor: ["River crossing", "Sightseeing"]
        }
    ],

    Jaipur: [
        {
            id: "jaipur-metro",
            name: "Jaipur Metro",
            type: "metro",
            icon: "🚇",
            costMin: 10,
            costMax: 30,
            duration: 20,
            hours: "06:00 AM – 10:00 PM",
            accessibility: "yes",
            accessibilityText: "Accessible stations and elevators",
            ecoScore: 5,
            convenience: 4,
            description: "Rapid transit for selected parts of Jaipur.",
            suitableFor: ["Budget travel", "City travel"]
        },
        {
            id: "jaipur-auto",
            name: "Auto-rickshaw",
            type: "auto",
            icon: "🛺",
            costMin: 40,
            costMax: 250,
            duration: 25,
            hours: "24 hours",
            accessibility: "partial",
            accessibilityText: "Limited accessibility",
            ecoScore: 3,
            convenience: 5,
            description: "Popular transport for tourists.",
            suitableFor: ["Short distances", "Sightseeing"]
        },
        {
            id: "jaipur-taxi",
            name: "Taxi / Cab",
            type: "taxi",
            icon: "🚕",
            costMin: 150,
            costMax: 700,
            duration: 25,
            hours: "24 hours",
            accessibility: "partial",
            accessibilityText: "Accessible vehicles may be requested",
            ecoScore: 2,
            convenience: 5,
            description: "Comfortable door-to-door travel.",
            suitableFor: ["Families", "Luggage", "Sightseeing"]
        }
    ],

    Hyderabad: [
        {
            id: "hyd-metro",
            name: "Hyderabad Metro",
            type: "metro",
            icon: "🚇",
            costMin: 10,
            costMax: 60,
            duration: 30,
            hours: "06:00 AM – 11:00 PM",
            accessibility: "yes",
            accessibilityText: "Accessible stations and elevators",
            ecoScore: 5,
            convenience: 5,
            description: "Fast transportation across major corridors.",
            suitableFor: ["Long distances", "Budget travel"]
        },
        {
            id: "hyd-bus",
            name: "TSRTC Bus",
            type: "bus",
            icon: "🚌",
            costMin: 10,
            costMax: 50,
            duration: 45,
            hours: "05:00 AM – 11:00 PM",
            accessibility: "partial",
            accessibilityText: "Accessibility varies by bus",
            ecoScore: 4,
            convenience: 4,
            description: "Affordable public bus transportation.",
            suitableFor: ["Budget travel", "Local routes"]
        },
        {
            id: "hyd-auto",
            name: "Auto-rickshaw",
            type: "auto",
            icon: "🛺",
            costMin: 40,
            costMax: 250,
            duration: 25,
            hours: "24 hours",
            accessibility: "partial",
            accessibilityText: "Limited accessibility",
            ecoScore: 3,
            convenience: 4,
            description: "Common option for short journeys.",
            suitableFor: ["Short distances", "Last-mile travel"]
        }
    ],

    Goa: [
        {
            id: "goa-bus",
            name: "Kadamba Bus",
            type: "bus",
            icon: "🚌",
            costMin: 10,
            costMax: 80,
            duration: 50,
            hours: "06:00 AM – 09:00 PM",
            accessibility: "partial",
            accessibilityText: "Accessibility varies",
            ecoScore: 4,
            convenience: 3,
            description: "Affordable public transport around Goa.",
            suitableFor: ["Budget travel", "Local travel"]
        },
        {
            id: "goa-taxi",
            name: "Taxi",
            type: "taxi",
            icon: "🚕",
            costMin: 150,
            costMax: 1000,
            duration: 30,
            hours: "24 hours",
            accessibility: "partial",
            accessibilityText: "Accessible vehicles available on request",
            ecoScore: 2,
            convenience: 5,
            description: "Convenient option for beaches and attractions.",
            suitableFor: ["Families", "Beach hopping", "Luggage"]
        },
        {
            id: "goa-bike",
            name: "Bicycle / Rental Bike",
            type: "bike",
            icon: "🚲",
            costMin: 100,
            costMax: 500,
            duration: 35,
            hours: "06:00 AM – 09:00 PM",
            accessibility: "partial",
            accessibilityText: "Not suitable for all mobility requirements",
            ecoScore: 5,
            convenience: 4,
            description: "Eco-friendly option for exploring Goa.",
            suitableFor: ["Short distances", "Eco travel", "Sightseeing"]
        }
    ],

    Kochi: [
        {
            id: "kochi-metro",
            name: "Kochi Metro",
            type: "metro",
            icon: "🚇",
            costMin: 10,
            costMax: 60,
            duration: 30,
            hours: "06:00 AM – 11:00 PM",
            accessibility: "yes",
            accessibilityText: "Elevators, ramps and accessible stations",
            ecoScore: 5,
            convenience: 5,
            description: "Modern metro network connecting Kochi.",
            suitableFor: ["Long distances", "Budget travel"]
        },
        {
            id: "kochi-ferry",
            name: "Kochi Water Metro",
            type: "ferry",
            icon: "⛴️",
            costMin: 20,
            costMax: 40,
            duration: 25,
            hours: "07:00 AM – 08:00 PM",
            accessibility: "yes",
            accessibilityText: "Designed with accessibility features",
            ecoScore: 5,
            convenience: 5,
            description: "Modern water-based public transportation.",
            suitableFor: ["Island travel", "Sightseeing", "Eco travel"]
        },
        {
            id: "kochi-bus",
            name: "KSRTC / City Bus",
            type: "bus",
            icon: "🚌",
            costMin: 10,
            costMax: 50,
            duration: 45,
            hours: "05:00 AM – 11:00 PM",
            accessibility: "partial",
            accessibilityText: "Accessibility varies",
            ecoScore: 4,
            convenience: 4,
            description: "Extensive bus network around Kochi.",
            suitableFor: ["Budget travel", "Local routes"]
        }
    ]
};

const TRANSPORT_DESTINATIONS = Object.keys(TRANSPORTATION_DATA);