/* ==========================================================================
   MAJOR DAMS & RIVER VALLEY PROJECTS OF INDIA — DATASET

   Heights, storage volumes and installed capacities are drawn from published
   project figures and are approximate. Several are measured differently by
   different authorities — "height" may be above the deepest foundation or
   above the river bed, and installed capacity changes as units are added or
   derated. Displacement figures are contested and are given as ranges.
   ========================================================================== */

const DM_BASINS = [
  { key: 'indus', name: 'Indus System', icon: '🏔️', blurb: 'Sutlej, Beas, Ravi, Chenab and Jhelum — governed by the Indus Waters Treaty.' },
  { key: 'ganga', name: 'Ganga Basin', icon: '🛕', blurb: 'The Bhagirathi, Yamuna, Chambal, Betwa, Son and Koel.' },
  { key: 'narmada', name: 'Narmada & Tapti', icon: '🌊', blurb: 'The west-flowing rivers of central India.' },
  { key: 'godavari', name: 'Godavari & Krishna', icon: '🌾', blurb: 'The two largest peninsular systems, and the most disputed.' },
  { key: 'mahanadi', name: 'Mahanadi & East Coast', icon: '🌅', blurb: 'Odisha and the eastern seaboard.' },
  { key: 'south', name: 'Cauvery & Southern Rivers', icon: '🌴', blurb: 'Cauvery, Periyar, Bhavani and the Kerala rivers.' },
];

const DM_PURPOSES = [
  { key: 'multipurpose', name: 'Multipurpose', icon: '⚙️' },
  { key: 'irrigation', name: 'Irrigation-led', icon: '🌾' },
  { key: 'hydro', name: 'Hydropower-led', icon: '⚡' },
  { key: 'supply', name: 'Water Supply / Flood Control', icon: '🚰' },
];

const DM_TYPES = [
  {
    key: 'gravity',
    name: 'Gravity Dam',
    icon: '🧱',
    desc: 'Holds water back by sheer mass — the weight of concrete or masonry resists the push of the reservoir. Needs a sound rock foundation and a great deal of material, but is simple to analyse and durable. Bhakra and Nagarjuna Sagar are gravity dams.',
    examples: 'Bhakra, Nagarjuna Sagar, Sardar Sarovar',
  },
  {
    key: 'embankment',
    name: 'Embankment Dam',
    icon: '⛰️',
    desc: 'Built from compacted earth or rock fill with an impervious core. Uses locally available material and tolerates weaker foundations, which makes it the most common dam type in India by number — but it cannot survive being overtopped.',
    examples: 'Tehri, Rihand, Hirakud (composite)',
  },
  {
    key: 'arch',
    name: 'Arch Dam',
    icon: '🌉',
    desc: 'A curved shell that transfers load into the canyon walls rather than into its own base. Uses far less material than a gravity dam of the same height, but requires a narrow gorge with strong abutments. Rare in India — Idukki is the standout.',
    examples: 'Idukki, Chera',
  },
  {
    key: 'barrage',
    name: 'Barrage / Weir',
    icon: '🚧',
    desc: 'A low, gated structure that raises the water level to divert flow into canals rather than to store it. Farakka and the Kallanai are barrages in function — they manage where water goes, not how much is kept.',
    examples: 'Farakka, Kallanai, Durgapur',
  },
];

/* -------------------------------------------------------------- the dams */
const DAMS = [
  {
    name: 'Bhakra Dam',
    icon: '⚡',
    river: 'Sutlej',
    state: 'Himachal Pradesh (serving Punjab, Haryana, Rajasthan)',
    basin: 'indus',
    type: 'gravity',
    purpose: 'multipurpose',
    heightM: 226,
    capacityMW: 1325,
    storageMcm: 9340,
    commissioned: 1963,
    reservoir: 'Gobind Sagar',
    tagline: 'The dam Nehru called a temple of modern India',
    desc: 'Bhakra is the project the phrase was coined for — Nehru used it at the 1954 canal-water dedication. Together with the Nangal barrage downstream it made large-scale irrigation possible across Punjab, Haryana and northern Rajasthan, and it underwrote the Green Revolution in the region more directly than any other single structure. It remains among the highest gravity dams in the world.',
    impact: 'The Bhakra-Nangal system irrigates a very large command area across three states and supplies power to the northern grid. Around 36,000 people were displaced from the Bilaspur area, and the old town of Bilaspur was submerged.',
    note: 'Sedimentation has reduced live storage since commissioning, which is the standard fate of large reservoirs and is rarely factored into original project economics.',
  },
  {
    name: 'Hirakud Dam',
    icon: '📏',
    river: 'Mahanadi',
    state: 'Odisha',
    basin: 'mahanadi',
    type: 'embankment',
    purpose: 'multipurpose',
    heightM: 61,
    capacityMW: 348,
    storageMcm: 5896,
    commissioned: 1957,
    reservoir: 'Hirakud Reservoir',
    tagline: 'The longest major earthen dam in the world',
    desc: 'At roughly 26 km including its dykes, Hirakud is the longest major earthen dam anywhere. It was built primarily for flood control on the Mahanadi, which had repeatedly devastated coastal Odisha, and it has substantially moderated the delta flooding that prompted it. It was among the first major river valley projects taken up after independence.',
    impact: 'Flood moderation across the Mahanadi delta, irrigation in Sambalpur and Bargarh, and power for Odisha. Displacement is generally put in the range of 150,000 people from roughly 250 villages; rehabilitation was incomplete and remains a live grievance.',
    note: 'Hirakud is frequently cited in the resettlement literature as the case that established how badly early Indian projects handled displacement.',
  },
  {
    name: 'Sardar Sarovar Dam',
    icon: '⚖️',
    river: 'Narmada',
    state: 'Gujarat (benefiting Gujarat, MP, Maharashtra, Rajasthan)',
    basin: 'narmada',
    type: 'gravity',
    purpose: 'multipurpose',
    heightM: 163,
    capacityMW: 1450,
    storageMcm: 9500,
    commissioned: 2006,
    reservoir: 'Sardar Sarovar Reservoir',
    tagline: 'India\'s most contested dam',
    desc: 'The terminal dam of the Narmada Valley Development Project and the focus of the Narmada Bachao Andolan, one of the longest-running social movements in independent India. The World Bank withdrew from the project in 1993 after the Morse Commission found its resettlement and environmental provisions inadequate. Construction was halted by the Supreme Court in 1995 and allowed to resume in 2000 with conditions on rehabilitation.',
    impact: 'Irrigation across a large command in Gujarat and Rajasthan, drinking water to hundreds of towns and villages, and power shared between three states. Displacement estimates range widely — commonly cited figures run from around 40,000 families upward — and rehabilitation across three states has been disputed for four decades.',
    note: 'Whichever view one takes of the project, it changed Indian practice: environmental clearance, rehabilitation policy and the role of the courts in infrastructure all look different because of it.',
  },
  {
    name: 'Tehri Dam',
    icon: '🏔️',
    river: 'Bhagirathi',
    state: 'Uttarakhand',
    basin: 'ganga',
    type: 'embankment',
    purpose: 'multipurpose',
    heightM: 260,
    capacityMW: 2400,
    storageMcm: 3540,
    commissioned: 2006,
    reservoir: 'Tehri Reservoir',
    tagline: 'India\'s tallest dam, in a seismic zone',
    desc: 'At 260 m Tehri is the tallest dam in India and among the tallest anywhere. It is a rock-and-earth fill structure on the Bhagirathi, one of the two headstreams of the Ganga. Its pumped-storage plant lets it serve as grid balancing capacity as well as generation. The old town of Tehri was submerged and rebuilt as New Tehri on higher ground.',
    impact: 'Power for the northern grid, irrigation in western Uttar Pradesh, and drinking water for Delhi. Around 100,000 people were affected across the town and surrounding villages.',
    note: 'Tehri sits in Seismic Zone IV. The seismic design was contested through the entire construction period and remains the most-cited concern about the project.',
  },
  {
    name: 'Nagarjuna Sagar Dam',
    icon: '🧱',
    river: 'Krishna',
    state: 'Telangana & Andhra Pradesh',
    basin: 'godavari',
    type: 'gravity',
    purpose: 'multipurpose',
    heightM: 124,
    capacityMW: 816,
    storageMcm: 11560,
    commissioned: 1967,
    reservoir: 'Nagarjuna Sagar',
    tagline: 'The largest masonry dam in the world when built',
    desc: 'Nagarjuna Sagar was the largest masonry dam in the world at completion and was built substantially by hand — the labour force ran into the tens of thousands. It irrigates a very large command across Telangana and Andhra Pradesh. The Buddhist site of Nagarjunakonda lay in the submergence zone and its principal monuments were excavated, dismantled and re-erected on a hilltop island in the reservoir.',
    impact: 'One of India\'s largest irrigation commands. The archaeological rescue at Nagarjunakonda is among the most substantial such operations undertaken in India.',
    note: 'Water sharing between Telangana and Andhra Pradesh at Nagarjuna Sagar has been a recurring point of dispute since the 2014 bifurcation.',
  },
  {
    name: 'Idukki Dam',
    icon: '🌉',
    river: 'Periyar',
    state: 'Kerala',
    basin: 'south',
    type: 'arch',
    purpose: 'hydro',
    heightM: 168,
    capacityMW: 780,
    storageMcm: 1996,
    commissioned: 1976,
    reservoir: 'Idukki Reservoir',
    tagline: 'Asia\'s first double-curvature arch dam',
    desc: 'Built across a narrow gorge between the Kuravan and Kurathi hills, Idukki was Asia\'s first double-curvature arch dam and remains one of the highest. Its shape uses a fraction of the material a gravity dam of the same height would need. The power station is underground, and the project is the backbone of Kerala\'s hydroelectric capacity.',
    impact: 'The largest single source of hydroelectric power in Kerala, in a state with limited thermal capacity of its own.',
    note: 'Idukki\'s narrow gorge site is what makes the arch form possible — most Indian dam sites do not offer the abutments an arch dam needs.',
  },
  {
    name: 'Rihand Dam',
    icon: '💧',
    river: 'Rihand (Son tributary)',
    state: 'Uttar Pradesh',
    basin: 'ganga',
    type: 'gravity',
    purpose: 'multipurpose',
    heightM: 91,
    capacityMW: 300,
    storageMcm: 10600,
    commissioned: 1962,
    reservoir: 'Govind Ballabh Pant Sagar',
    tagline: 'India\'s largest reservoir by surface area',
    desc: 'Rihand created Govind Ballabh Pant Sagar, the largest artificial reservoir in India by surface area. The reservoir anchors the Singrauli industrial and thermal power complex, one of the largest concentrations of coal-fired generation in the country, which draws its cooling water from it.',
    impact: 'Power, irrigation and industrial water supply. The Singrauli region that grew around it is also one of India\'s most heavily polluted industrial areas, which is part of the project\'s legacy.',
    note: 'The dam is often described as a hydropower project, but its greater significance is as the water source for a thermal power cluster many times its own generating capacity.',
  },
  {
    name: 'Indira Sagar Dam',
    icon: '🗺️',
    river: 'Narmada',
    state: 'Madhya Pradesh',
    basin: 'narmada',
    type: 'gravity',
    purpose: 'multipurpose',
    heightM: 92,
    capacityMW: 1000,
    storageMcm: 12220,
    commissioned: 2005,
    reservoir: 'Indira Sagar',
    tagline: 'The largest reservoir in India by storage volume',
    desc: 'Indira Sagar holds the largest volume of water of any reservoir in India. It is the upstream storage of the Narmada Valley Development Project and regulates the flow reaching Omkareshwar, Sardar Sarovar and the downstream command. Its very large submergence area is the direct consequence of the storage it provides.',
    impact: 'Regulates the entire lower Narmada system. Submergence covered a substantial number of villages in Khandwa and adjoining districts, with the associated rehabilitation disputes.',
    note: 'Largest reservoir by volume and largest by surface area are different titles — Indira Sagar holds the first, Rihand\'s Govind Ballabh Pant Sagar the second.',
  },
  {
    name: 'Koyna Dam',
    icon: '🌍',
    river: 'Koyna',
    state: 'Maharashtra',
    basin: 'godavari',
    type: 'gravity',
    purpose: 'hydro',
    heightM: 103,
    capacityMW: 1960,
    storageMcm: 2797,
    commissioned: 1964,
    reservoir: 'Shivsagar',
    tagline: 'The best-documented case of reservoir-induced seismicity',
    desc: 'Koyna is Maharashtra\'s largest hydroelectric complex. It is better known internationally for the magnitude 6.3 earthquake that struck near the reservoir in December 1967, killing around 180 people. It is among the most-studied candidate cases of reservoir-triggered seismicity anywhere, and a deep borehole observatory has since been established in the region to study it.',
    impact: 'A major share of Maharashtra\'s hydro capacity, feeding the western grid.',
    note: 'Reservoir-induced seismicity remains debated in general, but Koyna is the case most often cited on the affirmative side.',
  },
  {
    name: 'Kallanai (Grand Anicut)',
    icon: '🏛️',
    river: 'Cauvery',
    state: 'Tamil Nadu',
    basin: 'south',
    type: 'barrage',
    purpose: 'irrigation',
    heightM: 5,
    capacityMW: 0,
    storageMcm: 0,
    commissioned: 200,
    reservoir: 'Run-of-river diversion',
    tagline: 'Roughly 1,800 years old and still in service',
    desc: 'Built by the Chola king Karikalan, conventionally dated to around the second century CE, the Kallanai diverts the Cauvery into the delta distributary system. It is among the oldest water-diversion structures anywhere still performing its original function. The British engineer Arthur Cotton studied it in the nineteenth century and used its principles in his own delta works on the Godavari and Krishna.',
    impact: 'Underpins irrigation across the Cauvery delta, the agricultural core of Tamil Nadu, and has done so for the better part of two millennia.',
    note: 'The commissioning year here is approximate and conventional; the structure has been repaired and extended many times, most substantially in the nineteenth century.',
  },
  {
    name: 'Mettur Dam',
    icon: '🌾',
    river: 'Cauvery',
    state: 'Tamil Nadu',
    basin: 'south',
    type: 'gravity',
    purpose: 'multipurpose',
    heightM: 65,
    capacityMW: 240,
    storageMcm: 2648,
    commissioned: 1934,
    reservoir: 'Stanley Reservoir',
    tagline: 'The pre-independence dam that still sets the delta calendar',
    desc: 'Completed in 1934, Mettur was one of the largest dams in the world at the time. The date of its annual opening for irrigation still effectively sets the sowing calendar for the Cauvery delta, which is why that date is a political question in Tamil Nadu every year and not merely an administrative one.',
    impact: 'Irrigation for the delta districts, power for Tamil Nadu, and drinking water supply.',
    note: 'Mettur sits at the centre of the Cauvery dispute, since what it can release depends on what Karnataka releases upstream.',
  },
  {
    name: 'Srisailam Dam',
    icon: '⚡',
    river: 'Krishna',
    state: 'Andhra Pradesh & Telangana',
    basin: 'godavari',
    type: 'gravity',
    purpose: 'hydro',
    heightM: 145,
    capacityMW: 1670,
    storageMcm: 8722,
    commissioned: 1981,
    reservoir: 'Srisailam Reservoir',
    tagline: 'A major hydro station inside a tiger reserve',
    desc: 'Srisailam sits in the Nallamala hills within the Nagarjunsagar-Srisailam Tiger Reserve, the largest tiger reserve in India. It was conceived as a pure hydroelectric project and later given an irrigation role. Its position inside a protected area makes it a standing example of the tension between energy infrastructure and habitat protection.',
    impact: 'One of the largest hydroelectric stations in southern India, with left and right bank powerhouses serving Telangana and Andhra Pradesh respectively.',
    note: 'Water releases from Srisailam are a recurring point of contention between the two successor states.',
  },
  {
    name: 'Bhavanisagar Dam',
    icon: '🌊',
    river: 'Bhavani',
    state: 'Tamil Nadu',
    basin: 'south',
    type: 'embankment',
    purpose: 'irrigation',
    heightM: 32,
    capacityMW: 32,
    storageMcm: 932,
    commissioned: 1955,
    reservoir: 'Bhavanisagar',
    tagline: 'Among the largest earthen dams in the country',
    desc: 'Bhavanisagar is one of India\'s largest earth dams, built across the Bhavani in the Erode district. Its command area supports intensive cultivation in one of Tamil Nadu\'s more productive agricultural belts, and it was one of the earliest major post-independence irrigation projects completed in the south.',
    impact: 'Irrigation across the lower Bhavani command, with a modest generating station attached.',
    note: '',
  },
  {
    name: 'Farakka Barrage',
    icon: '🚧',
    river: 'Ganga',
    state: 'West Bengal',
    basin: 'ganga',
    type: 'barrage',
    purpose: 'supply',
    heightM: 21,
    capacityMW: 0,
    storageMcm: 0,
    commissioned: 1975,
    reservoir: 'Run-of-river diversion',
    tagline: 'A structure built to save a port, and a diplomatic problem for fifty years',
    desc: 'Farakka diverts Ganga water into the Bhagirathi-Hooghly to flush silt from the approach to Kolkata port. It is a barrage rather than a storage dam — it changes where water goes, not how much is kept. Its downstream effect on flows into Bangladesh made it a bilateral issue from the moment it was commissioned, addressed by the Ganges Water Sharing Treaty of 1996.',
    impact: 'Maintains navigability at Kolkata port. Downstream effects in Bangladesh, and changes to fish migration — particularly hilsa — are the enduring criticisms.',
    note: 'Farakka is the standard example of why a low structure with no storage can matter more politically than a very large dam.',
  },
  {
    name: 'Tungabhadra Dam',
    icon: '🌾',
    river: 'Tungabhadra',
    state: 'Karnataka (shared with Andhra Pradesh)',
    basin: 'godavari',
    type: 'gravity',
    purpose: 'multipurpose',
    heightM: 49,
    capacityMW: 72,
    storageMcm: 3766,
    commissioned: 1953,
    reservoir: 'Pampa Sagar',
    tagline: 'An interstate project agreed before the states existed in their present form',
    desc: 'Tungabhadra was planned jointly by Hyderabad and Madras before reorganisation and is now operated as a Karnataka–Andhra Pradesh joint project through a dedicated board. It irrigates a large command in the dry Raichur and Bellary districts, and is one of the earliest examples of a formal interstate operating arrangement in India.',
    impact: 'Irrigation in one of the drier parts of the Deccan, plus power. Sedimentation has reduced its live storage substantially since commissioning.',
    note: 'The loss of live storage at Tungabhadra is one of the most frequently cited Indian examples of reservoir sedimentation.',
  },
  {
    name: 'Nizam Sagar',
    icon: '🕌',
    river: 'Manjira',
    state: 'Telangana',
    basin: 'godavari',
    type: 'gravity',
    purpose: 'irrigation',
    heightM: 43,
    capacityMW: 10,
    storageMcm: 841,
    commissioned: 1931,
    reservoir: 'Nizam Sagar',
    tagline: 'A princely-state project from before independence',
    desc: 'Built by the Nizam of Hyderabad and completed in 1931, Nizam Sagar predates the post-independence dam programme by two decades and shows that large-scale water engineering in India was well under way before it. Its masonry aqueduct across the Manjira was considered a significant engineering work at the time.',
    impact: 'Irrigation across Nizamabad and adjoining districts; also supplies water to Hyderabad.',
    note: 'Upstream development on the Manjira has reduced the inflow the project was designed around.',
  },
  {
    name: 'Krishna Raja Sagara (KRS)',
    icon: '💐',
    river: 'Cauvery',
    state: 'Karnataka',
    basin: 'south',
    type: 'gravity',
    purpose: 'multipurpose',
    heightM: 39,
    capacityMW: 49,
    storageMcm: 1369,
    commissioned: 1932,
    reservoir: 'Krishna Raja Sagara',
    tagline: 'Visvesvaraya\'s dam, and the upstream half of the Cauvery dispute',
    desc: 'Designed under M. Visvesvaraya for the Mysore state and completed in 1932, KRS was built without cement — using surki mortar, a lime-and-brick-dust mix. It irrigates the Mandya belt and supplies water to Mysuru and Bengaluru. Because it sits upstream of Mettur, what KRS holds and what it releases is the operative question in the Cauvery dispute.',
    impact: 'Irrigation in southern Karnataka and drinking water for two major cities. The Brindavan Gardens below the dam are among the most visited sites in the state.',
    note: 'KRS and Mettur are best read as two halves of one problem rather than as separate projects.',
  },
  {
    name: 'Bhakra-adjacent: Pong Dam',
    icon: '🦆',
    river: 'Beas',
    state: 'Himachal Pradesh',
    basin: 'indus',
    type: 'embankment',
    purpose: 'multipurpose',
    heightM: 133,
    capacityMW: 396,
    storageMcm: 8570,
    commissioned: 1974,
    reservoir: 'Maharana Pratap Sagar',
    tagline: 'A hydro reservoir that became a Ramsar wetland',
    desc: 'Pong is an earth-fill dam on the Beas whose reservoir, Maharana Pratap Sagar, became one of India\'s most important wintering grounds for migratory waterfowl and was designated a Ramsar site in 2002. It is a rare instance of a large reservoir acquiring genuine conservation value rather than only ecological cost.',
    impact: 'Irrigation in Punjab and Rajasthan, power for the northern grid, and internationally significant waterbird habitat. Around 30,000 people were displaced, many resettled in Rajasthan.',
    note: 'The resettlement of Pong oustees into the Rajasthan canal command was troubled and is still cited in the rehabilitation literature.',
  },
  {
    name: 'Ukai Dam',
    icon: '🌊',
    river: 'Tapti',
    state: 'Gujarat',
    basin: 'narmada',
    type: 'embankment',
    purpose: 'multipurpose',
    heightM: 69,
    capacityMW: 305,
    storageMcm: 8511,
    commissioned: 1972,
    reservoir: 'Ukai Reservoir',
    tagline: 'Surat\'s flood defence, and the source of its worst flood',
    desc: 'Ukai is one of the largest reservoirs in Gujarat and was built partly to protect Surat from Tapti flooding. In August 2006 an emergency release during exceptional inflows contributed to the most severe flood Surat has recorded, which made Ukai a standard case study in reservoir operating rules and flood-cushion management.',
    impact: 'Irrigation, power and industrial water supply for south Gujarat.',
    note: 'The 2006 event is usually attributed to operating decisions and rainfall rather than to the structure, and it changed how flood cushions are managed on the Tapti.',
  },
  {
    name: 'Gandhi Sagar Dam',
    icon: '🏞️',
    river: 'Chambal',
    state: 'Madhya Pradesh',
    basin: 'ganga',
    type: 'gravity',
    purpose: 'multipurpose',
    heightM: 64,
    capacityMW: 115,
    storageMcm: 7322,
    commissioned: 1960,
    reservoir: 'Gandhi Sagar',
    tagline: 'The first of the Chambal cascade',
    desc: 'Gandhi Sagar is the uppermost of four structures on the Chambal, followed by Rana Pratap Sagar, Jawahar Sagar and the Kota barrage. The cascade is an early Indian example of a coordinated multi-dam river development, operated jointly by Madhya Pradesh and Rajasthan.',
    impact: 'Irrigation in the Chambal command across two states, plus power. The surrounding sanctuary protects gharial and Indian skimmer habitat.',
    note: 'Downstream of the cascade, the National Chambal Sanctuary protects one of the last breeding gharial populations in India.',
  },
  {
    name: 'Rana Pratap Sagar Dam',
    icon: '⚙️',
    river: 'Chambal',
    state: 'Rajasthan',
    basin: 'ganga',
    type: 'gravity',
    purpose: 'multipurpose',
    heightM: 54,
    capacityMW: 172,
    storageMcm: 2900,
    commissioned: 1970,
    reservoir: 'Rana Pratap Sagar',
    tagline: 'Second stage of the Chambal Valley Project',
    desc: 'The second structure in the Chambal cascade, taking regulated releases from Gandhi Sagar upstream. The Rawatbhata nuclear power station sits nearby and draws its cooling water from the reservoir, which makes this a rare site where hydro and nuclear generation share a water source.',
    impact: 'Power and irrigation in the Kota division of Rajasthan.',
    note: '',
  },
  {
    name: 'Maithon Dam',
    icon: '🏭',
    river: 'Barakar',
    state: 'Jharkhand',
    basin: 'ganga',
    type: 'gravity',
    purpose: 'multipurpose',
    heightM: 56,
    capacityMW: 60,
    storageMcm: 1348,
    commissioned: 1957,
    reservoir: 'Maithon Reservoir',
    tagline: 'Part of India\'s first river valley authority',
    desc: 'Maithon is one of the four principal dams of the Damodar Valley Corporation, set up in 1948 as India\'s first multipurpose river valley authority and modelled explicitly on the Tennessee Valley Authority. Its underground powerhouse was the first of its kind in South-East Asia.',
    impact: 'Flood control on the Damodar — historically called the "sorrow of Bengal" — plus power and irrigation.',
    note: 'The DVC is as significant institutionally as any of its individual dams: it established the river-basin authority as a model in India.',
  },
  {
    name: 'Panchet Dam',
    icon: '🌊',
    river: 'Damodar',
    state: 'Jharkhand',
    basin: 'ganga',
    type: 'gravity',
    purpose: 'multipurpose',
    heightM: 45,
    capacityMW: 80,
    storageMcm: 1497,
    commissioned: 1959,
    reservoir: 'Panchet Reservoir',
    tagline: 'The last of the DVC\'s original four',
    desc: 'The fourth and final dam of the original Damodar Valley Corporation scheme, completed in 1959. With Maithon, Tilaiya and Konar it forms the flood-moderation system for the lower Damodar, which had flooded the Bengal plain with grim regularity before the DVC was created.',
    impact: 'Flood control, irrigation and power in the Damodar valley.',
    note: 'The DVC scheme as originally conceived envisaged many more dams than the four that were built.',
  },
  {
    name: 'Sivasamudram',
    icon: '💡',
    river: 'Cauvery',
    state: 'Karnataka',
    basin: 'south',
    type: 'barrage',
    purpose: 'hydro',
    heightM: 12,
    capacityMW: 42,
    storageMcm: 0,
    commissioned: 1902,
    reservoir: 'Run-of-river',
    tagline: 'Asia\'s first hydroelectric station',
    desc: 'Commissioned in 1902 at the Cauvery falls, Sivasamudram was the first hydroelectric power station in Asia. Its original purpose was to power the Kolar Gold Fields, and the transmission line built to reach them was among the longest in the world at the time. Bengaluru became one of the first Indian cities with electric street lighting as a result.',
    impact: 'Historically decisive rather than large — it established hydroelectric generation in India.',
    note: 'A run-of-river scheme with negligible storage, which is why it appears here with no reservoir volume.',
  },
  {
    name: 'Baglihar Dam',
    icon: '🏔️',
    river: 'Chenab',
    state: 'Jammu & Kashmir',
    basin: 'indus',
    type: 'gravity',
    purpose: 'hydro',
    heightM: 144,
    capacityMW: 900,
    storageMcm: 475,
    commissioned: 2008,
    reservoir: 'Baglihar Reservoir',
    tagline: 'A run-of-river project that went to international arbitration',
    desc: 'Baglihar is a run-of-river hydroelectric project on the Chenab. Pakistan objected to its design under the Indus Waters Treaty, and the dispute went to a World Bank-appointed Neutral Expert, who in 2007 upheld parts of both cases and required design modifications. It is the most-cited test of the treaty\'s dispute-resolution machinery.',
    impact: 'A significant addition to generation in Jammu and Kashmir.',
    note: 'Under the Indus Waters Treaty India may use the western rivers for run-of-river hydropower but not for large storage, which constrains project design on the Chenab and Jhelum.',
  },
  {
    name: 'Salal Dam',
    icon: '⚡',
    river: 'Chenab',
    state: 'Jammu & Kashmir',
    basin: 'indus',
    type: 'gravity',
    purpose: 'hydro',
    heightM: 113,
    capacityMW: 690,
    storageMcm: 285,
    commissioned: 1987,
    reservoir: 'Salal Reservoir',
    tagline: 'The first major hydro project on the Chenab',
    desc: 'Salal was the first large hydroelectric project built on the Chenab and the first major test of what the Indus Waters Treaty permits India to build on the western rivers. Its design was settled with Pakistan in 1978 after protracted negotiation, and that settlement set precedents used in later projects.',
    impact: 'Generation for the northern grid, and the template for subsequent Chenab projects.',
    note: 'Heavy silt load in the Chenab has been a persistent operating problem at Salal.',
  },
  {
    name: 'Nathpa Jhakri',
    icon: '⛰️',
    river: 'Sutlej',
    state: 'Himachal Pradesh',
    basin: 'indus',
    type: 'barrage',
    purpose: 'hydro',
    heightM: 68,
    capacityMW: 1500,
    storageMcm: 0,
    commissioned: 2004,
    reservoir: 'Run-of-river with pondage',
    tagline: 'India\'s largest run-of-river hydro scheme',
    desc: 'Nathpa Jhakri diverts Sutlej water through a 27 km head-race tunnel to an underground powerhouse, using the drop rather than a reservoir to generate. Run-of-river schemes of this kind submerge far less land than storage dams — but they still fragment the river, and the Sutlej now runs through tunnel for long stretches of its Himachal course.',
    impact: 'One of India\'s largest hydroelectric stations by capacity, feeding the northern grid.',
    note: 'Silt abrasion of turbines during the monsoon is the recurring operational constraint on Himalayan run-of-river schemes.',
  },
  {
    name: 'Sardar Sarovar-adjacent: Omkareshwar',
    icon: '🛕',
    river: 'Narmada',
    state: 'Madhya Pradesh',
    basin: 'narmada',
    type: 'gravity',
    purpose: 'multipurpose',
    heightM: 73,
    capacityMW: 520,
    storageMcm: 987,
    commissioned: 2007,
    reservoir: 'Omkareshwar Reservoir',
    tagline: 'The middle link of the Narmada cascade',
    desc: 'Omkareshwar sits between Indira Sagar upstream and Sardar Sarovar downstream, regulating releases through the middle Narmada. It supplies power and irrigation, and it drew significant protest over submergence around the Omkareshwar temple town and the associated resettlement.',
    impact: 'Power for Madhya Pradesh and irrigation in the Nimar region.',
    note: 'A floating solar installation on the reservoir is among the largest planned in India, an increasingly common way of using reservoir surface area.',
  },
  {
    name: 'Almatti Dam',
    icon: '⚖️',
    river: 'Krishna',
    state: 'Karnataka',
    basin: 'godavari',
    type: 'gravity',
    purpose: 'multipurpose',
    heightM: 160,
    capacityMW: 290,
    storageMcm: 3105,
    commissioned: 2005,
    reservoir: 'Lal Bahadur Shastri Sagar',
    tagline: 'The dam whose permitted height is a legal question',
    desc: 'Almatti is the principal storage of the Upper Krishna Project. How high it may be raised has been litigated for decades, because every additional metre of storage in Karnataka reduces what reaches Andhra Pradesh and Telangana. The Krishna Water Disputes Tribunal has addressed the question more than once and it is still not fully closed.',
    impact: 'Irrigation in northern Karnataka, a chronically drought-prone region, plus power.',
    note: 'Almatti is the clearest illustration that on interstate rivers the contested number is often not the dam\'s cost but its height.',
  },
  {
    name: 'Polavaram Project',
    icon: '🚧',
    river: 'Godavari',
    state: 'Andhra Pradesh',
    basin: 'godavari',
    type: 'embankment',
    purpose: 'multipurpose',
    heightM: 46,
    capacityMW: 960,
    storageMcm: 5511,
    commissioned: 0,
    reservoir: 'Polavaram Reservoir (under construction)',
    tagline: 'Still being built, and already one of the most disputed projects in India',
    desc: 'Polavaram is a national project on the Godavari intended to irrigate a very large command in Andhra Pradesh and to transfer water to the Krishna basin. It has been under construction for years past its original schedule. Its submergence extends into Odisha and Chhattisgarh, both of which have objected, and it affects a substantial Scheduled Tribe population.',
    impact: 'Projected irrigation across seven districts, plus generation and a Godavari–Krishna link. Displacement estimates run above 100,000 people, heavily tribal.',
    note: 'Commissioning year is shown as pending because the project is not complete. Figures here are design values, not achieved ones.',
  },
  {
    name: 'Tilaiya Dam',
    icon: '🌿',
    river: 'Barakar',
    state: 'Jharkhand',
    basin: 'ganga',
    type: 'gravity',
    purpose: 'multipurpose',
    heightM: 30,
    capacityMW: 4,
    storageMcm: 395,
    commissioned: 1953,
    reservoir: 'Tilaiya Reservoir',
    tagline: 'The DVC\'s first dam',
    desc: 'Tilaiya was the first dam completed by the Damodar Valley Corporation, in 1953, and therefore the first structure of India\'s first river valley authority. It is small by later standards, and that is part of its interest — the programme began at a scale that would look modest a decade later.',
    impact: 'Flood moderation on the Barakar and modest power generation.',
    note: '',
  },
  {
    name: 'Mullaperiyar Dam',
    icon: '⚠️',
    river: 'Periyar',
    state: 'Kerala (operated by Tamil Nadu)',
    basin: 'south',
    type: 'gravity',
    purpose: 'irrigation',
    heightM: 53,
    capacityMW: 175,
    storageMcm: 443,
    commissioned: 1895,
    reservoir: 'Mullaperiyar Reservoir',
    tagline: 'Built in 1895, in Kerala, operated by Tamil Nadu',
    desc: 'Mullaperiyar was completed in 1895 using lime-surki mortar, under a 999-year lease agreed in 1886 between the Madras Presidency and Travancore. It stands in Kerala, is operated by Tamil Nadu, and diverts Periyar water east across the Ghats. Kerala has raised safety concerns about a structure of that age and construction; Tamil Nadu depends on the diversion for the Theni command. The Supreme Court has ruled on it more than once.',
    impact: 'Irrigation in five Tamil Nadu districts. The reservoir also created the lake at the centre of Periyar Tiger Reserve.',
    note: 'This is the clearest case in India of a dam whose ownership, operation and risk sit with different parties — which is exactly why it has never been settled.',
  },
  {
    name: 'Ranjit Sagar (Thein) Dam',
    icon: '🏔️',
    river: 'Ravi',
    state: 'Punjab',
    basin: 'indus',
    type: 'embankment',
    purpose: 'multipurpose',
    heightM: 160,
    capacityMW: 600,
    storageMcm: 2344,
    commissioned: 2001,
    reservoir: 'Ranjit Sagar',
    tagline: 'Punjab\'s largest, on the last of the eastern rivers',
    desc: 'Ranjit Sagar is the largest dam in Punjab, on the Ravi near the Jammu border. Under the Indus Waters Treaty the Ravi is one of the eastern rivers allocated to India, so unlike projects on the Chenab it faces no treaty constraint on storage.',
    impact: 'Irrigation in Punjab and Jammu, and generation for the northern grid.',
    note: 'The dam took several decades from conception to commissioning, which is not unusual for Indian storage projects of this size.',
  },
  {
    name: 'Sriram Sagar Project',
    icon: '🌾',
    river: 'Godavari',
    state: 'Telangana',
    basin: 'godavari',
    type: 'gravity',
    purpose: 'irrigation',
    heightM: 43,
    capacityMW: 36,
    storageMcm: 2300,
    commissioned: 1977,
    reservoir: 'Pochampad Reservoir',
    tagline: 'The main irrigation storage of northern Telangana',
    desc: 'Sriram Sagar, also called Pochampad, is the principal irrigation project of northern Telangana, supplying a large command through the Kakatiya canal. Sedimentation has cut its live storage significantly since commissioning, and restoring capacity has been a long-running state priority.',
    impact: 'Irrigation across several northern Telangana districts.',
    note: 'Loss of storage to silt here is among the more severe documented cases in India.',
  },
];

/* ---------------------------------------------------------- superlatives */
const DM_SUPERLATIVES = [
  { icon: '📏', label: 'Tallest dam', value: 'Tehri, 260 m', note: 'On the Bhagirathi in Uttarakhand. Height is measured above the deepest foundation.' },
  { icon: '↔️', label: 'Longest major dam', value: 'Hirakud, ~26 km with dykes', note: 'The longest major earthen dam in the world.' },
  { icon: '🪣', label: 'Largest reservoir by volume', value: 'Indira Sagar, ~12,220 million m³', note: 'On the Narmada in Madhya Pradesh.' },
  { icon: '🗺️', label: 'Largest reservoir by area', value: 'Govind Ballabh Pant Sagar (Rihand)', note: 'Largest artificial lake in India by surface area — a different title from the one above.' },
  { icon: '🏛️', label: 'Oldest still in service', value: 'Kallanai, c. 2nd century CE', note: 'The Grand Anicut on the Cauvery, still diverting water into the delta.' },
  { icon: '💡', label: 'First hydro station in Asia', value: 'Sivasamudram, 1902', note: 'Built to power the Kolar Gold Fields.' },
  { icon: '⚡', label: 'Largest hydro capacity', value: 'Tehri complex, 2,400 MW', note: 'Including its pumped-storage units.' },
  { icon: '🏗️', label: 'First river valley authority', value: 'Damodar Valley Corporation, 1948', note: 'Modelled on the Tennessee Valley Authority.' },
];

/* ------------------------------------------------------------- timeline */
const DM_TIMELINE = [
  { year: 'c. 2nd c. CE', title: 'Kallanai built', desc: 'The Chola Grand Anicut is constructed across the Cauvery, and is still performing its original function today.' },
  { year: '1895', title: 'Mullaperiyar completed', desc: 'Built with lime-surki mortar under an 1886 lease that still governs its operation.' },
  { year: '1902', title: 'Sivasamudram', desc: 'Asia\'s first hydroelectric station is commissioned on the Cauvery to power the Kolar Gold Fields.' },
  { year: '1931–34', title: 'Nizam Sagar and Mettur', desc: 'Two of the largest dams of their day are completed, one by a princely state and one by the Madras Presidency.' },
  { year: '1948', title: 'Damodar Valley Corporation', desc: 'India\'s first multipurpose river valley authority is created, modelled on the Tennessee Valley Authority.' },
  { year: '1954', title: '"Temples of modern India"', desc: 'Nehru uses the phrase at Bhakra. It becomes the defining description of the era\'s dam programme.' },
  { year: '1957', title: 'Hirakud commissioned', desc: 'The longest major earthen dam in the world begins operation on the Mahanadi.' },
  { year: '1958', title: '"The disease of gigantism"', desc: 'Nehru tells the Central Board of Irrigation and Power that India has been suffering from it. The same person said both things, four years apart.' },
  { year: '1960', title: 'Indus Waters Treaty', desc: 'India and Pakistan divide the Indus system: the eastern rivers to India, the western rivers to Pakistan with limited Indian run-of-river use.' },
  { year: '1963', title: 'Bhakra commissioned', desc: 'The Bhakra-Nangal system begins full operation and underwrites the Green Revolution in Punjab and Haryana.' },
  { year: '1967', title: 'Koyna earthquake', desc: 'A magnitude 6.3 earthquake near the Koyna reservoir kills around 180 people and becomes the most-studied case of suspected reservoir-induced seismicity.' },
  { year: '1975', title: 'Farakka commissioned', desc: 'The barrage begins diverting Ganga water to flush Kolkata port, and immediately becomes a bilateral issue with Bangladesh.' },
  { year: '1985', title: 'Narmada Bachao Andolan', desc: 'The movement against the Narmada projects takes organised form and becomes the most sustained anti-dam campaign in India.' },
  { year: '1993', title: 'World Bank withdraws', desc: 'After the Morse Commission review, the World Bank withdraws from the Sardar Sarovar project.' },
  { year: '2000', title: 'Supreme Court allows construction', desc: 'Construction on Sardar Sarovar is permitted to resume, subject to conditions on rehabilitation.' },
  { year: '2006', title: 'Tehri and Sardar Sarovar', desc: 'Both are commissioned, closing out the era of very large storage projects begun decades earlier.' },
  { year: '2021', title: 'Dam Safety Act', desc: 'Parliament passes the Dam Safety Act, creating national and state authorities for surveillance, inspection and maintenance of specified dams.' },
];

/* ------------------------------------------------------------- benefits */
const DM_BENEFITS = [
  { icon: '🌾', title: 'Irrigation', desc: 'Major and medium irrigation projects command a very large share of India\'s irrigated area. The Bhakra command in particular made the Green Revolution possible in Punjab and Haryana, which changed the country\'s food security position within a decade.' },
  { icon: '⚡', title: 'Hydropower', desc: 'India has over 45 GW of installed hydroelectric capacity. Hydro can be dispatched in seconds, which makes it disproportionately valuable for balancing a grid taking on large amounts of solar and wind.' },
  { icon: '🌊', title: 'Flood moderation', desc: 'The Damodar was called the sorrow of Bengal before the DVC dams; Hirakud materially reduced flooding in the Mahanadi delta. Moderation is not elimination, but the difference is measurable.' },
  { icon: '🚰', title: 'Drinking water', desc: 'Tehri supplies Delhi, KRS supplies Mysuru and Bengaluru, Nizam Sagar supplies Hyderabad. Urban water security in much of India runs through a reservoir somewhere upstream.' },
  { icon: '🏭', title: 'Industrial supply', desc: 'Thermal and nuclear stations need cooling water. The Singrauli complex depends on Rihand and Rawatbhata on Rana Pratap Sagar — a dependency that is easy to overlook when tallying what a dam is for.' },
  { icon: '🐟', title: 'Fisheries and navigation', desc: 'Reservoir fisheries support livelihoods at many large projects, and barrages maintain navigable depth — which is the whole reason Farakka exists.' },
];

/* --------------------------------------------------------------- costs */
const DM_COSTS = [
  { icon: '🏘️', title: 'Displacement', desc: 'Large dams have displaced an enormous number of people in India, disproportionately Adivasi and Dalit. Aggregate national estimates vary by an order of magnitude depending on definition and source, which is itself part of the problem — the count was never systematically kept.', severity: 'Critical' },
  { icon: '📋', title: 'Rehabilitation failure', desc: 'Cash compensation without land, resettlement sites prepared after the move rather than before, and rights that were never formally recorded. Hirakud and Pong are the standard case studies. Bhadra-style land-for-land resettlement done in advance is the exception.', severity: 'Critical' },
  { icon: '🏜️', title: 'Sedimentation', desc: 'Reservoirs silt up, and Indian rivers carry heavy loads. Tungabhadra and Sriram Sagar have lost large fractions of live storage. Original project economics rarely priced this in, so the benefit stream was overstated from the start.', severity: 'High' },
  { icon: '🌳', title: 'Submergence of forest and farmland', desc: 'Storage requires area. Indira Sagar, Polavaram and the Narmada projects between them submerged large tracts of forest and cultivated land, with compensatory afforestation that has frequently not matched what was lost in kind.', severity: 'High' },
  { icon: '🐟', title: 'River fragmentation', desc: 'Dams block migratory fish, cut sediment supply to deltas, and change the flow regime downstream. Hilsa migration past Farakka and delta sediment starvation are the clearest Indian examples.', severity: 'High' },
  { icon: '🌍', title: 'Seismicity', desc: 'Reservoir-induced seismicity is contested in general, but Koyna 1967 remains the most-cited case anywhere. Tehri\'s location in Seismic Zone IV has kept the question live for a project of very different scale.', severity: 'Moderate' },
  { icon: '⚖️', title: 'Interstate disputes', desc: 'Cauvery, Krishna, Ravi-Beas, Mahanadi. Storage upstream is water not delivered downstream, so the height of a dam becomes a legal question. Almatti and Mullaperiyar are the sharpest instances.', severity: 'High' },
  { icon: '🏚️', title: 'Ageing infrastructure', desc: 'A large share of India\'s big dams are over twenty-five years old and a significant number are past fifty. Mullaperiyar is over a century. Maintenance and surveillance are the reason the Dam Safety Act, 2021 exists.', severity: 'High' },
];

/* ---------------------------------------------------------- dam safety */
const DM_SAFETY = [
  { icon: '📜', title: 'Dam Safety Act, 2021', desc: 'Establishes the National Dam Safety Authority and state safety organisations, and makes surveillance, inspection, operation and maintenance of specified dams a statutory obligation rather than a matter of practice.' },
  { icon: '🔍', title: 'Why it was needed', desc: 'Dam failures in India have generally followed from inadequate spillway capacity, poor maintenance or foundation problems rather than from design load being exceeded. The Machchhu II failure at Morbi in 1979 remains the worst, and is one of the deadliest dam failures anywhere.' },
  { icon: '📊', title: 'The ageing problem', desc: 'Most large Indian dams were built between the 1950s and the 1980s. Concrete, gates, instrumentation and spillways all have finite service lives, and a large cohort is reaching the end of the design life it was given.' },
  { icon: '🌧️', title: 'Changing hydrology', desc: 'Spillways were sized against historical rainfall records. Where extreme rainfall intensity is shifting, a spillway that was adequate at design time may no longer be, which is why design flood revision has become a standard part of safety review.' },
  { icon: '🛠️', title: 'DRIP', desc: 'The Dam Rehabilitation and Improvement Project, run with World Bank support, has funded structural rehabilitation, instrumentation and emergency action planning at hundreds of dams across multiple states.' },
  { icon: '🚨', title: 'Emergency action plans', desc: 'Inundation mapping and downstream warning arrangements are now required for specified dams. Historically many large Indian dams had neither, which is part of why the 2006 Surat flood unfolded as it did.' },
];

/* -------------------------------------------------------------- gallery */
const DM_GALLERY = [
  { icon: '🧱', title: 'Gravity', caption: 'Held back by mass alone — Bhakra, Nagarjuna Sagar, Sardar Sarovar.' },
  { icon: '🌉', title: 'Arch', caption: 'Idukki transfers load into the canyon walls, using a fraction of the material.' },
  { icon: '⛰️', title: 'Embankment', caption: 'Earth and rock fill — the most common Indian dam type by number.' },
  { icon: '🚧', title: 'Barrage', caption: 'Farakka and the Kallanai divert rather than store.' },
  { icon: '🏛️', title: 'Kallanai', caption: 'Roughly 1,800 years old, still feeding the Cauvery delta.' },
  { icon: '🌾', title: 'Command Area', caption: 'The Bhakra canals underwrote the Green Revolution in Punjab.' },
  { icon: '🏘️', title: 'Submergence', caption: 'Old Tehri and old Bilaspur are both under water.' },
  { icon: '🏜️', title: 'Silt', caption: 'Every reservoir is filling up. Tungabhadra has lost a large share of live storage.' },
  { icon: '⚖️', title: 'Disputed Height', caption: 'At Almatti, the contested number is not cost but metres.' },
  { icon: '🚨', title: 'Dam Safety', caption: 'A large cohort of Indian dams is now past fifty years old.' },
];

/* ---------------------------------------------------------------- facts */
const DM_FACTS = [
  'India has more than 5,700 large dams, the third highest number in the world after China and the United States.',
  'Nehru called Bhakra a temple of modern India in 1954. In 1958 he told the Central Board of Irrigation and Power that the country had been suffering from "the disease of gigantism". Both remarks are his, and an honest account of the period needs both.',
  'The Kallanai on the Cauvery, built by the Chola king Karikalan around the second century CE, is among the oldest water-diversion structures anywhere still doing the job it was built for.',
  'Tehri at 260 m is India\'s tallest dam, and it stands in Seismic Zone IV.',
  'Hirakud is the longest major earthen dam in the world at roughly 26 km including its dykes.',
  'Indira Sagar holds the largest volume of any Indian reservoir; Rihand\'s Govind Ballabh Pant Sagar covers the largest area. Those are two different superlatives and they belong to two different dams.',
  'Sivasamudram on the Cauvery, commissioned in 1902, was the first hydroelectric station in Asia. It was built to power the Kolar Gold Fields.',
  'The Damodar Valley Corporation, created in 1948, was India\'s first multipurpose river valley authority and was modelled directly on the Tennessee Valley Authority.',
  'Mullaperiyar stands in Kerala, is operated by Tamil Nadu under an 1886 lease, and was completed in 1895 with lime-surki mortar rather than cement.',
  'Krishna Raja Sagara was also built without cement, using surki — a lime and brick-dust mortar — under M. Visvesvaraya.',
  'The 1967 Koyna earthquake, magnitude 6.3, is the most-studied candidate case of reservoir-induced seismicity anywhere in the world.',
  'The World Bank withdrew from Sardar Sarovar in 1993 after the Morse Commission review — the first time it had withdrawn from a project of that scale on those grounds.',
  'Nagarjunakonda, a major Buddhist site, was excavated and its principal monuments re-erected on a hilltop island before the Nagarjuna Sagar reservoir filled.',
  'The Dam Safety Act was passed only in 2021 — several decades after most of India\'s large dams were built.',
];

/* ----------------------------------------------------------------- quiz */
const DM_QUIZ = [
  {
    q: 'Which is India\'s tallest dam?',
    options: ['Bhakra', 'Tehri', 'Sardar Sarovar', 'Idukki'],
    answer: 1,
    explain: 'Tehri, at about 260 m on the Bhagirathi in Uttarakhand. It is also in Seismic Zone IV, which was the main objection raised against it.',
  },
  {
    q: 'What did Nehru say about dams in 1958, four years after calling Bhakra a temple of modern India?',
    options: [
      'That India should build twice as many',
      'That the country had suffered from "the disease of gigantism"',
      'That dams should be handed to the states',
      'He never revisited the subject',
    ],
    answer: 1,
    explain: 'He told the Central Board of Irrigation and Power exactly that. Both remarks are his, and quoting only the first gives a misleading picture of his own view.',
  },
  {
    q: 'Which structure is roughly 1,800 years old and still performing its original function?',
    options: ['Mettur Dam', 'Kallanai (Grand Anicut)', 'Nizam Sagar', 'Mullaperiyar'],
    answer: 1,
    explain: 'The Kallanai on the Cauvery, built by the Chola king Karikalan around the second century CE and still diverting water into the delta.',
  },
  {
    q: 'Why did the World Bank withdraw from the Sardar Sarovar project in 1993?',
    options: [
      'Cost overruns',
      'The Morse Commission found resettlement and environmental provisions inadequate',
      'Engineering defects in the dam wall',
      'A dispute between Gujarat and Madhya Pradesh',
    ],
    answer: 1,
    explain: 'The independent Morse Commission review found the project\'s resettlement and environmental provisions inadequate, and the Bank withdrew.',
  },
  {
    q: 'What is the difference between a barrage and a storage dam?',
    options: [
      'A barrage is made of earth rather than concrete',
      'A barrage raises the level to divert flow rather than to store water',
      'A barrage is always smaller than 10 m',
      'There is no functional difference',
    ],
    answer: 1,
    explain: 'A barrage is a low gated structure that controls where water goes. Farakka is the clearest example — it stores almost nothing and yet has been a bilateral issue for fifty years.',
  },
  {
    q: 'Which dam is the most-cited case of suspected reservoir-induced seismicity?',
    options: ['Tehri', 'Koyna', 'Bhakra', 'Hirakud'],
    answer: 1,
    explain: 'Koyna in Maharashtra, after the magnitude 6.3 earthquake near its reservoir in December 1967.',
  },
  {
    q: 'Which reservoir holds the largest volume of water in India?',
    options: ['Gobind Sagar (Bhakra)', 'Indira Sagar', 'Govind Ballabh Pant Sagar (Rihand)', 'Nagarjuna Sagar'],
    answer: 1,
    explain: 'Indira Sagar on the Narmada holds the largest volume. Rihand\'s reservoir is the largest by surface area — a different superlative.',
  },
  {
    q: 'Where is Mullaperiyar Dam, and who operates it?',
    options: [
      'In Tamil Nadu, operated by Tamil Nadu',
      'In Kerala, operated by Tamil Nadu under an 1886 lease',
      'In Kerala, operated jointly by both states',
      'In Karnataka, operated by the central government',
    ],
    answer: 1,
    explain: 'It stands in Kerala and is operated by Tamil Nadu under a lease agreed in 1886 — which is precisely why the dispute has never been settled.',
  },
  {
    q: 'What was the Damodar Valley Corporation modelled on?',
    options: ['The Hoover Dam authority', 'The Tennessee Valley Authority', 'The Nile Basin Commission', 'The Rhine Commission'],
    answer: 1,
    explain: 'The TVA. Created in 1948, the DVC was India\'s first multipurpose river valley authority.',
  },
  {
    q: 'Why does sedimentation matter for a reservoir?',
    options: [
      'It makes the water unsafe to drink',
      'It progressively reduces live storage, shortening the useful life the project was costed against',
      'It causes the dam wall to crack',
      'It has no significant effect',
    ],
    answer: 1,
    explain: 'Silt occupies storage volume. Tungabhadra and Sriram Sagar have both lost large fractions of live storage, and original project economics rarely accounted for it.',
  },
  {
    q: 'Which was the first hydroelectric power station in Asia?',
    options: ['Sivasamudram, 1902', 'Mettur, 1934', 'Bhakra, 1963', 'Koyna, 1964'],
    answer: 0,
    explain: 'Sivasamudram on the Cauvery, commissioned in 1902 to power the Kolar Gold Fields.',
  },
  {
    q: 'What does the Dam Safety Act, 2021 do?',
    options: [
      'Prohibits construction of new large dams',
      'Creates national and state authorities and makes surveillance, inspection and maintenance statutory obligations',
      'Transfers all dams to central ownership',
      'Sets a maximum permissible dam height',
    ],
    answer: 1,
    explain: 'It establishes the National Dam Safety Authority and state safety organisations, and converts what had been good practice into a legal duty — several decades after most Indian dams were built.',
  },
];
